#!/usr/bin/env python3
"""Build vocabulary JSON files for all grades"""
import json, os, sys
# UTF-8
if sys.platform == 'win32':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(BASE, 'data', 'vocabulary', 'grade7.json')

def W(en, zh, ph="", pos="", ex="", ex_zh=""):
    return {"en":en,"zh":zh,"phonetic":ph,"pos":pos,"example":ex,"exampleZh":ex_zh}

# ===================================================================
# 七年级上册 Starter + Unit1-9 | 七年级下册 Unit1-12
# Word data: [en, zh, phonetic, pos, example, example_zh]
# ===================================================================

GRADE7 = {
    "grade":"七年级","semester":"全学年","textbook":"人教版 Go for it! (2012审定版)",
    "units":[]
}

# ------------ Starter ------------
starter = [
    ["good","好的","/ɡʊd/","adj.","Good morning!","早上好！"],
    ["morning","早晨；上午","/ˈmɔːnɪŋ/","n.","Good morning!","早上好！"],
    ["hi","嗨；喂","/haɪ/","interj.","Hi! How are you?","嗨！你好吗？"],
    ["hello","你好；喂","/həˈloʊ/","interj.","Hello! Nice to meet you.","你好！"],
    ["afternoon","下午","/ˌæftərˈnuːn/","n.","Good afternoon!","下午好！"],
    ["evening","晚上；傍晚","/ˈiːvnɪŋ/","n.","Good evening!","晚上好！"],
    ["how","怎样；如何","/haʊ/","adv.","How are you?","你好吗？"],
    ["are","是","/ɑːr/","v.","How are you?","你好吗？"],
    ["you","你；你们","/juː/","pron.","How are you?","你好吗？"],
    ["I","我","/aɪ/","pron.","I am fine.","我很好。"],
    ["am","是","/æm/","v.","I am a student.","我是一名学生。"],
    ["fine","健康的；美好的","/faɪn/","adj.","I'm fine, thanks.","我很好，谢谢。"],
    ["thanks","感谢；谢谢","/θæŋks/","interj. & n.","Thanks for your help.","谢谢你的帮助。"],
    ["OK","好；可以","/ˌoʊˈkeɪ/","interj. & adv.","That's OK.","没关系。"],
    ["what","什么","/wɑːt/","pron.","What is this?","这是什么？"],
    ["is","是","/ɪz/","v.","What's your name?","你叫什么名字？"],
    ["this","这；这个","/ðɪs/","pron.","This is a pen.","这是一支笔。"],
    ["in","用；在……里","/ɪn/","prep.","Write it in English.","用英语写。"],
    ["English","英语","/ˈɪŋɡlɪʃ/","n.","I like English.","我喜欢英语。"],
    ["map","地图","/mæp/","n.","There is a map.","有一张地图。"],
    ["cup","杯子","/kʌp/","n.","A cup of tea.","一杯茶。"],
    ["ruler","尺子","/ˈruːlər/","n.","Use a ruler.","用尺子。"],
    ["pen","笔；钢笔","/pen/","n.","Use a pen.","用笔。"],
    ["jacket","夹克衫","/ˈdʒækɪt/","n.","A black jacket.","一件黑色夹克。"],
    ["color","颜色","/ˈkʌlər/","n.","What color?","什么颜色？"],
    ["red","红色的","/red/","adj.","Red apple.","红苹果。"],
    ["yellow","黄色的","/ˈjeloʊ/","adj.","Yellow banana.","黄香蕉。"],
    ["green","绿色的","/ɡriːn/","adj.","Green trees.","绿树。"],
    ["blue","蓝色的","/bluː/","adj.","Blue sky.","蓝天。"],
    ["black","黑色的","/blæk/","adj.","Black hair.","黑发。"],
    ["white","白色的","/waɪt/","adj.","White snow.","白雪。"],
    ["purple","紫色的","/ˈpɜːrpl/","adj.","Purple dress.","紫裙。"],
    ["brown","棕色的","/braʊn/","adj.","Brown bag.","棕色包。"],
    ["the","这/那个；这/那些","/ðə/","art.","The book.","那本书。"],
    ["now","现在","/naʊ/","adv.","Now or never.","机不可失。"],
    ["see","看见","/siː/","v.","I see a bird.","我看见鸟。"],
    ["can","能；可以","/kæn/","modal v.","Can you help?","能帮忙吗？"],
    ["say","说；讲","/seɪ/","v.","Say it again.","再说一遍。"],
    ["my","我的","/maɪ/","pron.","My book.","我的书。"],
    ["spell","拼写","/spel/","v.","Spell your name.","拼写名字。"],
    ["please","请","/pliːz/","interj.","Please sit down.","请坐。"],
]
GRADE7["units"].append({"unit":0,"title":"Starter Units 1-3","words":[W(*w) for w in starter]})

# ------------ U1: My name's Gina (correct order from textbook) ------------
u1 = [
    ["name","名字；名称","/neɪm/","n.","My name is Gina.","我叫吉娜。"],
    ["nice","好的；令人愉快的","/naɪs/","adj.","Nice to meet you.","很高兴见到你。"],
    ["to","不定式符号","/tuː/","part.","I want to go.","我想去。"],
    ["meet","遇见；相逢","/miːt/","v.","Glad to meet you.","很高兴认识你。"],
    ["too","也；太","/tuː/","adv.","Nice to meet you, too.","我也很高兴认识你。"],
    ["your","你的；你们的","/jʊr/","pron.","What's your name?","你叫什么名字？"],
    ["Ms.","女士","/mɪz/","n.","Ms. Brown.","布朗女士。"],
    ["his","他的","/hɪz/","pron.","His name is Eric.","他叫埃里克。"],
    ["and","和；又；而","/ænd/","conj.","Tom and Jerry.","汤姆和杰瑞。"],
    ["her","她的","/hɜːr/","pron.","Her bag is red.","她的包是红色的。"],
    ["yes","是的","/jes/","interj.","Yes, please.","好的。"],
    ["she","她","/ʃiː/","pron.","She is my friend.","她是我的朋友。"],
    ["he","他","/hiː/","pron.","He is a student.","他是学生。"],
    ["no","不；没有；不是","/noʊ/","interj.","No, thank you.","不，谢谢。"],
    ["not","不；没有","/nɑːt/","adv.","She is not here.","她不在这。"],
    ["zero","零","/ˈzɪroʊ/","num.","Zero degrees.","零度。"],
    ["one","一","/wʌn/","num.","One brother.","一个哥哥。"],
    ["two","二","/tuː/","num.","Two cats.","两只猫。"],
    ["three","三","/θriː/","num.","Three books.","三本书。"],
    ["four","四","/fɔːr/","num.","Four legs.","四条腿。"],
    ["five","五","/faɪv/","num.","Five minutes.","五分钟。"],
    ["six","六","/sɪks/","num.","Six o'clock.","六点。"],
    ["seven","七","/ˈsevn/","num.","Seven days.","七天。"],
    ["eight","八","/eɪt/","num.","Eight o'clock.","八点。"],
    ["nine","九","/naɪn/","num.","Nine apples.","九个苹果。"],
    ["telephone","电话","/ˈtelɪfoʊn/","n.","Telephone number.","电话号码。"],
    ["number","号码；数字","/ˈnʌmbər/","n.","Phone number.","电话号码。"],
    ["first","第一","/fɜːrst/","adj.","First name.","名字。"],
    ["last","最后的；末尾的","/læst/","adj.","Last name.","姓。"],
    ["friend","朋友","/frend/","n.","My best friend.","最好的朋友。"],
    ["China","中国","/ˈtʃaɪnə/","n.","I'm from China.","我来自中国。"],
    ["middle","中间的","/ˈmɪdl/","adj.","Middle school.","中学。"],
    ["school","学校","/skuːl/","n.","Go to school.","去上学。"],
]
GRADE7["units"].append({"unit":1,"title":"上册 Unit 1 My name's Gina.","words":[W(*w) for w in u1]})

# ------------ U2: This is my sister ------------
u2 = [
    ["sister","姐；妹","/ˈsɪstər/","n.","This is my sister.","这是我姐姐。"],
    ["mother","母亲；妈妈","/ˈmʌðər/","n.","My mother is a nurse.","我妈妈是护士。"],
    ["father","父亲；爸爸","/ˈfɑːðər/","n.","My father is a doctor.","我爸爸是医生。"],
    ["parent","父（母）亲","/ˈperənt/","n.","My parents are kind.","我的父母很好。"],
    ["brother","兄；弟","/ˈbrʌðər/","n.","I have two brothers.","我有两个兄弟。"],
    ["grandmother","（外）祖母","/ˈɡrænmʌðər/","n.","My grandmother is 70.","我奶奶70岁。"],
    ["grandfather","（外）祖父","/ˈɡrænfɑːðər/","n.","He likes fishing.","他喜欢钓鱼。"],
    ["grandparent","祖父（母）","/ˈɡrænperənt/","n.","My grandparents.","我的祖父母。"],
    ["family","家；家庭","/ˈfæməli/","n.","I love my family.","我爱我家。"],
    ["those","那些","/ðoʊz/","pron.","Those are my books.","那些是我的书。"],
    ["who","谁","/huː/","pron.","Who is that girl?","那个女孩是谁？"],
    ["these","这些","/ðiːz/","pron.","These are my pencils.","这些是我的铅笔。"],
    ["they","他/她/它们","/ðeɪ/","pron.","They are classmates.","他们是同学。"],
    ["have","有","/hæv/","v.","I have a happy family.","我有个幸福的家。"],
    ["son","儿子","/sʌn/","n.","He is my son.","他是我儿子。"],
    ["cousin","堂/表兄弟姐妹","/ˈkʌzn/","n.","My cousin is funny.","我表弟很搞笑。"],
    ["aunt","姑/姨/伯母/婶母","/ænt/","n.","My aunt is a doctor.","我姑姑是医生。"],
    ["uncle","舅/叔/伯/姑父","/ˈʌŋkl/","n.","My uncle lives in Shanghai.","我叔叔住上海。"],
    ["daughter","女儿","/ˈdɔːtər/","n.","Their daughter is six.","他们女儿6岁。"],
    ["photo","照片","/ˈfoʊtoʊ/","n.","A photo of my family.","全家福。"],
    ["picture","照片；图画","/ˈpɪktʃər/","n.","Draw a picture.","画一幅画。"],
    ["here","这就是；在这里","/hɪr/","adv.","Here is your book.","这是你的书。"],
    ["of","属于……的","/ʌv/","prep.","The door of the room.","房间的门。"],
    ["next","下一个（的）","/nekst/","adj. & n.","Next one.","下一个。"],
    ["girl","女孩","/ɡɜːrl/","n.","The girl is my sister.","那女孩是我妹妹。"],
    ["dog","狗","/dɔːɡ/","n.","A lovely dog.","一只可爱的狗。"],
]
GRADE7["units"].append({"unit":2,"title":"上册 Unit 2 This is my sister.","words":[W(*w) for w in u2]})

# ------------ U3: Is this your pencil? ------------
u3 = [
    ["pencil","铅笔","/ˈpensl/","n.","Is this your pencil?","这是你的铅笔吗？"],
    ["book","书","/bʊk/","n.","This book is interesting.","这本书很有趣。"],
    ["eraser","橡皮","/ɪˈreɪsər/","n.","May I borrow your eraser?","借你的橡皮？"],
    ["box","箱；盒","/bɑːks/","n.","What's in the box?","盒子里有什么？"],
    ["schoolbag","书包","/ˈskuːlbæɡ/","n.","My schoolbag is heavy.","我的书包很重。"],
    ["dictionary","词典；字典","/ˈdɪkʃəneri/","n.","An English dictionary.","英语词典。"],
    ["mine","我的","/maɪn/","pron.","This pen is mine.","这支笔是我的。"],
    ["hers","她的","/hɜːrz/","pron.","The red bag is hers.","那个红包是她的。"],
    ["excuse","原谅；宽恕","/ɪkˈskjuːz/","v.","Excuse me.","打扰一下。"],
    ["me","我（宾格）","/miː/","pron.","Can you help me?","你能帮我吗？"],
    ["thank","感谢","/θæŋk/","v.","Thank you.","谢谢你。"],
    ["teacher","老师","/ˈtiːtʃər/","n.","Our English teacher.","我们的英语老师。"],
    ["about","关于","/əˈbaʊt/","prep.","What about you?","你呢？"],
    ["yours","你的；你们的","/jɔːrz/","pron.","Is this book yours?","这本书是你的吗？"],
    ["for","为了；给","/fɔːr/","prep.","This gift is for you.","这礼物给你的。"],
    ["help","帮助","/help/","v. & n.","Can you help me?","你能帮我吗？"],
    ["welcome","受欢迎的","/ˈwelkəm/","adj.","You're welcome.","不用谢。"],
    ["baseball","棒球","/ˈbeɪsbɔːl/","n.","Play baseball.","打棒球。"],
    ["watch","表；手表","/wɑːtʃ/","n.","My watch is new.","我的手表是新的。"],
    ["computer","计算机","/kəmˈpjuːtər/","n.","I use a computer.","我用电脑。"],
    ["game","游戏；比赛","/ɡeɪm/","n.","Let's play a game.","玩游戏吧。"],
    ["card","卡片","/kɑːrd/","n.","Birthday card.","生日卡片。"],
    ["notebook","笔记本","/ˈnoʊtbʊk/","n.","Write in your notebook.","写在笔记本上。"],
    ["ring","戒指","/rɪŋ/","n.","A gold ring.","金戒指。"],
    ["bag","袋；包","/bæɡ/","n.","What's in your bag?","包里有什么？"],
    ["library","图书馆","/ˈlaɪbreri/","n.","Study in the library.","在图书馆学习。"],
    ["ask","请求；询问","/æsk/","v.","May I ask a question?","问个问题？"],
    ["find","找到；发现","/faɪnd/","v.","I can't find my keys.","找不到钥匙。"],
    ["some","一些","/sʌm/","adj.","Some water.","一些水。"],
    ["classroom","教室","/ˈklæsruːm/","n.","Our classroom.","我们的教室。"],
    ["e-mail","电子邮件","/ˈiːmeɪl/","n.","Send me an e-mail.","给我发邮件。"],
    ["at","在(某处/时间)","/æt/","prep.","At home.","在家。"],
    ["call","打电话","/kɔːl/","v.","Call me tonight.","今晚打给我。"],
    ["lost","遗失；丢失","/lɔːst/","v.","I lost my watch.","我丢了手表。"],
    ["must","必须","/mʌst/","modal v.","You must study.","你必须学习。"],
    ["set","一套；一副","/set/","n.","A set of keys.","一串钥匙。"],
]
GRADE7["units"].append({"unit":3,"title":"上册 Unit 3 Is this your pencil?","words":[W(*w) for w in u3]})

# ------------ U4: Where's my schoolbag? ------------
u4 = [
    ["where","在哪里","/wer/","adv.","Where's my schoolbag?","我的书包在哪？"],
    ["table","桌子","/ˈteɪbl/","n.","On the table.","在桌子上。"],
    ["bed","床","/bed/","n.","On the bed.","在床上。"],
    ["bookcase","书架","/ˈbʊkkeɪs/","n.","In the bookcase.","在书架里。"],
    ["sofa","沙发","/ˈsoʊfə/","n.","On the sofa.","在沙发上。"],
    ["chair","椅子","/tʃer/","n.","On the chair.","在椅子上。"],
    ["on","在……上","/ɑːn/","prep.","On the desk.","在书桌上。"],
    ["under","在……下","/ˈʌndər/","prep.","Under the table.","在桌子下。"],
    ["come","来；来到","/kʌm/","v.","Come here.","过来。"],
    ["desk","书桌","/desk/","n.","On the desk.","在书桌上。"],
    ["think","认为；想","/θɪŋk/","v.","I think so.","我也这么认为。"],
    ["room","房间","/ruːm/","n.","My room is clean.","我的房间很干净。"],
    ["their","他/她/它们的","/ðer/","pron.","Their house.","他们的房子。"],
    ["hat","帽子","/hæt/","n.","Take off your hat.","脱帽。"],
    ["head","头","/hed/","n.","My head hurts.","我头疼。"],
    ["yeah","是的；对","/jeə/","interj.","Yeah, I know.","是的，我知道。"],
    ["know","知道","/noʊ/","v.","I don't know.","我不知道。"],
    ["radio","收音机","/ˈreɪdioʊ/","n.","Listen to the radio.","听收音机。"],
    ["clock","时钟","/klɑːk/","n.","The clock says 8.","钟显示8点。"],
    ["tape","磁带；录音带","/teɪp/","n.","English tape.","英语磁带。"],
    ["player","播放机","/ˈpleɪər/","n.","CD player.","CD播放机。"],
    ["model","模型","/ˈmɑːdl/","n.","Model plane.","模型飞机。"],
    ["plane","飞机","/pleɪn/","n.","The plane flies.","飞机在飞。"],
    ["tidy","整洁的","/ˈtaɪdi/","adj.","Keep your room tidy.","保持房间整洁。"],
    ["but","但是","/bʌt/","conj.","I like it, but it's expensive.","喜欢但太贵。"],
    ["our","我们的","/ˈaʊər/","pron.","Our classroom.","我们的教室。"],
    ["everywhere","处处；到处","/ˈevriwer/","adv.","I looked everywhere.","我到处找了。"],
    ["always","总是","/ˈɔːlweɪz/","adv.","She is always happy.","她总是很开心。"],
]
GRADE7["units"].append({"unit":4,"title":"上册 Unit 4 Where's my schoolbag?","words":[W(*w) for w in u4]})

# ------------ U5: Do you have a soccer ball? ------------
u5 = [
    ["do","做；用于构成疑问","/duː/","aux v.","Do you have a soccer ball?","你有足球吗？"],
    ["have","有","/hæv/","v.","I have a basketball.","我有一个篮球。"],
    ["tennis","网球","/ˈtenɪs/","n.","Play tennis.","打网球。"],
    ["ball","球","/bɔːl/","n.","A ball.","一个球。"],
    ["ping-pong","乒乓球","/ˈpɪŋpɒŋ/","n.","Play ping-pong.","打乒乓球。"],
    ["bat","球棒；球拍","/bæt/","n.","Ping-pong bat.","乒乓球拍。"],
    ["soccer","足球","/ˈsɒkər/","n.","Soccer ball.","足球。"],
    ["volleyball","排球","/ˈvɒlibɔːl/","n.","Volleyball team.","排球队。"],
    ["basketball","篮球","/ˈbɑːskɪtbɔːl/","n.","Play basketball.","打篮球。"],
    ["hey","嘿；喂","/heɪ/","interj.","Hey, wait!","嘿，等等！"],
    ["let","允许；让","/let/","v.","Let me help.","让我帮忙。"],
    ["us","我们（宾格）","/ʌs/","pron.","Let us go.","我们走吧。"],
    ["go","去；走","/ɡoʊ/","v.","Go to school.","去上学。"],
    ["we","我们","/wiː/","pron.","We are friends.","我们是朋友。"],
    ["late","迟到","/leɪt/","adj.","Don't be late.","不要迟到。"],
    ["has","有（have三单）","/hæz/","v.","He has a new bike.","他有新自行车。"],
    ["get","去取；得到","/ɡet/","v.","Get your book.","拿你的书。"],
    ["great","美妙的；伟大的","/ɡreɪt/","adj.","That's great!","太棒了！"],
    ["play","参加比赛；玩耍","/pleɪ/","v.","Let's play.","我们一起玩。"],
    ["sound","听起来好像","/saʊnd/","v.","That sounds good.","听起来不错。"],
    ["interesting","有趣的","/ˈɪntrəstɪŋ/","adj.","Interesting book.","有趣的书。"],
    ["boring","无聊的","/ˈbɔːrɪŋ/","adj.","Boring movie.","无聊的电影。"],
    ["fun","有趣的；乐趣","/fʌn/","adj. & n.","Have fun!","玩得开心！"],
    ["difficult","困难的","/ˈdɪfɪkəlt/","adj.","Difficult math.","难的数学。"],
    ["relaxing","轻松的","/rɪˈlæksɪŋ/","adj.","Relaxing music.","轻松的音乐。"],
    ["watch","注视；观看","/wɑːtʃ/","v.","Watch TV.","看电视。"],
    ["TV","电视","/ˌtiːˈviː/","n.","Watch TV.","看电视。"],
    ["same","相同的","/seɪm/","adj.","Same class.","同班。"],
    ["love","爱；喜爱","/lʌv/","v. & n.","I love English.","我爱英语。"],
    ["with","和……一起","/wɪð/","prep.","Play with friends.","和朋友玩。"],
    ["sport","体育运动","/spɔːrt/","n.","Like sports.","喜欢运动。"],
    ["them","他/她/它们(宾格)","/ðəm/","pron.","I like them.","我喜欢他们。"],
    ["only","只；仅","/ˈoʊnli/","adv.","Only one.","只有一个。"],
    ["like","喜欢","/laɪk/","v.","I like apples.","我喜欢苹果。"],
    ["easy","容易的","/ˈiːzi/","adj.","Easy question.","简单的问题。"],
    ["after","在……以后","/ˈæftər/","prep.","After school.","放学后。"],
    ["class","班级；课","/klæs/","n.","Our class.","我们班。"],
    ["classmate","同班同学","/ˈklæsmeɪt/","n.","He is my classmate.","他是我同班同学。"],
]
GRADE7["units"].append({"unit":5,"title":"上册 Unit 5 Do you have a soccer ball?","words":[W(*w) for w in u5]})

# ------------ U6: Do you like bananas? ------------
u6 = [
    ["banana","香蕉","/bəˈnænə/","n.","I like bananas.","我喜欢香蕉。"],
    ["hamburger","汉堡包","/ˈhæmbɜːrɡər/","n.","A hamburger.","一个汉堡。"],
    ["tomato","西红柿","/təˈmeɪtoʊ/","n.","Tomatoes are healthy.","西红柿有益健康。"],
    ["ice-cream","冰激凌","/ˌaɪsˈkriːm/","n.","Children like ice-cream.","孩子们喜欢冰激凌。"],
    ["salad","沙拉","/ˈsæləd/","n.","Fruit salad.","水果沙拉。"],
    ["strawberry","草莓","/ˈstrɔːberi/","n.","Strawberries are my favorite.","草莓是我的最爱。"],
    ["pear","梨","/per/","n.","This pear is sweet.","这个梨很甜。"],
    ["milk","牛奶","/mɪlk/","n.","Drink milk every day.","每天喝牛奶。"],
    ["bread","面包","/bred/","n.","Bread for breakfast.","早餐吃面包。"],
    ["birthday","生日","/ˈbɜːrθdeɪ/","n.","Happy birthday!","生日快乐！"],
    ["dinner","正餐","/ˈdɪnər/","n.","Have dinner.","吃晚饭。"],
    ["week","周；星期","/wiːk/","n.","Seven days a week.","一周七天。"],
    ["food","食物","/fuːd/","n.","Chinese food.","中国食物。"],
    ["sure","当然；肯定","/ʃʊr/","adv.","Sure, I can help.","当然，可以帮忙。"],
    ["vegetable","蔬菜","/ˈvedʒtəbl/","n.","Eat vegetables.","吃蔬菜。"],
    ["fruit","水果","/fruːt/","n.","Fresh fruit.","新鲜水果。"],
    ["right","正确的","/raɪt/","adj.","That's right.","没错。"],
    ["apple","苹果","/ˈæpl/","n.","An apple a day.","每天一个苹果。"],
    ["then","那么","/ðen/","adv.","Then let's go.","那我们走吧。"],
    ["egg","蛋；鸡蛋","/eɡ/","n.","Two eggs.","两个鸡蛋。"],
    ["carrot","胡萝卜","/ˈkærət/","n.","Rabbits like carrots.","兔子喜欢胡萝卜。"],
    ["rice","大米；米饭","/raɪs/","n.","Eat rice.","吃米饭。"],
    ["chicken","鸡肉","/ˈtʃɪkɪn/","n.","Have chicken.","吃鸡肉。"],
    ["so","那么","/soʊ/","conj.","So, what do you think?","你觉得呢？"],
    ["breakfast","早餐","/ˈbrekfəst/","n.","Have breakfast.","吃早餐。"],
    ["lunch","午餐","/lʌntʃ/","n.","Have lunch.","吃午餐。"],
    ["star","明星；星星","/stɑːr/","n.","Movie star.","电影明星。"],
    ["eat","吃","/iːt/","v.","Let's eat.","我们吃吧。"],
    ["well","好；令人满意地","/wel/","adv.","Well done!","干得好！"],
    ["habit","习惯","/ˈhæbɪt/","n.","Good habit.","好习惯。"],
    ["healthy","健康的","/ˈhelθi/","adj.","Healthy food.","健康食物。"],
    ["really","真正地","/ˈriːəli/","adv.","Really like it.","真的喜欢。"],
    ["question","问题","/ˈkwestʃən/","n.","Ask a question.","问个问题。"],
    ["want","需要；想要","/wɑːnt/","v.","Want to learn.","想学。"],
    ["fat","胖的","/fæt/","adj.","Too much junk food makes you fat.","太多垃圾食品让你变胖。"],
]
GRADE7["units"].append({"unit":6,"title":"上册 Unit 6 Do you like bananas?","words":[W(*w) for w in u6]})

# ------------ U7: How much are these socks? ------------
u7 = [
    ["much","许多；多少","/mʌtʃ/","pron. & adj.","How much?","多少钱？"],
    ["sock","短袜","/sɒk/","n.","These socks.","这些袜子。"],
    ["T-shirt","T恤衫","/ˈtiːʃɜːrt/","n.","White T-shirt.","白T恤。"],
    ["shorts","短裤","/ʃɔːrts/","n.","Wear shorts.","穿短裤。"],
    ["sweater","毛衣","/ˈswetər/","n.","A warm sweater.","温暖的毛衣。"],
    ["trousers","裤子","/ˈtraʊzərz/","n.","Too long.","太长了。"],
    ["shoe","鞋","/ʃuː/","n.","New shoes.","新鞋。"],
    ["skirt","裙子","/skɜːrt/","n.","Red skirt.","红裙子。"],
    ["dollar","元（$）","/ˈdɒlər/","n.","Ten dollars.","十美元。"],
    ["big","大的","/bɪɡ/","adj.","Too big.","太大了。"],
    ["small","小的","/smɔːl/","adj.","Too small.","太小了。"],
    ["short","短的；矮的","/ʃɔːrt/","adj.","Too short.","太短了。"],
    ["long","长的","/lɔːŋ/","adj.","Very long.","很长。"],
    ["woman","女子","/ˈwʊmən/","n.","The woman in red.","穿红衣的女人。"],
    ["need","需要","/niːd/","v.","I need a new bag.","我需要新包。"],
    ["look","看；看上去","/lʊk/","v.","You look beautiful.","你看起来很漂亮。"],
    ["pair","一双；一对","/per/","n.","A pair of shoes.","一双鞋。"],
    ["take","买下；拿；取","/teɪk/","v.","I'll take this.","我要这个。"],
    ["ten","十","/ten/","num.","Ten dollars.","十美元。"],
    ["Mr.","先生","/ˈmɪstər/","n.","Mr. Green.","格林先生。"],
    ["clothes","衣服；服装","/kloʊðz/","n.","Buy new clothes.","买新衣服。"],
    ["store","商店","/stɔːr/","n.","Clothing store.","服装店。"],
    ["buy","购买；买","/baɪ/","v.","Buy a gift.","买礼物。"],
    ["sale","特价销售","/seɪl/","n.","On sale.","打折。"],
    ["sell","出售","/sel/","v.","Sell clothes.","卖衣服。"],
    ["all","所有的","/ɔːl/","adj.","All students.","所有学生。"],
    ["very","很；非常","/ˈveri/","adv.","Very good.","非常好。"],
    ["price","价格","/praɪs/","n.","What's the price?","什么价格？"],
    ["boy","男孩","/bɔɪ/","n.","The boy is playing.","男孩在玩。"],
]
GRADE7["units"].append({"unit":7,"title":"上册 Unit 7 How much are these socks?","words":[W(*w) for w in u7]})

# ------------ U8: When is your birthday? ------------
u8 = [
    ["when","什么时候","/wen/","adv.","When is your birthday?","你的生日是什么时候？"],
    ["month","月；月份","/mʌnθ/","n.","12 months.","12个月。"],
    ["January","一月","/ˈdʒænjueri/","n.","In January.","在一月。"],
    ["February","二月","/ˈfebrueri/","n.","In February.","在二月。"],
    ["March","三月","/mɑːrtʃ/","n.","In March.","在三月。"],
    ["April","四月","/ˈeɪprəl/","n.","In April.","在四月。"],
    ["May","五月","/meɪ/","n.","In May.","在五月。"],
    ["June","六月","/dʒuːn/","n.","In June.","在六月。"],
    ["July","七月","/dʒuˈlaɪ/","n.","In July.","在七月。"],
    ["August","八月","/ˈɔːɡəst/","n.","In August.","在八月。"],
    ["September","九月","/sepˈtembər/","n.","In September.","在九月。"],
    ["October","十月","/ɒkˈtoʊbər/","n.","In October.","在十月。"],
    ["November","十一月","/noʊˈvembər/","n.","In November.","在十一月。"],
    ["December","十二月","/dɪˈsembər/","n.","In December.","在十二月。"],
    ["happy","愉快的；高兴的","/ˈhæpi/","adj.","Happy birthday!","生日快乐！"],
    ["old","年老的；旧的","/oʊld/","adj.","How old are you?","你多大了？"],
    ["party","聚会；晚会","/ˈpɑːrti/","n.","Birthday party.","生日聚会。"],
    ["first","第一","/fɜːrst/","adj.","First month.","第一个月。"],
    ["test","测验；检查","/test/","n.","English test.","英语测验。"],
    ["trip","旅游；旅行","/trɪp/","n.","School trip.","学校旅行。"],
    ["art","艺术；美术","/ɑːrt/","n.","Art class.","美术课。"],
    ["festival","节日","/ˈfestɪvl/","n.","Spring Festival.","春节。"],
    ["dear","亲爱的","/dɪr/","adj.","My dear.","亲爱的。"],
    ["student","学生","/ˈstuːdnt/","n.","A good student.","好学生。"],
    ["thing","东西；事情","/θɪŋ/","n.","What's that thing?","那是什么？"],
    ["term","学期","/tɜːrm/","n.","This term.","这学期。"],
    ["busy","忙碌的","/ˈbɪzi/","adj.","I'm busy.","我很忙。"],
    ["time","时间","/taɪm/","n.","What time is it?","几点了？"],
    ["there","（在）那里","/ðer/","adv.","Put it there.","放那里。"],
]
GRADE7["units"].append({"unit":8,"title":"上册 Unit 8 When is your birthday?","words":[W(*w) for w in u8]})

# ------------ U9: My favorite subject is science ------------
u9 = [
    ["favorite","特别喜爱的","/ˈfeɪvərɪt/","adj. & n.","My favorite subject.","我最爱的科目。"],
    ["subject","学科；科目","/ˈsʌbdʒɪkt/","n.","How many subjects?","几门科目？"],
    ["science","科学","/ˈsaɪəns/","n.","I like science.","我喜欢科学。"],
    ["P.E.","体育","/ˌpiːˈiː/","n.","P.E. class.","体育课。"],
    ["music","音乐","/ˈmjuːzɪk/","n.","Listen to music.","听音乐。"],
    ["math","数学","/mæθ/","n.","Math is fun.","数学有趣。"],
    ["Chinese","语文；汉语；中国的","/ˌtʃaɪˈniːz/","n. & adj.","Chinese class.","语文课。"],
    ["geography","地理（学）","/dʒiˈɒɡrəfi/","n.","Geography class.","地理课。"],
    ["history","历史","/ˈhɪstri/","n.","History is interesting.","历史很有趣。"],
    ["why","为什么","/waɪ/","adv.","Why do you like it?","你为什么喜欢？"],
    ["because","因为","/bɪˈkɔːz/","conj.","Because it's fun.","因为它有趣。"],
    ["Monday","星期一","/ˈmʌndeɪ/","n.","On Monday.","在周一。"],
    ["Friday","星期五","/ˈfraɪdeɪ/","n.","Happy Friday!","周五快乐！"],
    ["Saturday","星期六","/ˈsætərdeɪ/","n.","On Saturday.","在周六。"],
    ["free","空闲的","/friː/","adj.","Are you free?","你有空吗？"],
    ["cool","妙极的；酷的","/kuːl/","adj.","That's cool!","太酷了！"],
    ["Tuesday","星期二","/ˈtuːzdeɪ/","n.","On Tuesday.","在周二。"],
    ["Wednesday","星期三","/ˈwenzdeɪ/","n.","On Wednesday.","在周三。"],
    ["Thursday","星期四","/ˈθɜːrzdeɪ/","n.","On Thursday.","在周四。"],
    ["Sunday","星期日","/ˈsʌndeɪ/","n.","On Sunday.","在周日。"],
    ["A.M.","上午","/ˌeɪˈem/","abbr.","8:00 a.m.","上午8点。"],
    ["P.M.","下午","/ˌpiːˈem/","abbr.","3:00 p.m.","下午3点。"],
    ["useful","有用的","/ˈjuːsfl/","adj.","English is useful.","英语很有用。"],
    ["from","从……开始","/frʌm/","prep.","From China.","来自中国。"],
    ["Mrs.","太太；夫人","/ˈmɪsɪz/","n.","Mrs. Smith.","史密斯夫人。"],
    ["finish","完成","/ˈfɪnɪʃ/","v.","Finish homework.","完成作业。"],
    ["lesson","课；一节课","/ˈlesn/","n.","English lesson.","英语课。"],
    ["hour","小时","/ˈaʊər/","n.","Two hours.","两小时。"],
]
GRADE7["units"].append({"unit":9,"title":"上册 Unit 9 My favorite subject is science.","words":[W(*w) for w in u9]})

# ================================================================
# 下册 Units 1-12
# ================================================================
d1 = [
    ["guitar","吉他","/ɡɪˈtɑːr/","n.","Play the guitar.","弹吉他。"],
    ["sing","唱歌","/sɪŋ/","v.","She can sing.","她会唱歌。"],
    ["swim","游泳","/swɪm/","v.","I can swim.","我会游泳。"],
    ["dance","跳舞；舞蹈","/dæns/","v. & n.","She likes to dance.","她喜欢跳舞。"],
    ["draw","画","/drɔː/","v.","Draw pictures.","画画。"],
    ["chess","国际象棋","/tʃes/","n.","Play chess.","下象棋。"],
    ["join","参加；加入","/dʒɔɪn/","v.","Join the club.","加入俱乐部。"],
    ["club","俱乐部；社团","/klʌb/","n.","Music club.","音乐俱乐部。"],
    ["tell","讲述；告诉","/tel/","v.","Tell a story.","讲故事。"],
    ["story","故事；小说","/ˈstɔːri/","n.","A bedtime story.","睡前故事。"],
    ["write","写作；写字","/raɪt/","v.","Write your name.","写名字。"],
    ["show","演出；展示","/ʃoʊ/","n. & v.","Talent show.","才艺表演。"],
    ["talk","说话；交谈","/tɔːk/","v. & n.","Let's talk.","我们谈谈。"],
    ["kung fu","功夫","/ˌkʌŋ ˈfuː/","n.","Learn kung fu.","学功夫。"],
    ["drum","鼓","/drʌm/","n.","Play the drums.","打鼓。"],
    ["piano","钢琴","/piˈænoʊ/","n.","Play the piano.","弹钢琴。"],
    ["violin","小提琴","/ˌvaɪəˈlɪn/","n.","Play the violin.","拉小提琴。"],
    ["also","也；而且","/ˈɔːlsoʊ/","adv.","I also like it.","我也喜欢。"],
    ["people","人；人们","/ˈpiːpl/","n.","Many people.","许多人。"],
    ["home","家；到家","/hoʊm/","n. & adv.","Go home.","回家。"],
    ["make","使成为；制造","/meɪk/","v.","Make a cake.","做蛋糕。"],
    ["today","在今天","/təˈdeɪ/","adv.","What day is it today?","今天周几？"],
    ["center","中心；中央","/ˈsentər/","n.","In the center.","在中央。"],
    ["weekend","周末","/ˈwiːkend/","n.","On the weekend.","在周末。"],
    ["teach","教；讲授","/tiːtʃ/","v.","Teach us English.","教我们英语。"],
    ["musician","音乐家","/mjuˈzɪʃn/","n.","Be a musician.","成为音乐家。"],
]
GRADE7["units"].append({"unit":10,"title":"下册 Unit 1 Can you play the guitar?","words":[W(*w) for w in d1]})

d2 = [
    ["up","向上","/ʌp/","adv.","Get up.","起床。"],
    ["dress","连衣裙；穿衣","/dres/","n. & v.","Get dressed.","穿衣服。"],
    ["brush","刷；刷子","/brʌʃ/","v. & n.","Brush teeth.","刷牙。"],
    ["tooth","牙齿","/tuːθ/","n.","Brush your teeth.","刷牙。"],
    ["shower","淋浴","/ˈʃaʊər/","n. & v.","Take a shower.","洗澡。"],
    ["usually","通常地","/ˈjuːʒuəli/","adv.","I usually get up at 6.","我通常6点起。"],
    ["forty","四十","/ˈfɔːrti/","num.","Forty minutes.","40分钟。"],
    ["never","从不","/ˈnevər/","adv.","I never smoke.","我从不抽烟。"],
    ["early","早的","/ˈɜːrli/","adj. & adv.","Get up early.","早起。"],
    ["fifty","五十","/ˈfɪfti/","num.","Fifty years.","50年。"],
    ["job","工作；职业","/dʒɑːb/","n.","A good job.","好工作。"],
    ["work","工作","/wɜːrk/","v. & n.","Go to work.","去工作。"],
    ["station","电视台；车站","/ˈsteɪʃn/","n.","TV station.","电视台。"],
    ["o'clock","……点钟","/əˈklɒk/","adv.","Seven o'clock.","七点。"],
    ["night","晚上","/naɪt/","n.","At night.","在晚上。"],
    ["funny","滑稽的","/ˈfʌni/","adj.","A funny story.","搞笑故事。"],
    ["exercise","锻炼","/ˈeksərsaɪz/","v. & n.","Do exercise.","做运动。"],
    ["best","最好的（地）","/best/","adj. & adv.","Best friend.","最好的朋友。"],
    ["group","组；团体","/ɡruːp/","n.","Study group.","学习小组。"],
    ["half","一半","/hæf/","n.","Half an hour.","半小时。"],
    ["past","过（时间）","/pæst/","prep.","Half past eight.","八点半。"],
    ["quarter","一刻钟；四分之一","/ˈkwɔːrtər/","n.","A quarter to nine.","八点四十五。"],
    ["homework","家庭作业","/ˈhoʊmwɜːrk/","n.","Do homework.","做作业。"],
    ["run","跑","/rʌn/","v.","Run fast.","快跑。"],
    ["clean","打扫；干净的","/kliːn/","v. & adj.","Clean the room.","打扫房间。"],
    ["walk","行走；散步","/wɔːk/","n. & v.","Take a walk.","散步。"],
    ["quickly","迅速地","/ˈkwɪkli/","adv.","Run quickly.","快跑。"],
    ["either","也（否定）","/ˈiːðər/","adv.","I don't like it either.","我也不喜欢。"],
    ["lot","大量；许多","/lɒt/","pron.","A lot of books.","许多书。"],
    ["sometimes","有时","/ˈsʌmtaɪmz/","adv.","Sometimes I walk.","有时我走路。"],
    ["taste","尝起来；味道","/teɪst/","v. & n.","It tastes good.","味道好。"],
    ["life","生活；生命","/laɪf/","n.","A happy life.","幸福生活。"],
]
GRADE7["units"].append({"unit":11,"title":"下册 Unit 2 What time do you go to school?","words":[W(*w) for w in d2]})

d3 = [
    ["train","火车","/treɪn/","n.","By train.","坐火车。"],
    ["bus","公交车","/bʌs/","n.","By bus.","坐公交。"],
    ["subway","地铁","/ˈsʌbweɪ/","n.","Take the subway.","坐地铁。"],
    ["ride","骑；旅程","/raɪd/","v. & n.","Ride a bike.","骑自行车。"],
    ["bike","自行车","/baɪk/","n.","Ride a bike.","骑自行车。"],
    ["sixty","六十","/ˈsɪksti/","num.","Sixty years.","60年。"],
    ["seventy","七十","/ˈsevnti/","num.","Seventy years.","70年。"],
    ["eighty","八十","/ˈeɪti/","num.","Eighty years.","80年。"],
    ["ninety","九十","/ˈnaɪnti/","num.","Ninety years.","90年。"],
    ["hundred","一百","/ˈhʌndrəd/","num.","One hundred.","一百。"],
    ["minute","分钟","/ˈmɪnɪt/","n.","Wait a minute.","等一分钟。"],
    ["far","远","/fɑːr/","adv. & adj.","How far?","多远？"],
    ["kilometer","公里","/kɪˈlɒmɪtər/","n.","Five kilometers.","五公里。"],
    ["new","新的","/njuː/","adj.","A new book.","新书。"],
    ["every","每一","/ˈevri/","adj.","Every day.","每天。"],
    ["by","通过；乘","/baɪ/","prep.","By bus.","坐公交。"],
    ["drive","开车","/draɪv/","v.","Drive a car.","开车。"],
    ["car","小汽车","/kɑːr/","n.","By car.","坐小汽车。"],
    ["live","居住；生活","/lɪv/","v.","I live in Beijing.","我住北京。"],
    ["stop","车站；停止","/stɒp/","n. & v.","Bus stop.","公交站。"],
    ["cross","横过","/krɒs/","v.","Cross the road.","过马路。"],
    ["river","河；江","/ˈrɪvər/","n.","Cross the river.","过河。"],
    ["many","许多","/ˈmeni/","adj. & pron.","Many books.","许多书。"],
    ["village","村庄","/ˈvɪlɪdʒ/","n.","A small village.","小村庄。"],
    ["between","在……之间","/bɪˈtwiːn/","prep.","Between A and B.","在A和B之间。"],
    ["bridge","桥","/brɪdʒ/","n.","Cross the bridge.","过桥。"],
    ["boat","小船","/boʊt/","n.","By boat.","坐船。"],
    ["ropeway","索道","/ˈroʊpweɪ/","n.","By ropeway.","坐索道。"],
    ["year","年","/jɪr/","n.","This year.","今年。"],
    ["afraid","害怕的","/əˈfreɪd/","adj.","I'm afraid.","我害怕。"],
    ["like","像","/laɪk/","prep.","Like a bird.","像只鸟。"],
    ["leave","离开","/liːv/","v.","Leave home.","离开家。"],
    ["dream","梦想；做梦","/driːm/","n. & v.","My dream.","我的梦想。"],
    ["true","真实的","/truː/","adj.","Come true.","实现。"],
]
GRADE7["units"].append({"unit":12,"title":"下册 Unit 3 How do you get to school?","words":[W(*w) for w in d3]})

d4 = [
    ["rule","规则","/ruːl/","n.","Follow the rules.","遵守规则。"],
    ["arrive","到达","/əˈraɪv/","v.","Arrive on time.","准时到达。"],
    ["hallway","走廊","/ˈhɔːlweɪ/","n.","Don't run in the hallways.","不要在走廊跑。"],
    ["hall","大厅","/hɔːl/","n.","Dining hall.","餐厅。"],
    ["listen","听","/ˈlɪsn/","v.","Listen to the teacher.","听老师讲。"],
    ["fight","打架；战斗","/faɪt/","v. & n.","Don't fight.","不要打架。"],
    ["sorry","抱歉的","/ˈsɒri/","adj.","I'm sorry.","对不起。"],
    ["outside","在外面","/ˌaʊtˈsaɪd/","adv.","Go outside.","出去。"],
    ["wear","穿；戴","/wer/","v.","Wear a uniform.","穿校服。"],
    ["important","重要的","/ɪmˈpɔːrtnt/","adj.","It's important.","很重要。"],
    ["bring","带来","/brɪŋ/","v.","Bring your book.","带你的书来。"],
    ["uniform","校服","/ˈjuːnɪfɔːrm/","n.","School uniform.","校服。"],
    ["quiet","安静的","/ˈkwaɪət/","adj.","Be quiet.","安静。"],
    ["out","外出","/aʊt/","adv.","Go out.","出去。"],
    ["practice","练习","/ˈpræktɪs/","v. & n.","Practice English.","练习英语。"],
    ["dish","碟；盘","/dɪʃ/","n.","Wash the dishes.","洗碗。"],
    ["before","在……以前","/bɪˈfɔːr/","prep.","Before dinner.","晚饭前。"],
    ["dirty","脏的","/ˈdɜːrti/","adj.","Dirty hands.","脏手。"],
    ["kitchen","厨房","/ˈkɪtʃɪn/","n.","In the kitchen.","在厨房里。"],
    ["more","更多的","/mɔːr/","adj. & pron.","More water.","更多水。"],
    ["noisy","吵闹的","/ˈnɔɪzi/","adj.","Too noisy.","太吵了。"],
    ["relax","放松","/rɪˈlæks/","v.","Time to relax.","放松时间。"],
    ["read","阅读","/riːd/","v.","Read a book.","读书。"],
    ["terrible","可怕的","/ˈterəbl/","adj.","Terrible weather.","糟糕的天气。"],
    ["feel","感受","/fiːl/","v.","Feel good.","感觉好。"],
    ["strict","严格的","/strɪkt/","adj.","Strict teacher.","严格的老师。"],
    ["remember","记住","/rɪˈmembər/","v.","Remember me?","记得我吗？"],
    ["follow","遵循","/ˈfɒloʊ/","v.","Follow me.","跟我来。"],
    ["luck","幸运","/lʌk/","n.","Good luck!","祝好运！"],
    ["keep","保持","/kiːp/","v.","Keep quiet.","保持安静。"],
    ["hair","头发","/her/","n.","Long hair.","长发。"],
    ["learn","学习","/lɜːrn/","v.","Learn English.","学英语。"],
]
GRADE7["units"].append({"unit":13,"title":"下册 Unit 4 Don't eat in class.","words":[W(*w) for w in d4]})

d5 = [
    ["panda","熊猫","/ˈpændə/","n.","I like pandas.","我喜欢熊猫。"],
    ["zoo","动物园","/zuː/","n.","Go to the zoo.","去动物园。"],
    ["tiger","老虎","/ˈtaɪɡər/","n.","A big tiger.","大老虎。"],
    ["elephant","大象","/ˈelɪfənt/","n.","Elephants are big.","大象很大。"],
    ["koala","考拉","/koʊˈɑːlə/","n.","Koalas from Australia.","澳洲考拉。"],
    ["lion","狮子","/ˈlaɪən/","n.","The king lion.","狮子王。"],
    ["giraffe","长颈鹿","/dʒəˈræf/","n.","Long neck giraffe.","长颈鹿。"],
    ["animal","动物","/ˈænɪml/","n.","Favorite animal.","最喜欢的动物。"],
    ["cute","可爱的","/kjuːt/","adj.","A cute baby.","可爱的宝宝。"],
    ["lazy","懒惰的","/ˈleɪzi/","adj.","A lazy cat.","懒猫。"],
    ["smart","聪明的","/smɑːrt/","adj.","A smart boy.","聪明的男孩。"],
    ["beautiful","美丽的","/ˈbjuːtɪfl/","adj.","Beautiful flower.","美丽的花。"],
    ["scary","吓人的","/ˈskeri/","adj.","A scary movie.","恐怖电影。"],
    ["kind","种类","/kaɪnd/","n.","What kind?","什么种类？"],
    ["Australia","澳大利亚","/ɒˈstreɪliə/","n.","From Australia.","来自澳大利亚。"],
    ["south","南方的","/saʊθ/","adj.","South China.","华南。"],
    ["Africa","非洲","/ˈæfrɪkə/","n.","In Africa.","在非洲。"],
    ["pet","宠物","/pet/","n.","A pet dog.","宠物狗。"],
    ["leg","腿","/leɡ/","n.","Four legs.","四条腿。"],
    ["cat","猫","/kæt/","n.","I have a cat.","我有一只猫。"],
    ["sleep","睡觉","/sliːp/","v. & n.","Go to sleep.","去睡觉。"],
    ["friendly","友好的","/ˈfrendli/","adj.","A friendly smile.","友好的微笑。"],
    ["shy","羞怯的","/ʃaɪ/","adj.","A shy girl.","害羞的女孩。"],
    ["save","拯救","/seɪv/","v.","Save animals.","拯救动物。"],
    ["symbol","象征","/ˈsɪmbl/","n.","A symbol of peace.","和平象征。"],
    ["flag","旗","/flæɡ/","n.","National flag.","国旗。"],
    ["forget","忘记","/fərˈɡet/","v.","Don't forget.","别忘了。"],
    ["place","地点","/pleɪs/","n.","A beautiful place.","美丽的地方。"],
    ["water","水","/ˈwɔːtər/","n.","Drink water.","喝水。"],
    ["danger","危险","/ˈdeɪndʒər/","n.","In danger.","处于危险。"],
    ["cut","砍；切","/kʌt/","v.","Cut down trees.","砍树。"],
    ["down","向下","/daʊn/","adv.","Sit down.","坐下。"],
    ["tree","树","/triː/","n.","A big tree.","大树。"],
    ["kill","杀死","/kɪl/","v.","Don't kill animals.","别杀动物。"],
    ["ivory","象牙","/ˈaɪvəri/","n.","Ivory is expensive.","象牙很贵。"],
    ["over","超过","/ˈoʊvər/","prep.","Over 100.","超过100。"],
    ["Thailand","泰国","/ˈtaɪlænd/","n.","Thai elephants.","泰国大象。"],
]
GRADE7["units"].append({"unit":14,"title":"下册 Unit 5 Why do you like pandas?","words":[W(*w) for w in d5]})

d6 = [
    ["newspaper","报纸","/ˈnjuːzpeɪpər/","n.","Read a newspaper.","看报纸。"],
    ["use","使用","/juːz/","v.","Use a computer.","用电脑。"],
    ["soup","汤","/suːp/","n.","Make soup.","做汤。"],
    ["wash","洗","/wɒʃ/","v.","Wash dishes.","洗碗。"],
    ["movie","电影","/ˈmuːvi/","n.","Watch a movie.","看电影。"],
    ["just","只是；恰好","/dʒʌst/","adv.","Just a minute.","等一下。"],
    ["house","房子","/haʊs/","n.","My house.","我家。"],
    ["drink","喝；饮料","/drɪŋk/","v. & n.","Drink tea.","喝茶。"],
    ["tea","茶","/tiː/","n.","A cup of tea.","一杯茶。"],
    ["tomorrow","明天","/təˈmɒroʊ/","adv.","See you tomorrow.","明天见。"],
    ["pool","游泳池","/puːl/","n.","Swimming pool.","游泳池。"],
    ["shop","购物；商店","/ʃɒp/","v. & n.","Go shopping.","去购物。"],
    ["supermarket","超市","/ˈsuːpərmɑːrkɪt/","n.","At the supermarket.","在超市。"],
    ["man","男人；人","/mæn/","n.","A young man.","年轻男人。"],
    ["race","竞赛","/reɪs/","n.","Dragon boat race.","龙舟比赛。"],
    ["host","主人；东道主","/hoʊst/","n.","The host family.","寄宿家庭。"],
    ["study","学习；研究","/ˈstʌdi/","v. & n.","Study hard.","努力学习。"],
    ["state","州","/steɪt/","n.","The United States.","美国。"],
    ["American","美国的；美国人","/əˈmerɪkən/","adj. & n.","American food.","美国食物。"],
    ["dragon","龙","/ˈdræɡən/","n.","Dragon dance.","舞龙。"],
    ["any","任何的","/ˈeni/","adj.","Any questions?","有问题吗？"],
    ["other","另外的","/ˈʌðər/","adj.","Other people.","其他人。"],
    ["young","年轻的","/jʌŋ/","adj.","Young people.","年轻人。"],
    ["child","儿童","/tʃaɪld/","n.","A child.","一个小孩。"],
    ["miss","怀念；思念","/mɪs/","v.","I miss you.","我想你。"],
    ["wish","希望","/wɪʃ/","v.","I wish you well.","祝你安好。"],
    ["delicious","美味的","/dɪˈlɪʃəs/","adj.","Delicious food.","美味的食物。"],
    ["still","还；仍然","/stɪl/","adv.","Still here.","还在这里。"],
]
GRADE7["units"].append({"unit":15,"title":"下册 Unit 6 I'm watching TV.","words":[W(*w) for w in d6]})

d7 = [
    ["rain","下雨；雨","/reɪn/","v. & n.","It's raining.","正在下雨。"],
    ["windy","多风的","/ˈwɪndi/","adj.","Windy day.","刮风天。"],
    ["cloudy","多云的","/ˈklaʊdi/","adj.","Cloudy sky.","多云天。"],
    ["sunny","晴朗的","/ˈsʌni/","adj.","Sunny day.","晴天。"],
    ["snow","下雪；雪","/snoʊ/","v. & n.","It's snowing.","正在下雪。"],
    ["weather","天气","/ˈweðər/","n.","Good weather.","好天气。"],
    ["cook","做饭","/kʊk/","v.","Cook dinner.","做晚饭。"],
    ["bad","坏的","/bæd/","adj.","Bad weather.","坏天气。"],
    ["park","公园","/pɑːrk/","n.","In the park.","在公园。"],
    ["message","信息；消息","/ˈmesɪdʒ/","n.","Take a message.","捎个口信。"],
    ["him","他（宾格）","/hɪm/","pron.","Call him.","给他打电话。"],
    ["could","能；可以","/kʊd/","v.","Could you help?","能帮忙吗？"],
    ["back","回来","/bæk/","adj.","Call back.","回电话。"],
    ["problem","困难；难题","/ˈprɒbləm/","n.","No problem.","没问题。"],
    ["again","再一次","/əˈɡen/","adv.","Say it again.","再说一遍。"],
    ["dry","干燥的","/draɪ/","adj.","Dry weather.","干燥的天气。"],
    ["cold","寒冷的","/koʊld/","adj.","Too cold.","太冷了。"],
    ["hot","热的","/hɒt/","adj.","Very hot.","很热。"],
    ["warm","温暖的","/wɔːrm/","adj.","Warm spring.","暖春。"],
    ["visit","拜访","/ˈvɪzɪt/","v.","Visit friends.","拜访朋友。"],
    ["Canada","加拿大","/ˈkænədə/","n.","From Canada.","来自加拿大。"],
    ["summer","夏天","/ˈsʌmər/","n.","Hot summer.","炎热的夏天。"],
    ["sit","坐","/sɪt/","v.","Sit down.","坐下。"],
    ["juice","果汁","/dʒuːs/","n.","Orange juice.","橙汁。"],
    ["soon","不久","/suːn/","adv.","See you soon.","一会儿见。"],
    ["vacation","假期","/veɪˈkeɪʃn/","n.","On vacation.","度假。"],
    ["hard","努力地","/hɑːrd/","adv.","Study hard.","努力学习。"],
    ["Europe","欧洲","/ˈjʊrəp/","n.","In Europe.","在欧洲。"],
    ["mountain","高山","/ˈmaʊntən/","n.","High mountain.","高山。"],
    ["country","国家","/ˈkʌntri/","n.","My country.","我的国家。"],
    ["skate","滑冰","/skeɪt/","v.","Go skating.","去滑冰。"],
    ["snowy","下雪的","/ˈsnoʊi/","adj.","Snowy day.","下雪天。"],
    ["winter","冬天","/ˈwɪntər/","n.","Cold winter.","寒冷的冬天。"],
    ["Russian","俄罗斯的；俄语","/ˈrʌʃn/","adj. & n.","Russian winter.","俄罗斯的冬天。"],
    ["snowman","雪人","/ˈsnoʊmæn/","n.","Make a snowman.","堆雪人。"],
    ["rainy","多雨的","/ˈreɪni/","adj.","Rainy season.","雨季。"],
]
GRADE7["units"].append({"unit":16,"title":"下册 Unit 7 It's raining!","words":[W(*w) for w in d7]})

d8 = [
    ["post","邮政","/poʊst/","n.","Post office.","邮局。"],
    ["office","办公室","/ˈɒfɪs/","n.","Post office.","邮局。"],
    ["police","警察","/pəˈliːs/","n.","Police station.","警察局。"],
    ["hotel","旅馆","/hoʊˈtel/","n.","Stay at a hotel.","住旅馆。"],
    ["restaurant","餐馆","/ˈrestrɒnt/","n.","Chinese restaurant.","中餐馆。"],
    ["bank","银行","/bæŋk/","n.","In the bank.","在银行。"],
    ["hospital","医院","/ˈhɒspɪtl/","n.","Go to the hospital.","去医院。"],
    ["street","大街","/striːt/","n.","On the street.","在街上。"],
    ["pay","付费","/peɪ/","v.","Pay phone.","付费电话。"],
    ["near","在附近","/nɪr/","prep.","Near the school.","学校附近。"],
    ["across","过；穿过","/əˈkrɒs/","adv.","Across the street.","街对面。"],
    ["front","前面","/frʌnt/","n.","In front of.","在……前面。"],
    ["behind","在……后面","/bɪˈhaɪnd/","prep.","Behind the door.","门后面。"],
    ["town","镇","/taʊn/","n.","A small town.","小镇。"],
    ["around","到处；围绕","/əˈraʊnd/","adv. & prep.","Look around.","环顾四周。"],
    ["north","北；北方的","/nɔːrθ/","n. & adj.","North Street.","北街。"],
    ["along","沿着","/əˈlɒŋ/","prep.","Go along the street.","沿着街走。"],
    ["turn","转向","/tɜːrn/","v.","Turn left.","左转。"],
    ["right","向右边；右边","/raɪt/","adv. & n.","Turn right.","右转。"],
    ["left","向左边；左边","/left/","adv. & n.","Turn left.","左转。"],
    ["crossing","十字路口","/ˈkrɒsɪŋ/","n.","At the crossing.","在十字路口。"],
    ["neighborhood","街区","/ˈneɪbərhʊd/","n.","My neighborhood.","我家附近。"],
    ["spend","花（时间、钱）","/spend/","v.","Spend time.","花时间。"],
    ["climb","爬","/klaɪm/","v.","Climb the mountain.","爬山。"],
    ["road","路","/roʊd/","n.","On the road.","在路上。"],
    ["often","时常","/ˈɒfn/","adv.","I often walk.","我常走路。"],
    ["air","空气","/er/","n.","Fresh air.","新鲜空气。"],
    ["sunshine","阳光","/ˈsʌnʃaɪn/","n.","Enjoy the sunshine.","享受阳光。"],
    ["free","免费的","/friː/","adj.","Free lunch.","免费午餐。"],
    ["enjoy","享受；喜爱","/ɪnˈdʒɔɪ/","v.","Enjoy reading.","喜欢阅读。"],
    ["easily","容易地","/ˈiːzəli/","adv.","Find it easily.","容易找到。"],
    ["money","钱","/ˈmʌni/","n.","Make money.","赚钱。"],
]
GRADE7["units"].append({"unit":17,"title":"下册 Unit 8 Is there a post office near here?","words":[W(*w) for w in d8]})

d9 = [
    ["curly","卷曲的","/ˈkɜːrli/","adj.","Curly hair.","卷发。"],
    ["straight","直的","/streɪt/","adj.","Straight hair.","直发。"],
    ["tall","高的","/tɔːl/","adj.","Tall and thin.","又高又瘦。"],
    ["medium","中等的","/ˈmiːdiəm/","adj.","Medium height.","中等身高。"],
    ["height","身高","/haɪt/","n.","Of medium height.","中等个子。"],
    ["thin","瘦的","/θɪn/","adj.","A thin boy.","瘦男孩。"],
    ["heavy","重的","/ˈhevi/","adj.","A heavy box.","重箱子。"],
    ["build","身材","/bɪld/","n.","Of medium build.","中等身材。"],
    ["tonight","今夜","/təˈnaɪt/","adv. & n.","See you tonight.","今晚见。"],
    ["little","小的","/ˈlɪtl/","adj.","A little boy.","小男孩。"],
    ["cinema","电影院","/ˈsɪnəmə/","n.","Go to the cinema.","去电影院。"],
    ["glasses","眼镜","/ˈɡlɑːsɪz/","n.","Wear glasses.","戴眼镜。"],
    ["later","以后","/ˈleɪtər/","adj.","See you later.","回头见。"],
    ["handsome","英俊的","/ˈhænsəm/","adj.","A handsome man.","英俊的男人。"],
    ["actor","演员","/ˈæktər/","n.","A famous actor.","著名演员。"],
    ["actress","女演员","/ˈæktrəs/","n.","A great actress.","优秀女演员。"],
    ["person","人","/ˈpɜːrsn/","n.","A nice person.","一个好人。"],
    ["nose","鼻子","/noʊz/","n.","A big nose.","大鼻子。"],
    ["blonde","金黄色的","/blɒnd/","adj.","Blonde hair.","金发。"],
    ["mouth","嘴","/maʊθ/","n.","Open your mouth.","张嘴。"],
    ["round","圆形的","/raʊnd/","adj.","Round face.","圆脸。"],
    ["face","脸","/feɪs/","n.","A smile on her face.","脸上的微笑。"],
    ["eye","眼睛","/aɪ/","n.","Blue eyes.","蓝眼睛。"],
    ["singer","歌手","/ˈsɪŋər/","n.","A pop singer.","流行歌手。"],
    ["artist","艺术家","/ˈɑːrtɪst/","n.","A great artist.","伟大的艺术家。"],
    ["crime","犯罪活动","/kraɪm/","n.","Fight crime.","打击犯罪。"],
    ["criminal","罪犯","/ˈkrɪmɪnl/","n.","A criminal.","一个罪犯。"],
    ["put","放","/pʊt/","v.","Put it here.","放这里。"],
    ["each","每个","/iːtʃ/","adj. & pron.","Each student.","每个学生。"],
    ["way","方式","/weɪ/","n.","This way.","这边。"],
    ["describe","描述","/dɪˈskraɪb/","v.","Describe him.","描述他。"],
    ["differently","不同地","/ˈdɪfrəntli/","adv.","Think differently.","不同地思考。"],
    ["another","另一","/əˈnʌðər/","adj. & pron.","Another one.","另一个。"],
    ["end","结尾","/end/","n.","In the end.","最后。"],
    ["real","真正的","/rɪəl/","adj.","A real story.","真实故事。"],
    ["jeans","牛仔裤","/dʒiːnz/","n.","Blue jeans.","蓝色牛仔裤。"],
]
GRADE7["units"].append({"unit":18,"title":"下册 Unit 9 What does he look like?","words":[W(*w) for w in d9]})

d10 = [
    ["noodle","面条","/ˈnuːdl/","n.","A bowl of noodles.","一碗面条。"],
    ["mutton","羊肉","/ˈmʌtn/","n.","Mutton noodles.","羊肉面。"],
    ["beef","牛肉","/biːf/","n.","Beef noodles.","牛肉面。"],
    ["cabbage","卷心菜","/ˈkæbɪdʒ/","n.","Cabbage soup.","卷心菜汤。"],
    ["potato","土豆","/pəˈteɪtoʊ/","n.","Fried potatoes.","炸土豆。"],
    ["special","特色菜；特别的","/ˈspeʃl/","n. & adj.","Today's special.","今日特色菜。"],
    ["would","愿意","/wʊd/","v.","I'd like some noodles.","我想要面条。"],
    ["yet","还；仍然","/jet/","adv.","Not yet.","还没有。"],
    ["large","大号的","/lɑːrdʒ/","adj.","A large bowl.","大碗。"],
    ["order","点菜；命令","/ˈɔːrdər/","n. & v.","Take your order.","为您点菜。"],
    ["size","大小","/saɪz/","n.","What size?","什么大小？"],
    ["bowl","碗","/boʊl/","n.","A bowl of rice.","一碗米饭。"],
    ["tofu","豆腐","/ˈtoʊfuː/","n.","Tofu salad.","豆腐沙拉。"],
    ["meat","肉","/miːt/","n.","Eat meat.","吃肉。"],
    ["dumpling","饺子","/ˈdʌmplɪŋ/","n.","Make dumplings.","包饺子。"],
    ["porridge","粥","/ˈpɒrɪdʒ/","n.","Rice porridge.","米粥。"],
    ["onion","洋葱","/ˈʌnjən/","n.","Cut onions.","切洋葱。"],
    ["fish","鱼","/fɪʃ/","n.","Fresh fish.","鲜鱼。"],
    ["pancake","烙饼","/ˈpænkeɪk/","n.","Make pancakes.","做烙饼。"],
    ["world","世界","/wɜːrld/","n.","Around the world.","世界各地。"],
    ["answer","答案；回答","/ˈænsər/","n. & v.","Answer the question.","回答问题。"],
    ["different","不同的","/ˈdɪfrənt/","adj.","Different kinds.","不同种类。"],
    ["cake","蛋糕","/keɪk/","n.","Birthday cake.","生日蛋糕。"],
    ["candle","蜡烛","/ˈkændl/","n.","Blow out candles.","吹蜡烛。"],
    ["age","年龄","/eɪdʒ/","n.","What's your age?","你多大年龄？"],
    ["blow","吹","/bloʊ/","v.","Blow out.","吹灭。"],
    ["if","如果","/ɪf/","conj.","If you like it.","如果你喜欢。"],
    ["will","会","/wɪl/","v.","I will go.","我会去的。"],
    ["the UK","英国","","n.","From the UK.","来自英国。"],
    ["candy","糖果","/ˈkændi/","n.","Sweet candy.","甜甜的糖果。"],
    ["lucky","幸运的","/ˈlʌki/","adj.","Lucky you!","你真幸运！"],
    ["popular","受欢迎的","/ˈpɒpjələr/","adj.","Popular food.","受欢迎的食物。"],
    ["idea","想法","/aɪˈdɪə/","n.","Good idea!","好主意！"],
]
GRADE7["units"].append({"unit":19,"title":"下册 Unit 10 I'd like some noodles.","words":[W(*w) for w in d10]})

d11 = [
    ["milk","挤奶","/mɪlk/","v.","Milk a cow.","给奶牛挤奶。"],
    ["cow","奶牛","/kaʊ/","n.","Milk cows.","挤奶牛。"],
    ["horse","马","/hɔːrs/","n.","Ride a horse.","骑马。"],
    ["feed","喂养","/fiːd/","v.","Feed chickens.","喂鸡。"],
    ["farmer","农民","/ˈfɑːrmər/","n.","A farmer.","一个农民。"],
    ["quite","相当","/kwaɪt/","adv.","Quite a lot.","相当多。"],
    ["anything","任何东西","/ˈeniθɪŋ/","pron.","Anything else?","还要别的吗？"],
    ["grow","种植；生长","/ɡroʊ/","v.","Grow vegetables.","种蔬菜。"],
    ["farm","农场","/fɑːrm/","n.","On the farm.","在农场。"],
    ["pick","采；摘","/pɪk/","v.","Pick apples.","摘苹果。"],
    ["excellent","极好的","/ˈeksələnt/","adj.","Excellent job!","干得好！"],
    ["countryside","乡村","/ˈkʌntrisaɪd/","n.","In the countryside.","在乡下。"],
    ["yesterday","昨天","/ˈjestərdeɪ/","n.","Yesterday morning.","昨天早上。"],
    ["flower","花","/ˈflaʊər/","n.","Beautiful flowers.","美丽的花。"],
    ["worry","担心","/ˈwʌri/","v.","Don't worry.","别担心。"],
    ["luckily","幸运地","/ˈlʌkɪli/","adv.","Luckily, I passed.","幸运的是，我过了。"],
    ["sun","太阳","/sʌn/","n.","The sun shines.","太阳照耀。"],
    ["museum","博物馆","/mjuˈziːəm/","n.","Visit a museum.","参观博物馆。"],
    ["fire","火灾","/ˈfaɪər/","n.","Fire station.","消防站。"],
    ["painting","油画","/ˈpeɪntɪŋ/","n.","A famous painting.","著名油画。"],
    ["exciting","使人兴奋的","/ɪkˈsaɪtɪŋ/","adj.","An exciting trip.","令人兴奋的旅程。"],
    ["lovely","可爱的","/ˈlʌvli/","adj.","A lovely day.","美好的一天。"],
    ["expensive","昂贵的","/ɪkˈspensɪv/","adj.","Too expensive.","太贵了。"],
    ["cheap","便宜的","/tʃiːp/","adj.","Cheap clothes.","便宜的衣服。"],
    ["slow","缓慢的","/sloʊ/","adj.","Slow down.","慢下来。"],
    ["fast","快地","/fæst/","adv. & adj.","Run fast.","快跑。"],
    ["robot","机器人","/ˈroʊbɒt/","n.","A robot.","一个机器人。"],
    ["guide","导游","/ɡaɪd/","n.","A tour guide.","导游。"],
    ["gift","礼物","/ɡɪft/","n.","A birthday gift.","生日礼物。"],
    ["everything","一切","/ˈevriθɪŋ/","pron.","Everything is fine.","一切都好。"],
    ["interested","感兴趣的","/ˈɪntrəstɪd/","adj.","I'm interested in English.","我对英语感兴趣。"],
    ["dark","黑暗的","/dɑːrk/","adj.","In the dark.","在黑暗中。"],
    ["hear","听到","/hɪr/","v.","I can hear you.","我能听见你。"],
]
GRADE7["units"].append({"unit":20,"title":"下册 Unit 11 How was your school trip?","words":[W(*w) for w in d11]})

d12 = [
    ["camp","扎营","/kæmp/","v.","Go camping.","去野营。"],
    ["lake","湖","/leɪk/","n.","By the lake.","湖边。"],
    ["beach","海滩","/biːtʃ/","n.","On the beach.","在沙滩上。"],
    ["badminton","羽毛球","/ˈbædmɪntən/","n.","Play badminton.","打羽毛球。"],
    ["sheep","羊；绵羊","/ʃiːp/","n.","White sheep.","白羊。"],
    ["as","作为","/æz/","prep.","As a student.","作为学生。"],
    ["natural","自然的","/ˈnætʃrəl/","adj.","Natural beauty.","自然美。"],
    ["butterfly","蝴蝶","/ˈbʌtərflaɪ/","n.","A beautiful butterfly.","美丽的蝴蝶。"],
    ["visitor","游客","/ˈvɪzɪtər/","n.","Many visitors.","许多游客。"],
    ["tired","疲倦的","/ˈtaɪərd/","adj.","I feel tired.","我感到累。"],
    ["stay","停留","/steɪ/","v.","Stay at home.","待在家。"],
    ["away","离开","/əˈweɪ/","adv.","Run away.","跑开。"],
    ["mouse","老鼠","/maʊs/","n.","A little mouse.","小老鼠。"],
    ["baby","婴儿；幼小的","/ˈbeɪbi/","n. & adj.","A baby panda.","小熊猫。"],
    ["shout","呼喊","/ʃaʊt/","v.","Don't shout.","别喊。"],
    ["woof","汪汪（狗叫声）","/wʊf/","interj.","Woof woof!","汪汪！"],
    ["language","语言","/ˈlæŋɡwɪdʒ/","n.","Foreign language.","外语。"],
    ["fly","飞","/flaɪ/","v.","Birds can fly.","鸟会飞。"],
    ["kite","风筝","/kaɪt/","n.","Fly a kite.","放风筝。"],
    ["high","高的（地）","/haɪ/","adj. & adv.","High school.","高中。"],
    ["ago","以前","/əˈɡoʊ/","adv.","Two years ago.","两年前。"],
    ["India","印度","/ˈɪndiə/","n.","In India.","在印度。"],
    ["tent","帐篷","/tent/","n.","Put up a tent.","搭帐篷。"],
    ["moon","月亮","/muːn/","n.","Full moon.","满月。"],
    ["surprise","惊奇；使吃惊","/sərˈpraɪz/","n. & v.","What a surprise!","真意外！"],
    ["snake","蛇","/sneɪk/","n.","A snake.","一条蛇。"],
    ["scared","惊慌的","/skerd/","adj.","I'm scared.","我好怕。"],
    ["move","移动","/muːv/","v.","Don't move.","别动。"],
    ["start","开始","/stɑːrt/","v.","Let's start.","我们开始吧。"],
    ["jump","跳","/dʒʌmp/","v.","Jump high.","跳得高。"],
    ["wake","弄醒","/weɪk/","v.","Wake up.","醒来。"],
    ["into","到……里面","/ˈɪntuː/","prep.","Go into the room.","进入房间。"],
    ["forest","森林","/ˈfɒrɪst/","n.","In the forest.","在森林里。"],
    ["ear","耳朵","/ɪr/","n.","My ears.","我的耳朵。"],
]
GRADE7["units"].append({"unit":21,"title":"下册 Unit 12 What did you do last weekend?","words":[W(*w) for w in d12]})

# ================== SAVE ==================
total = sum(len(u["words"]) for u in GRADE7["units"])
print(f"Units: {len(GRADE7['units'])}")
print(f"Total words: {total}")

with open(OUT, 'w', encoding='utf-8') as f:
    json.dump(GRADE7, f, ensure_ascii=False, indent=2)
print(f"Saved to: {OUT}")

# Verify
with open(OUT, 'r', encoding='utf-8') as f:
    json.load(f)
print("JSON valid!")
