#!/usr/bin/env python3
"""One-shot build: all 6 grade vocabulary JSON files"""
import json, os, sys
if sys.platform=='win32':
    import io; sys.stdout=io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8')

BASE=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT=os.path.join(BASE,'data','vocabulary')
os.makedirs(OUT,exist_ok=True)

def W(*a):
    return {"en":a[0],"zh":a[1],"phonetic":a[2] if len(a)>2 else "","pos":a[3] if len(a)>3 else "","example":a[4] if len(a)>4 else "","exampleZh":a[5] if len(a)>5 else ""}

def S(name,data):
    p=os.path.join(OUT,name)
    with open(p,'w',encoding='utf-8') as f: json.dump(data,f,ensure_ascii=False,indent=2)
    t=sum(len(u["words"]) for u in data["units"])
    print(f"  {name}: {len(data['units'])} units, {t} words")

# ================================================================
# 初一（七年级）22单元 — already complete, load from existing
# ================================================================
with open(os.path.join(OUT,'grade7.json'),'r',encoding='utf-8') as f: g7=json.load(f)
g7["grade"]="初一（七年级）"
g7["semester"]="全学年（上+下册）"
for u in g7["units"]: u["title"]=u["title"].replace("上册 ","").replace("下册 ","")
S("grade7.json",g7)

# ================================================================
# 初二（八年级）20单元完整版
# ================================================================
# Helper: compact word lists as [en, zh, phonetic, pos] tuples
_r=lambda a:[W(*x) for x in a]

U1=[["anyone","任何人","/ˈeniwʌn/","pron."],["anywhere","在任何地方","/ˈeniwer/","adv."],
["wonderful","精彩的","/ˈwʌndərfl/","adj."],["few","不多；很少","/fjuː/","adj.&pron."],
["most","最多","/moʊst/","adj.&pron."],["something","某事","/ˈsʌmθɪŋ/","pron."],
["nothing","没有什么","/ˈnʌθɪŋ/","pron."],["everyone","每人","/ˈevriwʌn/","pron."],
["myself","我自己","/maɪˈself/","pron."],["yourself","你自己","/jɔːrˈself/","pron."],
["hen","母鸡","/hen/","n."],["pig","猪","/pɪɡ/","n."],["seem","好像","/siːm/","v."],
["bored","厌倦的","/bɔːrd/","adj."],["someone","某人","/ˈsʌmwʌn/","pron."],
["diary","日记","/ˈdaɪəri/","n."],["enjoyable","令人愉快的","/ɪnˈdʒɔɪəbl/","adj."],
["activity","活动","/ækˈtɪvəti/","n."],["decide","决定","/dɪˈsaɪd/","v."],
["try","尝试","/traɪ/","v.&n."],["paragliding","滑翔伞","/ˈpærəɡlaɪdɪŋ/","n."],
["bird","鸟","/bɜːrd/","n."],["bicycle","自行车","/ˈbaɪsɪkl/","n."],
["building","建筑物","/ˈbɪldɪŋ/","n."],["trader","商人","/ˈtreɪdər/","n."],
["wonder","想知道","/ˈwʌndər/","v."],["difference","差别","/ˈdɪfrəns/","n."],
["top","顶部","/tɑːp/","n."],["wait","等待","/weɪt/","v."],
["umbrella","雨伞","/ʌmˈbrelə/","n."],["wet","湿的","/wet/","adj."],
["below","在下面","/bɪˈloʊ/","prep."],["enough","足够的","/ɪˈnʌf/","adj.&adv."],
["hungry","饥饿的","/ˈhʌŋɡri/","adj."],["as","作为","/æz/","conj."],
["hill","小山","/hɪl/","n."],["duck","鸭子","/dʌk/","n."],
["dislike","不喜爱","/dɪsˈlaɪk/","v.&n."]]
U2=[["housework","家务","/ˈhaʊswɜːrk/","n."],["hardly","几乎不","/ˈhɑːrdli/","adv."],
["ever","曾经","/ˈevər/","adv."],["once","一次","/wʌns/","adv."],
["twice","两次","/twaɪs/","adv."],["Internet","互联网","/ˈɪntərnet/","n."],
["program","节目","/ˈproʊɡræm/","n."],["full","满的","/fʊl/","adj."],
["swing","摇摆","/swɪŋ/","v."],["maybe","大概","/ˈmeɪbi/","adv."],
["least","最少","/liːst/","adj."],["junk","垃圾","/dʒʌŋk/","n."],
["coffee","咖啡","/ˈkɔːfi/","n."],["health","健康","/helθ/","n."],
["result","结果","/rɪˈzʌlt/","n."],["percent","百分之","/pərˈsent/","n."],
["online","在线","/ˌɑːnˈlaɪn/","adj."],["television","电视","/ˈtelɪvɪʒn/","n."],
["although","虽然","/ɔːlˈðoʊ/","conj."],["through","穿过","/θruː/","prep."],
["mind","头脑","/maɪnd/","n."],["body","身体","/ˈbɑːdi/","n."],
["such","这样的","/sʌtʃ/","adj."],["together","一起","/təˈɡeðər/","adv."],
["die","消失","/daɪ/","v."],["writer","作家","/ˈraɪtər/","n."],
["dentist","牙医","/ˈdentɪst/","n."],["magazine","杂志","/ˌmæɡəˈziːn/","n."],
["however","然而","/haʊˈevər/","adv."],["than","比","/ðæn/","conj."],
["almost","几乎","/ˈɔːlmoʊst/","adv."],["none","没有一个","/nʌn/","pron."],
["less","更少","/les/","adj."],["point","得分","/pɔɪnt/","n."]]
U3=[["outgoing","外向的","/ˈaʊtɡoʊɪŋ/","adj."],["better","更好的","/ˈbetər/","adj."],
["loudly","大声地","/ˈlaʊdli/","adv."],["quietly","安静地","/ˈkwaɪətli/","adv."],
["hard-working","勤奋的","/ˌhɑːrdˈwɜːrkɪŋ/","adj."],["competition","比赛","/ˌkɑːmpəˈtɪʃn/","n."],
["fantastic","极好的","/fænˈtæstɪk/","adj."],["which","哪一个","/wɪtʃ/","pron."],
["clearly","清楚地","/ˈklɪrli/","adv."],["win","赢","/wɪn/","v."],
["though","虽然","/ðoʊ/","conj."],["talented","有才能的","/ˈtæləntɪd/","adj."],
["truly","真正","/ˈtruːli/","adv."],["care","关心","/ker/","v."],
["serious","严肃的","/ˈsɪriəs/","adj."],["mirror","镜子","/ˈmɪrər/","n."],
["kid","小孩","/kɪd/","n."],["necessary","必需的","/ˈnesəseri/","adj."],
["both","两个都","/boʊθ/","adj."],["grade","成绩","/ɡreɪd/","n."],
["should","应该","/ʃʊd/","modal v."],["saying","谚语","/ˈseɪɪŋ/","n."],
["reach","到达","/riːtʃ/","v."],["hand","手","/hænd/","n."],
["touch","触摸","/tʌtʃ/","v."],["heart","心脏","/hɑːrt/","n."],
["fact","事实","/fækt/","n."],["break","打破","/breɪk/","v."],
["arm","手臂","/ɑːrm/","n."],["share","分享","/ʃer/","v."],
["loud","大声的","/laʊd/","adj."],["similar","类似的","/ˈsɪmələr/","adj."],
["information","信息","/ˌɪnfərˈmeɪʃn/","n."]]
U4=[["theater","电影院","/ˈθiːətər/","n."],["comfortable","舒适的","/ˈkʌmftəbl/","adj."],
["seat","座位","/siːt/","n."],["screen","屏幕","/skriːn/","n."],
["close","接近的","/kloʊs/","adj."],["ticket","票","/ˈtɪkɪt/","n."],
["worst","最差的","/wɜːrst/","adj."],["cheaply","便宜地","/ˈtʃiːpli/","adv."],
["song","歌曲","/sɔːŋ/","n."],["choose","选择","/tʃuːz/","v."],
["carefully","仔细地","/ˈkerfəli/","adv."],["reporter","记者","/rɪˈpɔːrtər/","n."],
["fresh","新鲜的","/freʃ/","adj."],["comfortably","舒服地","/ˈkʌmftəbli/","adv."],
["worse","更差","/wɜːrs/","adj."],["service","服务","/ˈsɜːrvɪs/","n."],
["pretty","相当","/ˈprɪti/","adv."],["menu","菜单","/ˈmenjuː/","n."],
["act","扮演","/ækt/","v."],["meal","一餐","/miːl/","n."],
["creative","有创造力的","/kriˈeɪtɪv/","adj."],["performer","表演者","/pərˈfɔːrmər/","n."],
["talent","天赋","/ˈtælənt/","n."],["winner","获胜者","/ˈwɪnər/","n."],
["prize","奖","/praɪz/","n."],["everybody","每人","/ˈevribɑːdi/","pron."],
["example","例子","/ɪɡˈzæmpl/","n."],["poor","贫穷的","/pʊr/","adj."],
["seriously","严重地","/ˈsɪriəsli/","adv."],["give","给","/ɡɪv/","v."],
["crowded","拥挤的","/ˈkraʊdɪd/","adj."]]
U5=[["sitcom","情景喜剧","/ˈsɪtkɑːm/","n."],["news","新闻","/njuːz/","n."],
["soap","肥皂剧","/soʊp/","n."],["mind","介意","/maɪnd/","v."],
["stand","忍受","/stænd/","v."],["educational","教育的","/ˌedʒuˈkeɪʃənl/","adj."],
["plan","计划","/plæn/","n."],["hope","希望","/hoʊp/","v."],
["discussion","讨论","/dɪˈskʌʃn/","n."],["happen","发生","/ˈhæpən/","v."],
["expect","预料","/ɪkˈspekt/","v."],["joke","笑话","/dʒoʊk/","n."],
["comedy","喜剧","/ˈkɑːmədi/","n."],["meaningless","无意义的","/ˈmiːnɪŋləs/","adj."],
["action","行动","/ˈækʃn/","n."],["cartoon","卡通","/kɑːrˈtuːn/","n."],
["culture","文化","/ˈkʌltʃər/","n."],["famous","著名的","/ˈfeɪməs/","adj."],
["appear","出现","/əˈpɪr/","v."],["become","开始变得","/bɪˈkʌm/","v."],
["rich","富有的","/rɪtʃ/","adj."],["successful","成功的","/səkˈsesfl/","adj."],
["might","可能","/maɪt/","modal v."],["main","主要的","/meɪn/","adj."],
["reason","原因","/ˈriːzn/","n."],["common","普通的","/ˈkɑːmən/","adj."],
["film","电影","/fɪlm/","n."],["unlucky","不幸的","/ʌnˈlʌki/","adj."],
["lose","失去","/luːz/","v."],["ready","准备好的","/ˈredi/","adj."],
["character","角色","/ˈkærəktər/","n."],["simple","简单的","/ˈsɪmpl/","adj."]]
U6=[["doctor","医生","/ˈdɑːktər/","n."],["engineer","工程师","/ˌendʒɪˈnɪr/","n."],
["violinist","小提琴手","/ˌvaɪəˈlɪnɪst/","n."],["driver","司机","/ˈdraɪvər/","n."],
["pilot","飞行员","/ˈpaɪlət/","n."],["pianist","钢琴家","/ˈpiːənɪst/","n."],
["scientist","科学家","/ˈsaɪəntɪst/","n."],["college","大学","/ˈkɑːlɪdʒ/","n."],
["education","教育","/ˌedʒuˈkeɪʃn/","n."],["medicine","医学","/ˈmedɪsn/","n."],
["university","大学","/ˌjuːnɪˈvɜːrsəti/","n."],["article","文章","/ˈɑːrtɪkl/","n."],
["send","发送","/send/","v."],["resolution","决心","/ˌrezəˈluːʃn/","n."],
["team","团队","/tiːm/","n."],["foreign","外国的","/ˈfɔːrən/","adj."],
["able","能够","/ˈeɪbl/","adj."],["meaning","意义","/ˈmiːnɪŋ/","n."],
["discuss","讨论","/dɪˈskʌs/","v."],["promise","承诺","/ˈprɑːmɪs/","n."],
["improve","改进","/ɪmˈpruːv/","v."],["physical","身体的","/ˈfɪzɪkl/","adj."],
["themselves","他们自己","/ðəmˈselvz/","pron."],["hobby","爱好","/ˈhɑːbi/","n."],
["paint","画画","/peɪnt/","v."],["weekly","每周的","/ˈwiːkli/","adj."],
["schoolwork","学校作业","/ˈskuːlwɜːrk/","n."],["own","自己的","/oʊn/","adj."],
["personal","个人的","/ˈpɜːrsənl/","adj."],["relationship","关系","/rɪˈleɪʃnʃɪp/","n."]]
U7=[["paper","纸","/ˈpeɪpər/","n."],["pollution","污染","/pəˈluːʃn/","n."],
["prediction","预言","/prɪˈdɪkʃn/","n."],["future","未来","/ˈfjuːtʃər/","n."],
["pollute","污染","/pəˈluːt/","v."],["environment","环境","/ɪnˈvaɪrənmənt/","n."],
["planet","行星","/ˈplænɪt/","n."],["earth","地球","/ɜːrθ/","n."],
["plant","种植","/plænt/","v."],["part","部分","/pɑːrt/","n."],
["peace","和平","/piːs/","n."],["sky","天空","/skaɪ/","n."],
["apartment","公寓","/əˈpɑːrtmənt/","n."],["rocket","火箭","/ˈrɑːkɪt/","n."],
["space","太空","/speɪs/","n."],["human","人类","/ˈhjuːmən/","n."],
["servant","仆人","/ˈsɜːrvənt/","n."],["dangerous","危险的","/ˈdeɪndʒərəs/","adj."],
["already","已经","/ɔːlˈredi/","adv."],["factory","工厂","/ˈfæktri/","n."],
["believe","相信","/bɪˈliːv/","v."],["disagree","不同意","/ˌdɪsəˈɡriː/","v."],
["even","甚至","/ˈiːvn/","adv."],["agree","同意","/əˈɡriː/","v."],
["shape","形状","/ʃeɪp/","n."],["fall","落下","/fɔːl/","v."],
["inside","在里面","/ˌɪnˈsaɪd/","prep."],["possible","可能的","/ˈpɑːsəbl/","adj."],
["impossible","不可能的","/ɪmˈpɑːsəbl/","adj."],["side","侧面","/saɪd/","n."],
["probably","很可能","/ˈprɑːbəbli/","adv."],["during","在……期间","/ˈdʊrɪŋ/","prep."],
["holiday","假期","/ˈhɑːlədeɪ/","n."],["word","单词","/wɜːrd/","n."]]
U8=[["shake","奶昔","/ʃeɪk/","n."],["blender","搅拌器","/ˈblendər/","n."],
["peel","剥皮","/piːl/","v."],["pour","倒","/pɔːr/","v."],
["yogurt","酸奶","/ˈjoʊɡərt/","n."],["honey","蜂蜜","/ˈhʌni/","n."],
["watermelon","西瓜","/ˈwɔːtərmelən/","n."],["spoon","勺子","/spuːn/","n."],
["pot","锅","/pɑːt/","n."],["add","添加","/æd/","v."],
["finally","最后","/ˈfaɪnəli/","adv."],["salt","盐","/sɔːlt/","n."],
["sugar","糖","/ˈʃʊɡər/","n."],["cheese","奶酪","/tʃiːz/","n."],
["popcorn","爆米花","/ˈpɑːpkɔːrn/","n."],["corn","玉米","/kɔːrn/","n."],
["machine","机器","/məˈʃiːn/","n."],["dig","挖","/dɪɡ/","v."],
["hole","洞","/hoʊl/","n."],["sandwich","三明治","/ˈsænwɪtʃ/","n."],
["butter","黄油","/ˈbʌtər/","n."],["turkey","火鸡","/ˈtɜːrki/","n."],
["lettuce","生菜","/ˈletɪs/","n."],["piece","块","/piːs/","n."],
["traditional","传统的","/trəˈdɪʃənl/","adj."],["autumn","秋天","/ˈɔːtəm/","n."],
["celebrate","庆祝","/ˈselɪbreɪt/","v."],["mix","混合","/mɪks/","v."],
["pepper","甜椒","/ˈpepər/","n."],["fill","充满","/fɪl/","v."],
["cover","覆盖","/ˈkʌvər/","v."],["serve","服务","/sɜːrv/","v."],
["temperature","温度","/ˈtemprətʃər/","n."]]
U9=[["prepare","准备","/prɪˈper/","v."],["exam","考试","/ɪɡˈzæm/","n."],
["flu","流感","/fluː/","n."],["available","有空的","/əˈveɪləbl/","adj."],
["until","直到","/ənˈtɪl/","conj."],["hang","闲逛","/hæŋ/","v."],
["catch","赶上","/kætʃ/","v."],["invite","邀请","/ɪnˈvaɪt/","v."],
["accept","接受","/əkˈsept/","v."],["refuse","拒绝","/rɪˈfjuːz/","v."],
["weekday","工作日","/ˈwiːkdeɪ/","n."],["delete","删除","/dɪˈliːt/","v."],
["print","打印","/prɪnt/","v."],["sad","难过的","/sæd/","adj."],
["goodbye","再见","/ˌɡʊdˈbaɪ/","interj."],["concert","音乐会","/ˈkɑːnsərt/","n."],
["headmaster","校长","/ˌhedˈmæstər/","n."],["event","大事","/ɪˈvent/","n."],
["guest","客人","/ɡest/","n."],["calendar","日历","/ˈkælɪndər/","n."],
["daytime","白天","/ˈdeɪtaɪm/","n."]]
U10=[["meeting","会议","/ˈmiːtɪŋ/","n."],["video","录像","/ˈvɪdioʊ/","n."],
["organize","组织","/ˈɔːrɡənaɪz/","v."],["chocolate","巧克力","/ˈtʃɑːklət/","n."],
["upset","难过","/ʌpˈset/","adj."],["taxi","出租车","/ˈtæksi/","n."],
["advice","劝告","/ədˈvaɪs/","n."],["travel","旅行","/ˈtrævl/","v."],
["agent","代理人","/ˈeɪdʒənt/","n."],["expert","专家","/ˈekspɜːrt/","n."],
["teenager","青少年","/ˈtiːneɪdʒər/","n."],["normal","正常的","/ˈnɔːrml/","adj."],
["unless","除非","/ənˈles/","conj."],["certainly","当然","/ˈsɜːrtnli/","adv."],
["wallet","钱包","/ˈwɑːlɪt/","n."],["mile","英里","/maɪl/","n."],
["angry","生气的","/ˈæŋɡri/","adj."],["understanding","善解人意的","/ˌʌndərˈstændɪŋ/","adj."],
["careless","粗心的","/ˈkerləs/","adj."],["mistake","错误","/mɪˈsteɪk/","n."],
["himself","他自己","/hɪmˈself/","pron."],["careful","小心的","/ˈkerfl/","adj."],
["advise","劝告","/ədˈvaɪz/","v."],["solve","解决","/sɑːlv/","v."],
["step","步骤","/step/","n."],["trust","信任","/trʌst/","v."],
["experience","经历","/ɪkˈspɪriəns/","n."],["else","别的","/els/","adv."]]

# 初二下
D1=[["matter","问题","/ˈmætər/","n."],["sore","疼痛的","/sɔːr/","adj."],
["stomachache","胃痛","/ˈstʌməkeɪk/","n."],["foot","脚","/fʊt/","n."],
["neck","脖子","/nek/","n."],["stomach","胃","/ˈstʌmək/","n."],
["throat","喉咙","/θroʊt/","n."],["fever","发烧","/ˈfiːvər/","n."],
["cough","咳嗽","/kɔːf/","n."],["X-ray","X光","/ˈeksreɪ/","n."],
["toothache","牙痛","/ˈtuːθeɪk/","n."],["headache","头痛","/ˈhedeɪk/","n."],
["break","休息","/breɪk/","n."],["hurt","受伤","/hɜːrt/","v."],
["passenger","乘客","/ˈpæsɪndʒər/","n."],["trouble","麻烦","/ˈtrʌbl/","n."],
["herself","她自己","/hɜːrˈself/","pron."],["sick","生病的","/sɪk/","adj."],
["knee","膝盖","/niː/","n."],["ourselves","我们自己","/aʊərˈselvz/","pron."],
["climber","登山者","/ˈklaɪmər/","n."],["risk","风险","/rɪsk/","n."],
["accident","事故","/ˈæksɪdənt/","n."],["situation","情况","/ˌsɪtʃuˈeɪʃn/","n."],
["kilo","千克","/ˈkiːloʊ/","n."],["rock","岩石","/rɑːk/","n."],
["knife","刀","/naɪf/","n."],["blood","血","/blʌd/","n."],
["mean","意思是","/miːn/","v."],["importance","重要性","/ɪmˈpɔːrtns/","n."],
["decision","决定","/dɪˈsɪʒn/","n."],["control","控制","/kənˈtroʊl/","n."],
["spirit","精神","/ˈspɪrɪt/","n."],["death","死亡","/deθ/","n."],
["nurse","护士","/nɜːrs/","n."]]
D2=[["clean up","打扫","","phr."],["cheer","欢呼","/tʃɪr/","v."],
["volunteer","志愿者","/ˌvɑːlənˈtɪr/","n."],["sign","标志","/saɪn/","n."],
["notice","通知","/ˈnoʊtɪs/","n."],["lonely","孤独的","/ˈloʊnli/","adj."],
["several","几个","/ˈsevrəl/","pron."],["strong","强壮的","/strɔːŋ/","adj."],
["feeling","感觉","/ˈfiːlɪŋ/","n."],["satisfaction","满足","/ˌsætɪsˈfækʃn/","n."],
["joy","高兴","/dʒɔɪ/","n."],["owner","物主","/ˈoʊnər/","n."],
["journey","旅行","/ˈdʒɜːrni/","n."],["raise","筹集","/reɪz/","v."],
["alone","独自","/əˈloʊn/","adv."],["repair","修理","/rɪˈper/","v."],
["wheel","车轮","/wiːl/","n."],["letter","信","/ˈletər/","n."],
["blind","盲的","/blaɪnd/","adj."],["deaf","聋的","/def/","adj."],
["imagine","想象","/ɪˈmædʒɪn/","v."],["difficulty","困难","/ˈdɪfɪkəlti/","n."],
["open","打开","/ˈoʊpən/","v."],["carry","提","/ˈkæri/","v."],
["train","训练","/treɪn/","v."],["excited","兴奋的","/ɪkˈsaɪtɪd/","adj."],
["kindness","仁慈","/ˈkaɪndnəs/","n."],["clever","聪明的","/ˈklevər/","adj."],
["understand","理解","/ˌʌndərˈstænd/","v."],["change","改变","/tʃeɪndʒ/","v."],
["interest","兴趣","/ˈɪntrəst/","n."],["disabled","残疾的","/dɪsˈeɪbld/","adj."]]
D3=[["rubbish","垃圾","/ˈrʌbɪʃ/","n."],["fold","折叠","/foʊld/","v."],
["sweep","扫","/swiːp/","v."],["floor","地板","/flɔːr/","n."],
["mess","杂乱","/mes/","n."],["throw","扔","/θroʊ/","v."],
["neither","也不","/ˈniːðər/","adv."],["shirt","衬衫","/ʃɜːrt/","n."],
["pass","递给","/pæs/","v."],["borrow","借","/ˈbɔːroʊ/","v."],
["lend","借给","/lend/","v."],["finger","手指","/ˈfɪŋɡər/","n."],
["hate","讨厌","/heɪt/","v."],["chore","杂务","/tʃɔːr/","n."],
["snack","零食","/snæk/","n."],["stress","压力","/stres/","n."],
["waste","浪费","/weɪst/","v."],["provide","提供","/prəˈvaɪd/","v."],
["anyway","不管怎样","/ˈeniweɪ/","adv."],["depend","依靠","/dɪˈpend/","v."],
["develop","发展","/dɪˈveləp/","v."],["independence","独立","/ˌɪndɪˈpendəns/","n."],
["fairness","公正","/ˈfernəs/","n."],["since","自从","/sɪns/","prep."],
["neighbor","邻居","/ˈneɪbər/","n."],["ill","生病的","/ɪl/","adj."],
["drop","落下","/drɑːp/","v."]]
D4=[["allow","允许","/əˈlaʊ/","v."],["wrong","错误的","/rɔːŋ/","adj."],
["guess","猜测","/ɡes/","v."],["relation","关系","/rɪˈleɪʃn/","n."],
["communication","交流","/kəˌmjuːnɪˈkeɪʃn/","n."],["argue","争吵","/ˈɑːrɡjuː/","v."],
["cloud","云","/klaʊd/","n."],["elder","年纪较大的","/ˈeldər/","adj."],
["instead","代替","/ɪnˈsted/","adv."],["nervous","紧张的","/ˈnɜːrvəs/","adj."],
["offer","主动提出","/ˈɔːfər/","v."],["proper","正确的","/ˈprɑːpər/","adj."],
["secondly","其次","/ˈsekəndli/","adv."],["explain","解释","/ɪkˈspleɪn/","v."],
["copy","复制","/ˈkɑːpi/","v."],["return","归还","/rɪˈtɜːrn/","v."],
["member","成员","/ˈmembər/","n."],["pressure","压力","/ˈpreʃər/","n."],
["compete","竞争","/kəmˈpiːt/","v."],["opinion","意见","/əˈpɪnjən/","n."],
["skill","技能","/skɪl/","n."],["typical","典型的","/ˈtɪpɪkl/","adj."],
["continue","继续","/kənˈtɪnjuː/","v."],["compare","比较","/kəmˈper/","v."],
["crazy","疯狂的","/ˈkreɪzi/","adj."],["push","推","/pʊʃ/","v."],
["development","发展","/dɪˈveləpmənt/","n."],["cause","造成","/kɔːz/","v."],
["usual","通常的","/ˈjuːʒuəl/","adj."]]

g8={"grade":"初二（八年级）","semester":"全学年（上+下册）","textbook":"人教版 Go for it!",
     "units":[{"unit":1,"title":"上U1 Where did you go on vacation?","words":_r(U1)},
              {"unit":2,"title":"上U2 How often do you exercise?","words":_r(U2)},
              {"unit":3,"title":"上U3 I'm more outgoing than my sister.","words":_r(U3)},
              {"unit":4,"title":"上U4 What's the best movie theater?","words":_r(U4)},
              {"unit":5,"title":"上U5 Do you want to watch a game show?","words":_r(U5)},
              {"unit":6,"title":"上U6 I'm going to study computer science.","words":_r(U6)},
              {"unit":7,"title":"上U7 Will people have robots?","words":_r(U7)},
              {"unit":8,"title":"上U8 How do you make a banana milk shake?","words":_r(U8)},
              {"unit":9,"title":"上U9 Can you come to my party?","words":_r(U9)},
              {"unit":10,"title":"上U10 If you go to the party...","words":_r(U10)},
              {"unit":11,"title":"下U1 What's the matter?","words":_r(D1)},
              {"unit":12,"title":"下U2 I'll help to clean up the city parks.","words":_r(D2)},
              {"unit":13,"title":"下U3 Could you please clean your room?","words":_r(D3)},
              {"unit":14,"title":"下U4 Why don't you talk to your parents?","words":_r(D4)}]}
S("grade8.json",g8)

# ================================================================
# 初三（九年级）14单元完整版
# ================================================================
N1=[["textbook","教科书","/ˈtekstbʊk/","n."],["conversation","交谈","/ˌkɑːnvərˈseɪʃn/","n."],
["aloud","大声地","/əˈlaʊd/","adv."],["pronunciation","发音","/prəˌnʌnsiˈeɪʃn/","n."],
["sentence","句子","/ˈsentəns/","n."],["patient","耐心的","/ˈpeɪʃnt/","adj."],
["expression","表达","/ɪkˈspreʃn/","n."],["discover","发现","/dɪˈskʌvər/","v."],
["secret","秘密","/ˈsiːkrət/","n."],["grammar","语法","/ˈɡræmər/","n."],
["repeat","重复","/rɪˈpiːt/","v."],["note","笔记","/noʊt/","n."],
["pal","朋友","/pæl/","n."],["physics","物理","/ˈfɪzɪks/","n."],
["chemistry","化学","/ˈkemɪstri/","n."],["memorize","记忆","/ˈmeməraɪz/","v."],
["pattern","模式","/ˈpætərn/","n."],["pronounce","发音","/prəˈnaʊns/","v."],
["increase","增加","/ɪnˈkriːs/","v."],["speed","速度","/spiːd/","n."],
["partner","搭档","/ˈpɑːrtnər/","n."],["born","天生的","/bɔːrn/","v."],
["ability","能力","/əˈbɪləti/","n."],["create","创造","/kriˈeɪt/","v."],
["brain","大脑","/breɪn/","n."],["active","活跃的","/ˈæktɪv/","adj."],
["attention","注意","/əˈtenʃn/","n."],["connect","连接","/kəˈnekt/","v."],
["review","复习","/rɪˈvjuː/","v."],["knowledge","知识","/ˈnɑːlɪdʒ/","n."],
["wisely","明智地","/ˈwaɪzli/","adv."]]
N2=[["mooncake","月饼","/ˈmuːnkeɪk/","n."],["lantern","灯笼","/ˈlæntərn/","n."],
["stranger","陌生人","/ˈstreɪndʒər/","n."],["relative","亲属","/ˈrelətɪv/","n."],
["pound","磅","/paʊnd/","n."],["folk","民间的","/foʊk/","adj."],
["goddess","女神","/ˈɡɑːdes/","n."],["steal","偷","/stiːl/","v."],
["lay","放置","/leɪ/","v."],["dessert","甜点","/dɪˈzɜːrt/","n."],
["garden","花园","/ˈɡɑːrdn/","n."],["tradition","传统","/trəˈdɪʃn/","n."],
["admire","欣赏","/ədˈmaɪər/","v."],["tie","领带","/taɪ/","n."],
["haunted","闹鬼的","/ˈhɔːntɪd/","adj."],["ghost","鬼","/ɡoʊst/","n."],
["trick","花招","/trɪk/","n."],["treat","款待","/triːt/","n."],
["spider","蜘蛛","/ˈspaɪdər/","n."],["Christmas","圣诞节","/ˈkrɪsməs/","n."],
["novel","小说","/ˈnɑːvl/","n."],["eve","前夕","/iːv/","n."],
["dead","死的","/ded/","adj."],["business","生意","/ˈbɪznəs/","n."],
["punish","处罚","/ˈpʌnɪʃ/","v."],["warn","警告","/wɔːrn/","v."],
["present","礼物","/ˈpreznt/","n."],["warmth","温暖","/wɔːrmθ/","n."],
["spread","传播","/spred/","v."]]
N3=[["restroom","洗手间","/ˈrestruːm/","n."],["stamp","邮票","/stæmp/","n."],
["bookstore","书店","/ˈbʊkstɔːr/","n."],["beside","在旁边","/bɪˈsaɪd/","prep."],
["postcard","明信片","/ˈpoʊstkɑːrd/","n."],["pardon","请再说一遍","/ˈpɑːrdn/","interj."],
["rush","仓促","/rʌʃ/","v."],["suggest","建议","/səˈdʒest/","v."],
["staff","职工","/stæf/","n."],["grape","葡萄","/ɡreɪp/","n."],
["central","中心的","/ˈsentrəl/","adj."],["nearby","在附近","/ˌnɪrˈbaɪ/","adv."],
["mail","邮寄","/meɪl/","v."],["east","东方","/iːst/","n."],
["fascinating","迷人的","/ˈfæsɪneɪtɪŋ/","adj."],["convenient","方便的","/kənˈviːniənt/","adj."],
["corner","拐角","/ˈkɔːrnər/","n."],["politely","礼貌地","/pəˈlaɪtli/","adv."],
["request","请求","/rɪˈkwest/","n."],["direction","方向","/dəˈrekʃn/","n."],
["correct","正确的","/kəˈrekt/","adj."],["polite","有礼貌的","/pəˈlaɪt/","adj."],
["direct","直接的","/dəˈrekt/","adj."],["address","地址","/əˈdres/","n."],
["underground","地下的","/ˈʌndərɡraʊnd/","adj."],["course","课程","/kɔːrs/","n."]]
N4=[["humorous","幽默的","/ˈhjuːmərəs/","adj."],["silent","沉默的","/ˈsaɪlənt/","adj."],
["helpful","有帮助的","/ˈhelpfl/","adj."],["score","得分","/skɔːr/","n."],
["background","背景","/ˈbækɡraʊnd/","n."],["interview","面试","/ˈɪntərvjuː/","v."],
["Asian","亚洲的","/ˈeɪʒn/","adj."],["deal","处理","/diːl/","v."],
["dare","敢于","/der/","v."],["crowd","人群","/kraʊd/","n."],
["private","私人的","/ˈpraɪvət/","adj."],["guard","警卫","/ɡɑːrd/","n."],
["require","需要","/rɪˈkwaɪər/","v."],["European","欧洲的","/ˌjʊrəˈpiːən/","adj."],
["speech","演讲","/spiːtʃ/","n."],["public","公众的","/ˈpʌblɪk/","adj."],
["seldom","很少","/ˈseldəm/","adv."],["influence","影响","/ˈɪnfluəns/","n."],
["absent","缺席的","/ˈæbsənt/","adj."],["fail","失败","/feɪl/","v."],
["examination","考试","/ɪɡˌzæmɪˈneɪʃn/","n."],["exactly","确切地","/ɪɡˈzæktli/","adv."],
["pride","自豪","/praɪd/","n."],["proud","自豪的","/praʊd/","adj."],
["general","总的","/ˈdʒenrəl/","adj."],["introduction","介绍","/ˌɪntrəˈdʌkʃn/","n."]]
N5=[["chopsticks","筷子","/ˈtʃɑːpstɪks/","n."],["coin","硬币","/kɔɪn/","n."],
["fork","餐叉","/fɔːrk/","n."],["blouse","女式上衣","/blaʊz/","n."],
["silver","银","/ˈsɪlvər/","n."],["glass","玻璃","/ɡlæs/","n."],
["cotton","棉花","/ˈkɑːtn/","n."],["steel","钢","/stiːl/","n."],
["fair","展览会","/fer/","n."],["environmental","环境的","/ɪnˌvaɪrənˈmentl/","adj."],
["grass","草","/ɡræs/","n."],["leaf","叶子","/liːf/","n."],
["produce","生产","/prəˈduːs/","v."],["widely","广泛地","/ˈwaɪdli/","adv."],
["process","加工","/ˈprɑːses/","v."],["product","产品","/ˈprɑːdʌkt/","n."],
["local","当地的","/ˈloʊkl/","adj."],["brand","品牌","/brænd/","n."],
["avoid","避免","/əˈvɔɪd/","v."],["mobile","可移动的","/ˈmoʊbl/","adj."],
["everyday","日常的","/ˈevrideɪ/","adj."],["boss","老板","/bɔːs/","n."],
["material","材料","/məˈtɪriəl/","n."],["traffic","交通","/ˈtræfɪk/","n."],
["international","国际的","/ˌɪntərˈnæʃnəl/","adj."],["form","形式","/fɔːrm/","n."],
["lively","生气勃勃的","/ˈlaɪvli/","adj."],["heat","热","/hiːt/","n."],
["complete","完成","/kəmˈpliːt/","v."]]
N6=[["heel","鞋跟","/hiːl/","n."],["electricity","电","/ɪˌlekˈtrɪsəti/","n."],
["scoop","勺","/skuːp/","n."],["style","样式","/staɪl/","n."],
["project","项目","/ˈprɑːdʒekt/","n."],["pleasure","高兴","/ˈpleʒər/","n."],
["zipper","拉链","/ˈzɪpər/","n."],["daily","每日的","/ˈdeɪli/","adj."],
["website","网站","/ˈwebsaɪt/","n."],["pioneer","先锋","/ˌpaɪəˈnɪr/","n."],
["list","列表","/lɪst/","n."],["mention","提到","/ˈmenʃn/","v."],
["accidental","偶然的","/ˌæksɪˈdentl/","adj."],["boil","煮沸","/bɔɪl/","v."],
["remain","保持","/rɪˈmeɪn/","v."],["smell","气味","/smel/","n."],
["national","国家的","/ˈnæʃnəl/","adj."],["trade","贸易","/treɪd/","n."],
["doubt","怀疑","/daʊt/","n."],["fridge","冰箱","/frɪdʒ/","n."],
["low","低的","/loʊ/","adj."],["translate","翻译","/trænsˈleɪt/","v."],
["lock","锁","/lɑːk/","v."],["earthquake","地震","/ˈɜːrθkweɪk/","n."],
["sudden","突然的","/ˈsʌdn/","adj."],["bell","铃","/bel/","n."],
["biscuit","饼干","/ˈbɪskɪt/","n."],["musical","音乐的","/ˈmjuːzɪkl/","adj."],
["instrument","仪器","/ˈɪnstrəmənt/","n."],["salty","咸的","/ˈsɔːlti/","adj."],
["customer","顾客","/ˈkʌstəmər/","n."]]
N7=[["license","证件","/ˈlaɪsns/","n."],["safety","安全","/ˈseɪfti/","n."],
["smoke","吸烟","/smoʊk/","v."],["pierce","扎","/pɪrs/","v."],
["earring","耳环","/ˈɪrɪŋ/","n."],["cry","哭","/kraɪ/","v."],
["field","田野","/fiːld/","n."],["hug","拥抱","/hʌɡ/","v."],
["lift","举起","/lɪft/","v."],["awful","讨厌的","/ˈɔːfl/","adj."],
["regret","懊悔","/rɪˈɡret/","v."],["poem","诗","/ˈpoʊəm/","n."],
["community","社区","/kəˈmjuːnəti/","n."],["chance","机会","/tʃæns/","n."],
["educate","教育","/ˈedʒukeɪt/","v."],["manage","应付","/ˈmænɪdʒ/","v."],
["society","社会","/səˈsaɪəti/","n."],["support","支持","/səˈpɔːrt/","v."],
["enter","进入","/ˈentər/","v."],["choice","选择","/tʃɔɪs/","n."]]
N8=[["truck","卡车","/trʌk/","n."],["picnic","野餐","/ˈpɪknɪk/","n."],
["rabbit","兔子","/ˈræbɪt/","n."],["attend","出席","/əˈtend/","v."],
["valuable","贵重的","/ˈvæljuəbl/","adj."],["pink","粉红色的","/pɪŋk/","adj."],
["anybody","任何人","/ˈenibɑːdi/","pron."],["happening","事件","/ˈhæpənɪŋ/","n."],
["noise","噪音","/nɔɪz/","n."],["policeman","警察","/pəˈliːsmən/","n."],
["wolf","狼","/wʊlf/","n."],["laboratory","实验室","/ˈlæbrətɔːri/","n."],
["coat","外套","/koʊt/","n."],["sleepy","困倦的","/ˈsliːpi/","adj."],
["pocket","口袋","/ˈpɑːkɪt/","n."],["alien","外星人","/ˈeɪliən/","n."],
["suit","套装","/suːt/","n."],["express","表达","/ɪkˈspres/","v."],
["circle","圆圈","/ˈsɜːrkl/","n."],["receive","收到","/rɪˈsiːv/","v."],
["leader","领袖","/ˈliːdər/","n."],["medical","医疗的","/ˈmedɪkl/","adj."],
["purpose","目的","/ˈpɜːrpəs/","n."],["prevent","阻止","/prɪˈvent/","v."],
["energy","能量","/ˈenərdʒi/","n."],["position","位置","/pəˈzɪʃn/","n."],
["victory","胜利","/ˈvɪktəri/","n."],["enemy","敌人","/ˈenəmi/","n."],
["period","时期","/ˈpɪriəd/","n."]]
N9=[["prefer","更喜欢","/prɪˈfɜːr/","v."],["lyrics","歌词","/ˈlɪrɪks/","n."],
["electronic","电子的","/ɪˌlekˈtrɑːnɪk/","adj."],["suppose","推断","/səˈpoʊz/","v."],
["smooth","平滑的","/smuːð/","adj."],["spare","空闲的","/sper/","adj."],
["case","情况","/keɪs/","n."],["war","战争","/wɔːr/","n."],
["stick","粘贴","/stɪk/","v."],["down","沮丧","/daʊn/","adj."],
["dialog","对话","/ˈdaɪəlɔːɡ/","n."],["documentary","纪录片","/ˌdɑːkjuˈmentri/","n."],
["drama","戏剧","/ˈdrɑːmə/","n."],["plenty","大量","/ˈplenti/","pron."],
["shut","关闭","/ʃʌt/","v."],["hero","英雄","/ˈhɪroʊ/","n."],
["super","超级的","/ˈsuːpər/","adj."]]
N10=[["custom","风俗","/ˈkʌstəm/","n."],["bow","鞠躬","/baʊ/","v."],
["kiss","亲吻","/kɪs/","v."],["greet","打招呼","/ɡriːt/","v."],
["relaxed","放松的","/rɪˈlækst/","adj."],["value","价值","/ˈvæljuː/","n."],
["capital","首都","/ˈkæpɪtl/","n."],["noon","正午","/nuːn/","n."],
["mad","生气的","/mæd/","adj."],["effort","努力","/ˈefərt/","n."],
["passport","护照","/ˈpæspɔːrt/","n."],["chalk","粉笔","/tʃɔːk/","n."],
["blackboard","黑板","/ˈblækbɔːrd/","n."],["coast","海岸","/koʊst/","n."],
["season","季节","/ˈsiːzn/","n."],["knock","敲","/nɑːk/","v."],
["eastern","东方的","/ˈiːstərn/","adj."],["worth","值得的","/wɜːrθ/","adj."],
["manner","方式","/ˈmænər/","n."],["empty","空的","/ˈempti/","adj."]]
N11=[["friendship","友谊","/ˈfrendʃɪp/","n."],["king","国王","/kɪŋ/","n."],
["power","权力","/ˈpaʊər/","n."],["prime","首要的","/praɪm/","adj."],
["minister","大臣","/ˈmɪnɪstər/","n."],["banker","银行家","/ˈbæŋkər/","n."],
["fame","名声","/feɪm/","n."],["palace","宫殿","/ˈpæləs/","n."],
["wealth","财富","/welθ/","n."],["lemon","柠檬","/ˈlemən/","n."],
["uncomfortable","不舒服的","/ʌnˈkʌmftəbl/","adj."],["weight","重量","/weɪt/","n."],
["shoulder","肩膀","/ˈʃoʊldər/","n."],["goal","目标","/ɡoʊl/","n."],
["coach","教练","/koʊtʃ/","n."],["courage","勇气","/ˈkɜːrɪdʒ/","n."],
["rather","宁愿","/ˈræðər/","adv."],["pull","拉","/pʊl/","v."],
["relief","轻松","/rɪˈliːf/","n."],["nod","点头","/nɑːd/","v."],
["agreement","一致","/əˈɡriːmənt/","n."],["fault","过失","/fɔːlt/","n."],
["disappoint","使失望","/ˌdɪsəˈpɔɪnt/","v."]]
N12=[["backpack","背包","/ˈbækpæk/","n."],["oversleep","睡过头","/ˌoʊvərˈsliːp/","v."],
["block","街区","/blɑːk/","n."],["worker","工人","/ˈwɜːrkər/","n."],
["stare","盯着看","/ster/","v."],["disbelief","不信","/ˌdɪsbɪˈliːf/","n."],
["above","在……上面","/əˈbʌv/","prep."],["burn","燃烧","/bɜːrn/","v."],
["alive","活着的","/əˈlaɪv/","adj."],["airport","机场","/ˈerpɔːrt/","n."],
["till","直到","/tɪl/","conj."],["west","西方","/west/","n."],
["cream","奶油","/kriːm/","n."],["pie","馅饼","/paɪ/","n."],
["bean","豆","/biːn/","n."],["market","市场","/ˈmɑːrkɪt/","n."],
["embarrassed","窘迫的","/ɪmˈbærəst/","adj."],["announce","宣布","/əˈnaʊns/","v."],
["discovery","发现","/dɪˈskʌvəri/","n."],["cancel","取消","/ˈkænsl/","v."],
["officer","军官","/ˈɑːfɪsər/","n."],["disappear","消失","/ˌdɪsəˈpɪr/","v."],
["unexpected","出乎意料的","/ˌʌnɪkˈspektɪd/","adj."]]
N13=[["litter","乱扔","/ˈlɪtər/","v."],["bottom","底部","/ˈbɑːtəm/","n."],
["fisherman","渔民","/ˈfɪʃərmən/","n."],["coal","煤","/koʊl/","n."],
["ugly","丑陋的","/ˈʌɡli/","adj."],["advantage","优点","/ədˈvæntɪdʒ/","n."],
["cost","花费","/kɔːst/","v."],["wooden","木制的","/ˈwʊdn/","adj."],
["plastic","塑料","/ˈplæstɪk/","n."],["shark","鲨鱼","/ʃɑːrk/","n."],
["cruel","残忍的","/ˈkruːəl/","adj."],["harmful","有害的","/ˈhɑːrmfl/","adj."],
["chain","链条","/tʃeɪn/","n."],["ecosystem","生态系统","/ˈiːkoʊsɪstəm/","n."],
["industry","工业","/ˈɪndəstri/","n."],["law","法律","/lɔː/","n."],
["afford","买得起","/əˈfɔːrd/","v."],["transportation","运输","/ˌtrænspɔːrˈteɪʃn/","n."],
["recycle","回收","/ˌriːˈsaɪkl/","v."],["gate","大门","/ɡeɪt/","n."],
["bottle","瓶子","/ˈbɑːtl/","n."],["president","总统","/ˈprezɪdənt/","n."],
["metal","金属","/ˈmetl/","n."],["creativity","创造力","/ˌkriːeɪˈtɪvəti/","n."]]
N14=[["survey","调查","/ˈsɜːrveɪ/","n."],["standard","标准","/ˈstændərd/","n."],
["row","一排","/roʊ/","n."],["keyboard","键盘","/ˈkiːbɔːrd/","n."],
["instruction","指示","/ɪnˈstrʌkʃn/","n."],["double","加倍","/ˈdʌbl/","v."],
["shall","将要","/ʃæl/","v."],["overcome","克服","/ˌoʊvərˈkʌm/","v."],
["graduate","毕业","/ˈɡrædʒueɪt/","v."],["senior","高级的","/ˈsiːniər/","adj."],
["text","文本","/tekst/","n."],["level","水平","/ˈlevl/","n."],
["degree","学位","/dɪˈɡriː/","n."],["manager","经理","/ˈmænɪdʒər/","n."],
["gentleman","先生","/ˈdʒentlmən/","n."],["graduation","毕业","/ˌɡrædʒuˈeɪʃn/","n."],
["ceremony","典礼","/ˈserəmoʊni/","n."],["congratulate","祝贺","/kənˈɡrætʃuleɪt/","v."],
["thirsty","口渴的","/ˈθɜːrsti/","adj."],["task","任务","/tæsk/","n."],
["ahead","在前面","/əˈhed/","adv."],["responsible","有责任的","/rɪˈspɑːnsəbl/","adj."],
["separate","分开","/ˈseprət/","v."],["wing","翅膀","/wɪŋ/","n."]]

g9={"grade":"初三（九年级）","semester":"全一册","textbook":"人教版 Go for it!",
     "units":[{"unit":1,"title":"U1 How can we become good learners?","words":_r(N1)},
              {"unit":2,"title":"U2 I think that mooncakes are delicious!","words":_r(N2)},
              {"unit":3,"title":"U3 Could you please tell me where...?","words":_r(N3)},
              {"unit":4,"title":"U4 I used to be afraid of the dark.","words":_r(N4)},
              {"unit":5,"title":"U5 What are the shirts made of?","words":_r(N5)},
              {"unit":6,"title":"U6 When was it invented?","words":_r(N6)},
              {"unit":7,"title":"U7 Teenagers should be allowed to...","words":_r(N7)},
              {"unit":8,"title":"U8 It must belong to Carla.","words":_r(N8)},
              {"unit":9,"title":"U9 I like music that I can dance to.","words":_r(N9)},
              {"unit":10,"title":"U10 You're supposed to shake hands.","words":_r(N10)},
              {"unit":11,"title":"U11 Sad movies make me cry.","words":_r(N11)},
              {"unit":12,"title":"U12 Life is full of the unexpected.","words":_r(N12)},
              {"unit":13,"title":"U13 We're trying to save the earth!","words":_r(N13)},
              {"unit":14,"title":"U14 I remember meeting all of you...","words":_r(N14)}]}
S("grade9.json",g9)

# ================================================================
# 高一~高三：2019新人教版核心词汇。按必修/选择性必修分3个文件
# ================================================================
# 高一 (grade10): 必修1-3 核心词汇
H1W=[["exchange","交换","/ɪksˈtʃeɪndʒ/","n."],["lecture","讲座","/ˈlektʃər/","n."],
["female","女性","/ˈfiːmeɪl/","adj."],["male","男性","/meɪl/","adj."],
["nationality","国籍","/ˌnæʃəˈnæləti/","n."],["designer","设计师","/dɪˈzaɪnər/","n."],
["campus","校园","/ˈkæmpəs/","n."],["formal","正式的","/ˈfɔːrml/","adj."],
["anxious","焦虑的","/ˈæŋkʃəs/","adj."],["annoyed","恼怒的","/əˈnɔɪd/","adj."],
["frightened","害怕的","/ˈfraɪtnd/","adj."],["senior","高中的","/ˈsiːniər/","adj."],
["outgoing","外向的","/ˈaʊtɡoʊɪŋ/","adj."],["impression","印象","/ɪmˈpreʃn/","n."],
["concentrate","集中","/ˈkɑːnsntreɪt/","v."],["explore","探索","/ɪkˈsplɔːr/","v."],
["confident","自信的","/ˈkɑːnfɪdənt/","adj."],["organise","组织","/ˈɔːrɡənaɪz/","v."],
["goal","目标","/ɡoʊl/","n."],["strategy","策略","/ˈstrætədʒi/","n."],
["partner","搭档","/ˈpɑːrtnər/","n."],["improve","改进","/ɪmˈpruːv/","v."],
["curious","好奇的","/ˈkjʊriəs/","adj."],["company","公司","/ˈkʌmpəni/","n."],
["personality","个性","/ˌpɜːrsəˈnæləti/","n."],["revise","复习","/rɪˈvaɪz/","v."]]
H2W=[["castle","城堡","/ˈkæsl/","n."],["apply","申请","/əˈplaɪ/","v."],
["rent","租用","/rent/","v."],["pack","打包","/pæk/","v."],
["arrange","安排","/əˈreɪndʒ/","v."],["recognise","认出","/ˈrekəɡnaɪz/","v."],
["type","类型","/taɪp/","n."],["flight","航班","/flaɪt/","n."],
["accommodation","住宿","/əˌkɑːməˈdeɪʃn/","n."],["unique","独特的","/juˈniːk/","adj."],
["destination","目的地","/ˌdestɪˈneɪʃn/","n."],["transport","交通","/ˈtrænspɔːrt/","n."],
["request","请求","/rɪˈkwest/","n."],["view","景色","/vjuː/","n."],
["source","来源","/sɔːrs/","n."],["narrow","狭窄的","/ˈnæroʊ/","adj."],
["flat","公寓","/flæt/","n."],["powerful","强大的","/ˈpaʊərfl/","adj."],
["empire","帝国","/ˈempaɪər/","n."],["emperor","皇帝","/ˈempərər/","n."],
["site","地点","/saɪt/","n."],["official","官方的","/əˈfɪʃl/","adj."],
["recognise","认出","/ˈrekəɡnaɪz/","v."],["path","小路","/pæθ/","n."],
["contact","联系","/ˈkɑːntækt/","v."],["civilisation","文明","/ˌsɪvələˈzeɪʃn/","n."],
["soldier","士兵","/ˈsoʊldʒər/","n."]]
H3W=[["athlete","运动员","/ˈæθliːt/","n."],["master","掌握","/ˈmæstər/","v."],
["honour","荣誉","/ˈɑːnər/","n."],["determination","决心","/dɪˌtɜːrmɪˈneɪʃn/","n."],
["failure","失败","/ˈfeɪljər/","n."],["compete","竞争","/kəmˈpiːt/","v."],
["stress","压力","/stres/","n."],["positive","积极的","/ˈpɑːzətɪv/","adj."],
["injury","伤害","/ˈɪndʒəri/","n."],["strength","力量","/streŋθ/","n."],
["volunteer","志愿者","/ˌvɑːlənˈtɪr/","n."],["debate","辩论","/dɪˈbeɪt/","n."],
["prefer","更喜欢","/prɪˈfɜːr/","v."],["content","内容","/ˈkɑːntent/","n."],
["movement","运动","/ˈmuːvmənt/","n."],["confuse","使糊涂","/kənˈfjuːz/","v."],
["fluent","流利的","/ˈfluːənt/","adj."],["graduate","毕业","/ˈɡrædʒueɪt/","v."],
["recommend","推荐","/ˌrekəˈmend/","v."],["advance","前进","/ədˈvæns/","v."],
["obviously","明显地","/ˈɑːbviəsli/","adv."],["responsibility","责任","/rɪˌspɑːnsəˈbɪləti/","n."],
["editor","编辑","/ˈedɪtər/","n."],["adventure","冒险","/ədˈventʃər/","n."],
["survival","生存","/sərˈvaɪvl/","n."],["official","官员","/əˈfɪʃl/","n."],
["rescue","营救","/ˈreskjuː/","v."],["damage","损害","/ˈdæmɪdʒ/","v."],
["affect","影响","/əˈfekt/","v."],["supply","供应","/səˈplaɪ/","n."],
["emergency","紧急情况","/iˈmɜːrdʒənsi/","n."],["effort","努力","/ˈefərt/","n."]]

g10={"grade":"高一","semester":"必修1-3","textbook":"2019人教版高中英语",
      "units":[{"unit":1,"title":"Welcome Unit + B1U1 Teenage Life","words":_r(H1W)},
               {"unit":2,"title":"B1U2-B2U1 Travelling & Culture","words":_r(H2W)},
               {"unit":3,"title":"B1U3-B3U2 Sports & Morals","words":_r(H3W)}]}
S("grade10.json",g10)

# 高二 (grade11): 选择性必修1-4
H4W=[["achievement","成就","/əˈtʃiːvmənt/","n."],["commitment","承诺","/kəˈmɪtmənt/","n."],
["academic","学术的","/ˌækəˈdemɪk/","adj."],["objective","目标","/əbˈdʒektɪv/","n."],
["evaluate","评估","/ɪˈvæljueɪt/","v."],["distinct","明显的","/dɪˈstɪŋkt/","adj."],
["insist","坚持","/ɪnˈsɪst/","v."],["conclusion","结论","/kənˈkluːʒn/","n."],
["circumstance","环境","/ˈsɜːrkəmstæns/","n."],["consequence","后果","/ˈkɑːnsɪkwens/","n."],
["remarkable","非凡的","/rɪˈmɑːrkəbl/","adj."],["apparently","显然","/əˈpærəntli/","adv."],
["innovation","创新","/ˌɪnəˈveɪʃn/","n."],["available","可获得的","/əˈveɪləbl/","adj."],
["forecast","预测","/ˈfɔːrkæst/","v."],["artificial","人工的","/ˌɑːrtɪˈfɪʃl/","adj."],
["predict","预测","/prɪˈdɪkt/","v."],["combine","结合","/kəmˈbaɪn/","v."],
["occupation","职业","/ˌɑːkjuˈpeɪʃn/","n."],["opportunity","机会","/ˌɑːpərˈtuːnəti/","n."],
["absence","缺席","/ˈæbsəns/","n."],["preference","偏好","/ˈprefrəns/","n."],
["environment","环境","/ɪnˈvaɪrənmənt/","n."],["pollution","污染","/pəˈluːʃn/","n."],
["sustainable","可持续的","/səˈsteɪnəbl/","adj."],["restore","恢复","/rɪˈstɔːr/","v."],
["release","释放","/rɪˈliːs/","v."],["campaign","运动","/kæmˈpeɪn/","n."],
["strategy","策略","/ˈstrætədʒi/","n."],["threat","威胁","/θret/","n."]]
H5W=[["brilliant","杰出的","/ˈbrɪliənt/","adj."],["contribution","贡献","/ˌkɑːntrɪˈbjuːʃn/","n."],
["revolution","革命","/ˌrevəˈluːʃn/","n."],["enthusiasm","热情","/ɪnˈθuːziæzəm/","n."],
["cautious","谨慎的","/ˈkɔːʃəs/","adj."],["suspect","怀疑","/səˈspekt/","v."],
["blame","责备","/bleɪm/","v."],["handle","处理","/ˈhændl/","v."],
["expose","暴露","/ɪkˈspoʊz/","v."],["absorb","吸收","/əbˈzɔːrb/","v."],
["poetry","诗歌","/ˈpoʊətri/","n."],["emotion","情感","/ɪˈmoʊʃn/","n."],
["convey","传达","/kənˈveɪ/","v."],["transform","转变","/trænsˈfɔːrm/","v."],
["sorrow","悲伤","/ˈsɑːroʊ/","n."],["exchange","交换","/ɪksˈtʃeɪndʒ/","v."],
["eventually","最终","/ɪˈventʃuəli/","adv."],["abuse","滥用","/əˈbjuːz/","n."],
["ban","禁止","/bæn/","v."],["quit","戒掉","/kwɪt/","v."],
["tough","艰苦的","/tʌf/","adj."],["mental","精神的","/ˈmentl/","adj."],
["strengthen","加强","/ˈstreŋθn/","v."],["accustomed","习惯的","/əˈkʌstəmd/","adj."],
["desperate","绝望的","/ˈdespərət/","adj."],["withdraw","退出","/wɪðˈdrɔː/","v."],
["effect","效果","/ɪˈfekt/","n."],["phenomenon","现象","/fɪˈnɑːmɪnən/","n."],
["conflict","冲突","/ˈkɑːnflɪkt/","n."],["harmony","和谐","/ˈhɑːrməni/","n."]]

g11={"grade":"高二","semester":"选择性必修1-4","textbook":"2019人教版高中英语",
      "units":[{"unit":1,"title":"选必U1-B2 人物成就与科技创新","words":_r(H4W)},
               {"unit":2,"title":"选必U3-B4 诗歌健康与人生","words":_r(H5W)}]}
S("grade11.json",g11)

# 高三 (grade12): 高考高频核心词汇
H6W=[["abandon","放弃","/əˈbændən/","v."],["absorb","吸收","/əbˈzɔːrb/","v."],
["abstract","抽象的","/ˈæbstrækt/","adj."],["abundant","丰富的","/əˈbʌndənt/","adj."],
["abuse","滥用","/əˈbjuːz/","v."],["academy","学院","/əˈkædəmi/","n."],
["accelerate","加速","/əkˈseləreɪt/","v."],["access","进入","/ˈækses/","n."],
["accommodate","容纳","/əˈkɑːmədeɪt/","v."],["accompany","陪伴","/əˈkʌmpəni/","v."],
["accomplish","完成","/əˈkɑːmplɪʃ/","v."],["account","账户","/əˈkaʊnt/","n."],
["accumulate","积累","/əˈkjuːmjəleɪt/","v."],["accurate","精确的","/ˈækjərət/","adj."],
["accuse","指控","/əˈkjuːz/","v."],["achieve","实现","/əˈtʃiːv/","v."],
["acknowledge","承认","/əkˈnɑːlɪdʒ/","v."],["acquire","获得","/əˈkwaɪər/","v."],
["adapt","适应","/əˈdæpt/","v."],["adequate","充足的","/ˈædɪkwət/","adj."],
["adjust","调整","/əˈdʒʌst/","v."],["administration","管理","/ədˌmɪnɪˈstreɪʃn/","n."],
["admire","钦佩","/ədˈmaɪər/","v."],["adopt","采纳","/əˈdɑːpt/","v."],
["advance","前进","/ədˈvæns/","v."],["advantage","优势","/ədˈvæntɪdʒ/","n."],
["advertise","做广告","/ˈædvərtaɪz/","v."],["advocate","提倡","/ˈædvəkeɪt/","v."],
["affair","事务","/əˈfer/","n."],["affection","喜爱","/əˈfekʃn/","n."],
["aggressive","侵略的","/əˈɡresɪv/","adj."],["allocate","分配","/ˈæləkeɪt/","v."],
["alternative","替代方案","/ɔːlˈtɜːrnətɪv/","n."],["amateur","业余爱好者","/ˈæmətər/","n."],
["ambition","雄心","/æmˈbɪʃn/","n."],["analyse","分析","/ˈænəlaɪz/","v."],
["ancestor","祖先","/ˈænsestər/","n."],["annual","年度的","/ˈænjuəl/","adj."],
["anticipate","预期","/ænˈtɪsɪpeɪt/","v."],["anxiety","焦虑","/æŋˈzaɪəti/","n."],
["apparent","明显的","/əˈpærənt/","adj."],["appeal","吸引","/əˈpiːl/","v."],
["appetite","食欲","/ˈæpɪtaɪt/","n."],["appliance","电器","/əˈplaɪəns/","n."],
["applicant","申请人","/ˈæplɪkənt/","n."],["appoint","任命","/əˈpɔɪnt/","v."],
["appreciate","欣赏","/əˈpriːʃieɪt/","v."],["approach","方法","/əˈproʊtʃ/","n."],
["appropriate","适当的","/əˈproʊpriət/","adj."],["approve","批准","/əˈpruːv/","v."]]

g12={"grade":"高三","semester":"高考冲刺","textbook":"2019人教版 + 高考大纲核心词",
      "units":[{"unit":1,"title":"高考高频核心词 A-Z (Part 1)","words":_r(H6W)}]}
S("grade12.json",g12)

print("\n✅ All grades built successfully!")
