#!/usr/bin/env python3
"""Build complete high school vocabulary JSON (all 7 books, ~36 units)"""
import json, os, sys
if sys.platform=='win32': import io; sys.stdout=io.TextIOWrapper(sys.stdout.buffer,encoding='utf-8')

BASE=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT=os.path.join(BASE,'data','vocabulary')
os.makedirs(OUT,exist_ok=True)

def _r(arr): return [{"en":x[0],"zh":x[1],"phonetic":x[2] if len(x)>2 else "","pos":x[3] if len(x)>3 else "","example":"","exampleZh":""} for x in arr]

def S(name,data):
    p=os.path.join(OUT,name)
    with open(p,'w',encoding='utf-8') as f: json.dump(data,f,ensure_ascii=False,indent=2)
    t=sum(len(u["words"]) for u in data["units"])
    print(f"  {name}: {len(data['units'])} units, {t} words")

# ================================================================
# 必修一 (Book 1): Welcome Unit + Units 1-5
# ================================================================
B1W=["Welcome Unit", [
    ["exchange","交换","/ɪksˈtʃeɪndʒ/","n.&vt."],["lecture","讲座；讲课","/ˈlektʃər/","n.&vi."],
    ["female","女子；女性的","/ˈfiːmeɪl/","adj.&n."],["male","男子；男性的","/meɪl/","adj.&n."],
    ["nationality","国籍","/ˌnæʃəˈnæləti/","n."],["designer","设计师","/dɪˈzaɪnər/","n."],
    ["campus","校园","/ˈkæmpəs/","n."],["formal","正式的","/ˈfɔːrml/","adj."],
    ["anxious","焦虑的","/ˈæŋkʃəs/","adj."],["annoyed","恼怒的","/əˈnɔɪd/","adj."],
    ["frightened","害怕的","/ˈfraɪtnd/","adj."],["awkward","令人尴尬的","/ˈɔːkwərd/","adj."],
    ["junior","职位低的；青少年的","/ˈdʒuːniər/","adj.&n."],["explore","探索","/ɪkˈsplɔːr/","vt.&vi."],
    ["confident","自信的","/ˈkɑːnfɪdənt/","adj."],["forward","向前","/ˈfɔːrwərd/","adv."],
    ["flash","闪光；闪现","/flæʃ/","n.&vi."],["goal","目标","/ɡoʊl/","n."],
    ["strategy","策略","/ˈstrætədʒi/","n."],["partner","搭档","/ˈpɑːrtnər/","n."],
    ["improve","改进","/ɪmˈpruːv/","vi.&vt."],["curious","好奇的","/ˈkjʊriəs/","adj."],
    ["company","公司；陪伴","/ˈkʌmpəni/","n."],["personality","个性","/ˌpɜːrsəˈnæləti/","n."],
    ["revise","复习；修订","/rɪˈvaɪz/","vt.&vi."],["style","风格","/staɪl/","n."],
    ["extra-curricular","课外的","/ˌekstrəkəˈrɪkjələr/","adj."],["senior","高级的；高中部的","/ˈsiːniər/","adj."],
    ["concentrate","集中注意力","/ˈkɑːnsntreɪt/","vi.&vt."],["experiment","实验","/ɪkˈsperɪmənt/","n."],
    ["leave...alone","不打扰","","phr."],["impression","印象","/ɪmˈpreʃn/","n."],
    ["organise","组织","/ˈɔːrɡənaɪz/","vt.&vi."],["guy","小伙子","/ɡaɪ/","n."],
]]

B1U1=["Unit 1 Teenage Life", [
    ["teenage","十几岁的","/ˈtiːneɪdʒ/","adj."],["teenager","青少年","/ˈtiːneɪdʒər/","n."],
    ["ballet","芭蕾舞","/bæˈleɪ/","n."],["volunteer","志愿者","/ˌvɑːlənˈtɪr/","n."],
    ["debate","辩论","/dɪˈbeɪt/","n.&v."],["prefer","更喜欢","/prɪˈfɜːr/","vt."],
    ["content","内容；满意的","/ˈkɑːntent/","n.&adj."],["movement","动作；运动","/ˈmuːvmənt/","n."],
    ["greenhouse","温室","/ˈɡriːnhaʊs/","n."],["suitable","适合的","/ˈsuːtəbl/","adj."],
    ["actually","事实上","/ˈæktʃuəli/","adv."],["challenge","挑战","/ˈtʃælɪndʒ/","n.&vt."],
    ["title","标题；头衔","/ˈtaɪtl/","n."],["topic","话题","/ˈtɑːpɪk/","n."],
    ["freshman","大一新生；高一新生","/ˈfreʃmən/","n."],["confuse","使糊涂","/kənˈfjuːz/","vt."],
    ["confused","糊涂的","/kənˈfjuːzd/","adj."],["confusing","难以理解的","/kənˈfjuːzɪŋ/","adj."],
    ["fluent","流利的","/ˈfluːənt/","adj."],["graduate","毕业；毕业生","/ˈɡrædʒueɪt/","vi.&vt.&n."],
    ["recommend","推荐","/ˌrekəˈmend/","vt."],["advance","前进；进步","/ədˈvæns/","n.&vi."],
    ["advanced","高级的","/ədˈvænst/","adj."],["literature","文学","/ˈlɪtrətʃər/","n."],
    ["extra","额外的","/ˈekstrə/","adj."],["obviously","明显地","/ˈɑːbviəsli/","adv."],
    ["quit","停止；戒掉","/kwɪt/","vi.&vt."],["responsible","负责的","/rɪˈspɑːnsəbl/","adj."],
    ["responsibility","责任","/rɪˌspɑːnsəˈbɪləti/","n."],["solution","解决办法","/səˈluːʃn/","n."],
    ["schedule","日程表","/ˈʃedjuːl/","n.&vt."],["editor","编辑","/ˈedɪtər/","n."],
    ["adventure","冒险","/ədˈventʃər/","n."],["expert","专家","/ˈekspɜːrt/","n.&adj."],
    ["youth","青年；青春","/juːθ/","n."],["survival","生存","/sərˈvaɪvl/","n."],
    ["plate","盘子","/pleɪt/","n."],["adult","成人","/ˈædʌlt/","n.&adj."],
    ["attract","吸引","/əˈtrækt/","vt."],["focus","集中；焦点","/ˈfoʊkəs/","vi.&vt.&n."],
    ["addicted","上瘾的","/əˈdɪktɪd/","adj."],
]]

B1U2=["Unit 2 Travelling Around", [
    ["castle","城堡","/ˈkæsl/","n."],["apply","申请；应用","/əˈplaɪ/","vi.&vt."],
    ["visa","签证","/ˈviːzə/","n."],["rent","租用；出租","/rent/","vt.&n."],
    ["pack","打包；收拾","/pæk/","vi.&vt."],["amazing","令人惊奇的","/əˈmeɪzɪŋ/","adj."],
    ["amazed","惊奇的","/əˈmeɪzd/","adj."],["arrangement","安排","/əˈreɪndʒmənt/","n."],
    ["extremely","极其","/ɪkˈstriːmli/","adv."],["source","来源","/sɔːrs/","n."],
    ["narrow","狭窄的","/ˈnæroʊ/","adj.&vi.&vt."],["flat","公寓；平坦的","/flæt/","adj.&n."],
    ["powerful","强大的","/ˈpaʊərfl/","adj."],["empire","帝国","/ˈempaɪər/","n."],
    ["emperor","皇帝","/ˈempərər/","n."],["site","地点；遗址","/saɪt/","n."],
    ["official","官方的；官员","/əˈfɪʃl/","adj.&n."],["recognise","认出；承认","/ˈrekəɡnaɪz/","vt."],
    ["type","类型；打字","/taɪp/","n.&vi.&vt."],["flight","航班；飞行","/flaɪt/","n."],
    ["accommodation","住宿","/əˌkɑːməˈdeɪʃn/","n."],["unique","独特的","/juˈniːk/","adj."],
    ["path","小路","/pæθ/","n."],["destination","目的地","/ˌdestɪˈneɪʃn/","n."],
    ["admire","钦佩；欣赏","/ədˈmaɪər/","vt."],["architecture","建筑学","/ˈɑːrkɪtektʃər/","n."],
    ["architect","建筑师","/ˈɑːrkɪtekt/","n."],["brochure","小册子","/broʊˈʃʊr/","n."],
    ["package","包裹","/ˈpækɪdʒ/","n."],["contact","联系","/ˈkɑːntækt/","vt.&n."],
    ["civilisation","文明","/ˌsɪvələˈzeɪʃn/","n."],["soldier","士兵","/ˈsoʊldʒər/","n."],
    ["transport","交通；运输","/ˈtrænspɔːrt/","n.&vt."],["hike","远足","/haɪk/","vi.&n."],
    ["economy","经济","/ɪˈkɑːnəmi/","n."],["credit","信用","/ˈkredɪt/","n."],
    ["detail","细节","/ˈdiːteɪl/","n."],["request","请求","/rɪˈkwest/","n.&vt."],
    ["view","视野；景色","/vjuː/","n."],["sight","景象；视力","/saɪt/","n."],
    ["statue","雕像","/ˈstætʃuː/","n."],["tomb","坟墓","/tuːm/","n."],
    ["unearth","发掘","/ʌnˈɜːrθ/","vt."],["comment","评论","/ˈkɑːment/","n.&vi.&vt."],
]]

B1U3=["Unit 3 Sports and Fitness", [
    ["fitness","健康；适合","/ˈfɪtnəs/","n."],["soccer","足球","/ˈsɑːkər/","n."],
    ["stadium","体育场","/ˈsteɪdiəm/","n."],["boxing","拳击","/ˈbɑːksɪŋ/","n."],
    ["badminton","羽毛球","/ˈbædmɪntən/","n."],["marathon","马拉松","/ˈmærəθɑːn/","n."],
    ["event","比赛项目；大事","/ɪˈvent/","n."],["ski","滑雪","/skiː/","adj.&vi."],
    ["host","主办；主人","/hoʊst/","vt.&n."],["track","跑道；踪迹","/træk/","n.&vi.&vt."],
    ["gym","健身房","/dʒɪm/","n."],["gymnastics","体操","/dʒɪmˈnæstɪks/","n."],
    ["sweat","出汗","/swet/","vt.&vi.&n."],["legend","传奇","/ˈledʒənd/","n."],
    ["athlete","运动员","/ˈæθliːt/","n."],["master","掌握；大师","/ˈmæstər/","vt.&n."],
    ["honour","荣誉","/ˈɑːnər/","n.&vt."],["glory","荣耀","/ˈɡlɔːri/","n."],
    ["medal","奖牌","/ˈmedl/","n."],["championship","锦标赛","/ˈtʃæmpiənʃɪp/","n."],
    ["champion","冠军","/ˈtʃæmpiən/","n."],["determination","决心","/dɪˌtɜːrmɪˈneɪʃn/","n."],
    ["injure","使受伤","/ˈɪndʒər/","vt."],["injury","伤害","/ˈɪndʒəri/","n."],
    ["captain","队长；船长","/ˈkæptɪn/","n."],["graceful","优雅的","/ˈɡreɪsfl/","adj."],
    ["strength","力量；优点","/streŋθ/","n."],["failure","失败","/ˈfeɪljər/","n."],
    ["compete","竞争","/kəmˈpiːt/","vi."],["pretend","假装","/prɪˈtend/","vi.&vt."],
    ["million","百万","/ˈmɪljən/","num."],["cheat","作弊；欺骗","/tʃiːt/","vi.&vt.&n."],
    ["audience","观众","/ˈɔːdiəns/","n."],["positive","积极的","/ˈpɑːzətɪv/","adj."],
    ["slim","苗条的","/slɪm/","adj."],["diet","饮食","/ˈdaɪət/","n.&vi."],
    ["jog","慢跑","/dʒɑːɡ/","vi.&n."],["stress","压力","/stres/","n.&vt."],
    ["error","错误","/ˈerər/","n."],["push-up","俯卧撑","/ˈpʊʃʌp/","n."],
]]

B1U4=["Unit 4 Natural Disasters", [
    ["disaster","灾难","/dɪˈzæstər/","n."],["tornado","龙卷风","/tɔːrˈneɪdoʊ/","n."],
    ["drought","干旱","/draʊt/","n."],["landslide","山体滑坡","/ˈlændslaɪd/","n."],
    ["slide","滑动；幻灯片","/slaɪd/","vi.&vt.&n."],["tsunami","海啸","/tsuːˈnɑːmi/","n."],
    ["flood","洪水","/flʌd/","n.&vi.&vt."],["volcanic","火山的","/vɑːlˈkænɪk/","adj."],
    ["eruption","喷发","/ɪˈrʌpʃn/","n."],["magnitude","震级","/ˈmæɡnɪtuːd/","n."],
    ["rescue","营救","/ˈreskjuː/","n.&vt."],["damage","损害","/ˈdæmɪdʒ/","vt.&n."],
    ["destroy","摧毁","/dɪˈstrɔɪ/","vt."],["evacuate","疏散","/ɪˈvækjueɪt/","vt.&vi."],
    ["helicopter","直升机","/ˈhelɪkɑːptər/","n."],["death","死亡","/deθ/","n."],
    ["affect","影响","/əˈfekt/","vt."],["shelter","避难所","/ˈʃeltər/","n.&vt."],
    ["crack","裂缝；破裂","/kræk/","n.&vi.&vt."],["ruin","废墟；毁灭","/ˈruːɪn/","n.&vt."],
    ["percent","百分之","/pərˈsent/","n."],["brick","砖","/brɪk/","n."],
    ["metal","金属","/ˈmetl/","n."],["shock","震惊","/ʃɑːk/","n.&vt."],
    ["electricity","电","/ɪˌlekˈtrɪsəti/","n."],["trap","困住；陷阱","/træp/","vt.&n."],
    ["bury","埋葬","/ˈberi/","vt."],["breathe","呼吸","/briːð/","vi.&vt."],
    ["revive","复活；苏醒","/rɪˈvaɪv/","vt.&vi."],["effort","努力","/ˈefərt/","n."],
    ["wisdom","智慧","/ˈwɪzdəm/","n."],["context","上下文","/ˈkɑːntekst/","n."],
    ["suffer","遭受","/ˈsʌfər/","vt.&vi."],["volcano","火山","/vɑːlˈkeɪnoʊ/","n."],
    ["erupt","喷发","/ɪˈrʌpt/","vi.&vt."],["supply","供应","/səˈplaɪ/","n.&vt."],
    ["typhoon","台风","/taɪˈfuːn/","n."],["hurricane","飓风","/ˈhɜːrəkeɪn/","n."],
    ["survive","幸存","/sərˈvaɪv/","vi.&vt."],["power","电力；权力","/ˈpaʊər/","n."],
    ["tap","水龙头","/tæp/","n.&vi.&vt."],["pipe","管子","/paɪp/","n."],
    ["whistle","哨子；吹口哨","/ˈwɪsl/","n.&vi.&vt."],["emergency","紧急情况","/iˈmɜːrdʒənsi/","n."],
    ["calm","镇静的","/kɑːm/","adj.&vt."],["aid","援助","/eɪd/","n.&vt."],
    ["crash","碰撞；坠毁","/kræʃ/","vi.&vt.&n."],["sweep","打扫；席卷","/swiːp/","vt.&vi."],
    ["wave","波浪","/weɪv/","n.&vi.&vt."],["strike","袭击；罢工","/straɪk/","vi.&vt.&n."],
    ["deliver","递送","/dɪˈlɪvər/","vt.&vi."],["summary","总结","/ˈsʌməri/","n."],
    ["effect","影响；效果","/ɪˈfekt/","n."],["length","长度","/leŋθ/","n."],
]]

B1U5=["Unit 5 Languages Around the World", [
    ["billion","十亿","/ˈbɪljən/","n."],["native","本地的；本地人","/ˈneɪtɪv/","adj.&n."],
    ["attitude","态度","/ˈætɪtuːd/","n."],["reference","参考","/ˈrefrəns/","n."],
    ["refer","提到；参考","/rɪˈfɜːr/","vi.&vt."],["system","系统","/ˈsɪstəm/","n."],
    ["despite","尽管","/dɪˈspaɪt/","prep."],["factor","因素","/ˈfæktər/","n."],
    ["based","根据的","/beɪst/","adj."],["base","基础；基地","/beɪs/","vt.&n."],
    ["bone","骨头","/boʊn/","n."],["shell","壳","/ʃel/","n."],
    ["symbol","象征","/ˈsɪmbl/","n."],["carve","雕刻","/kɑːrv/","vt.&vi."],
    ["dynasty","朝代","/ˈdaɪnəsti/","n."],["variety","种类","/vəˈraɪəti/","n."],
    ["major","主要的","/ˈmeɪdʒər/","adj.&n.&vi."],["dialect","方言","/ˈdaɪəlekt/","n."],
    ["means","方式","/miːnz/","n."],["classic","经典的","/ˈklæsɪk/","adj.&n."],
    ["regard","看待；问候","/rɪˈɡɑːrd/","vt.&n."],["character","文字；角色","/ˈkærəktər/","n."],
    ["calligraphy","书法","/kəˈlɪɡrəfi/","n."],["global","全球的","/ˈɡloʊbl/","adj."],
    ["affair","事务","/əˈfer/","n."],["appreciate","欣赏；感激","/əˈpriːʃieɪt/","vt."],
    ["specific","具体的","/spəˈsɪfɪk/","adj."],["tongue","舌头；语言","/tʌŋ/","n."],
    ["semester","学期","/sɪˈmestər/","n."],["gas","汽油","/ɡæs/","n."],
    ["petrol","汽油","/ˈpetrəl/","n."],["subway","地铁","/ˈsʌbweɪ/","n."],
    ["apartment","公寓","/əˈpɑːrtmənt/","n."],["pants","裤子","/pænts/","n."],
    ["equal","相等的","/ˈiːkwəl/","adj.&n.&vt."],["gap","差距","/ɡæp/","n."],
    ["demand","需求","/dɪˈmænd/","n.&vt."],["vocabulary","词汇","/vəˈkæbjəleri/","n."],
    ["description","描述","/dɪˈskrɪpʃn/","n."],["relate","联系","/rɪˈleɪt/","vt.&vi."],
]]

# ================================================================
# 必修二 (Book 2): Units 1-5
# ================================================================
B2U1=["Unit 1 Cultural Heritage", [
    ["heritage","遗产","/ˈherɪtɪdʒ/","n."],["creatively","创造性地","/kriˈeɪtɪvli/","adv."],
    ["creative","创造性的","/kriˈeɪtɪv/","adj."],["temple","寺庙","/ˈtempl/","n."],
    ["relic","遗迹","/ˈrelɪk/","n."],["mount","山；安装","/maʊnt/","n.&vt."],
    ["former","以前的","/ˈfɔːrmər/","adj."],["clue","线索","/kluː/","n."],
    ["preserve","保存","/prɪˈzɜːrv/","vt."],["promote","促进","/prəˈmoʊt/","vt."],
    ["application","申请","/ˌæplɪˈkeɪʃn/","n."],["take part in","参加","","phr."],
    ["give way to","让步于","","phr."],["balance","平衡","/ˈbæləns/","n.&vt."],
    ["proposal","提议","/prəˈpoʊzl/","n."],["protest","抗议","/prəˈtest, ˈproʊtest/","n.&vi.&vt."],
    ["likely","可能的","/ˈlaɪkli/","adj.&adv."],["committee","委员会","/kəˈmɪti/","n."],
    ["establish","建立","/ɪˈstæblɪʃ/","vt."],["limit","限制","/ˈlɪmɪt/","n.&vt."],
    ["prevent","阻止","/prɪˈvent/","vt."],["contribution","贡献","/ˌkɑːntrɪˈbjuːʃn/","n."],
    ["contribute","捐献","/kənˈtrɪbjuːt/","vi.&vt."],["department","部门","/dɪˈpɑːrtmənt/","n."],
    ["fund","基金","/fʌnd/","n."],["throughout","遍及","/θruːˈaʊt/","prep.&adv."],
    ["quality","质量","/ˈkwɑːləti/","n."],["tradition","传统","/trəˈdɪʃn/","n."],
    ["opinion","意见","/əˈpɪnjən/","n."],["quote","引用","/kwoʊt/","vt.&n."],
    ["paraphrase","释义；改写","/ˈpærəfreɪz/","n.&vt.&vi."],["comparison","比较","/kəmˈpærɪsn/","n."],
    ["contrast","对比","/ˈkɑːntræst/","n.&vt."],["identify","确认","/aɪˈdentɪfaɪ/","vt."],
    ["forever","永远","/fərˈevər/","adv."],["issue","问题","/ˈɪʃuː/","n.&vt."],
    ["conduct","实施；行为","/kənˈdʌkt, ˈkɑːndʌkt/","vt.&n."],["attempt","尝试","/əˈtempt/","n.&vt."],
    ["worthwhile","值得的","/ˌwɜːrθˈwaɪl/","adj."],["entrance","入口","/ˈentrəns/","n."],
    ["process","过程","/ˈprɑːses/","n.&vt."],["overseas","海外的","/ˌoʊvərˈsiːz/","adj.&adv."],
    ["exit","出口","/ˈeksɪt/","n.&vi."],["roof","屋顶","/ruːf/","n."],
    ["dragon","龙","/ˈdræɡən/","n."],["forgive","原谅","/fərˈɡɪv/","vt.&vi."],
    ["digital","数字的","/ˈdɪdʒɪtl/","adj."],["image","形象","/ˈɪmɪdʒ/","n."],
    ["cave","洞穴","/keɪv/","n."],["throughout","遍及","/θruːˈaʊt/","prep.&adv."],
    ["professional","专业的","/prəˈfeʃənl/","adj.&n."],
]]

B2U2=["Unit 2 Wildlife Protection", [
    ["poster","海报","/ˈpoʊstər/","n."],["illegal","非法的","/ɪˈliːɡl/","adj."],
    ["hunt","打猎","/hʌnt/","vt.&vi."],["species","物种","/ˈspiːʃiːz/","n."],
    ["shark","鲨鱼","/ʃɑːrk/","n."],["fin","鳍","/fɪn/","n."],
    ["on earth","究竟","","phr."],["die out","灭绝","","phr."],
    ["alarming","令人惊恐的","/əˈlɑːrmɪŋ/","adj."],["alarm","惊恐","/əˈlɑːrm/","vt.&n."],
    ["rate","比率","/reɪt/","n."],["extinction","灭绝","/ɪkˈstɪŋkʃn/","n."],
    ["mass","大量的","/mæs/","adj.&n."],["habitat","栖息地","/ˈhæbɪtæt/","n."],
    ["aware","意识到","/əˈwer/","adj."],["endanger","使遭危险","/ɪnˈdeɪndʒər/","vt."],
    ["average","平均的","/ˈævərɪdʒ/","adj.&n."],["living","生活","/ˈlɪvɪŋ/","adj.&n."],
    ["measure","措施","/ˈmeʒər/","n.&vt."],["authority","权威","/əˈθɔːrəti/","n."],
    ["pressure","压力","/ˈpreʃər/","n.&vt."],["whale","鲸","/weɪl/","n."],
    ["antelope","羚羊","/ˈæntɪloʊp/","n."],["reserve","保护区；保留","/rɪˈzɜːrv/","n.&vt."],
    ["plain","平原","/pleɪn/","n.&adj."],["observe","观察","/əbˈzɜːrv/","vt."],
    ["beauty","美","/ˈbjuːti/","n."],["remind","提醒","/rɪˈmaɪnd/","vt."],
    ["fur","毛皮","/fɜːr/","n."],["sacred","神圣的","/ˈseɪkrɪd/","adj."],
    ["shoot","射击","/ʃuːt/","vt.&vi."],["profit","利润","/ˈprɑːfɪt/","n."],
    ["attack","攻击","/əˈtæk/","n.&vt.&vi."],["effective","有效的","/ɪˈfektɪv/","adj."],
    ["recover","恢复","/rɪˈkʌvər/","vi.&vt."],["remove","移除","/rɪˈmuːv/","vt."],
    ["threat","威胁","/θret/","n."],["exist","存在","/ɪɡˈzɪst/","vi."],
    ["harmony","和谐","/ˈhɑːrməni/","n."],["creature","生物","/ˈkriːtʃər/","n."],
    ["goods","商品","/ɡʊdz/","n."],["deer","鹿","/dɪr/","n."],
    ["reduce","减少","/rɪˈduːs/","vt."],["due","由于","/duː/","adj."],
    ["insect","昆虫","/ˈɪnsekt/","n."],["net","网","/net/","n."],
    ["neighbourhood","社区","/ˈneɪbərhʊd/","n."],
]]

B2U3=["Unit 3 The Internet", [
    ["blog","博客","/blɑːɡ/","n.&vi."],["blogger","博主","/ˈblɑːɡər/","n."],
    ["engine","引擎","/ˈendʒɪn/","n."],["search engine","搜索引擎","","phr."],
    ["chat","聊天","/tʃæt/","vi.&n."],["stream","流播；溪流","/striːm/","vt.&vi.&n."],
    ["identity","身份","/aɪˈdentəti/","n."],["convenient","方便的","/kənˈviːniənt/","adj."],
    ["cash","现金","/kæʃ/","n."],["update","更新","/ˌʌpˈdeɪt/","vt.&n."],
    ["database","数据库","/ˈdeɪtəbeɪs/","n."],["software","软件","/ˈsɔːftwer/","n."],
    ["network","网络","/ˈnetwɜːrk/","n.&vt."],["stuck","卡住的","/stʌk/","adj."],
    ["keep sb company","陪伴某人","","phr."],["surf","冲浪","/sɜːrf/","vt.&vi."],
    ["inspire","激励","/ɪnˈspaɪər/","vt."],["access","通道；访问","/ˈækses/","n.&vt."],
    ["charity","慈善","/ˈtʃærəti/","n."],["tough","艰难的","/tʌf/","adj."],
    ["province","省","/ˈprɑːvɪns/","n."],["conference","会议","/ˈkɑːnfərəns/","n."],
    ["resident","居民","/ˈrezɪdənt/","n.&adj."],["plus","加","/plʌs/","conj.&prep."],
    ["function","功能","/ˈfʌŋkʃn/","n.&vi."],["battery","电池","/ˈbætəri/","n."],
    ["confirm","确认","/kənˈfɜːrm/","vt."],["press","按；压","/pres/","vt.&n."],
    ["button","按钮","/ˈbʌtn/","n."],["file","文件","/faɪl/","n."],
    ["discount","折扣","/ˈdɪskaʊnt/","n.&vt."],["account","账户","/əˈkaʊnt/","n."],
    ["click","点击","/klɪk/","vt.&vi."],["privacy","隐私","/ˈpraɪvəsi/","n."],
    ["theft","盗窃","/θeft/","n."],["rude","粗鲁的","/ruːd/","adj."],
    ["target","目标","/ˈtɑːrɡɪt/","n.&vt."],["false","虚假的","/fɔːls/","adj."],
    ["particular","特定的","/pərˈtɪkjələr/","adj."],["embarrassing","令人尴尬的","/ɪmˈbærəsɪŋ/","adj."],
    ["upset","不安的","/ʌpˈset/","adj.&vt."],["guideline","指南","/ˈɡaɪdlaɪn/","n."],
    ["author","作者","/ˈɔːθər/","n."],["tip","提示；小费","/tɪp/","n."],
    ["familiar","熟悉的","/fəˈmɪliər/","adj."],["define","定义","/dɪˈfaɪn/","vt."],
    ["case","情况；案件","/keɪs/","n."],
]]

B2U4=["Unit 4 History and Traditions", [
    ["Confucius","孔子","/kənˈfjuːʃəs/","n."],["philosophy","哲学","/fɪˈlɑːsəfi/","n."],
    ["descendant","后代","/dɪˈsendənt/","n."],["individual","个人；单独的","/ˌɪndɪˈvɪdʒuəl/","adj.&n."],
    ["heel","脚后跟","/hiːl/","n."],["kingdom","王国","/ˈkɪŋdəm/","n."],
    ["chief","首领","/tʃiːf/","adj.&n."],["puzzle","谜","/ˈpʌzl/","n.&vt."],
    ["nearby","附近的","/ˌnɪrˈbaɪ/","adj.&adv."],["belong","属于","/bɪˈlɔːŋ/","vi."],
    ["defence","防御","/dɪˈfens/","n."],["legal","法律的","/ˈliːɡl/","adj."],
    ["surround","围绕","/səˈraʊnd/","vt."],["evidence","证据","/ˈevɪdəns/","n."],
    ["achievement","成就","/əˈtʃiːvmənt/","n."],["location","位置","/loʊˈkeɪʃn/","n."],
    ["conquer","征服","/ˈkɑːŋkər/","vt."],["battle","战役","/ˈbætl/","n.&vi."],
    ["port","港口","/pɔːrt/","n."],["fascinating","迷人的","/ˈfæsɪneɪtɪŋ/","adj."],
    ["charge","收费；控告","/tʃɑːrdʒ/","n.&vt.&vi."],["amount","数量","/əˈmaʊnt/","n."],
    ["gallery","画廊","/ˈɡæləri/","n."],["approach","方法；接近","/əˈproʊtʃ/","n.&vt.&vi."],
    ["ensure","确保","/ɪnˈʃʊr/","vt."],["landscape","风景","/ˈlændskeɪp/","n."],
    ["generous","慷慨的","/ˈdʒenərəs/","adj."],["butter","黄油","/ˈbʌtər/","n."],
    ["honey","蜂蜜","/ˈhʌni/","n."],["ancestor","祖先","/ˈænsestər/","n."],
    ["position","位置","/pəˈzɪʃn/","n."],["courtyard","庭院","/ˈkɔːrtjɑːrd/","n."],
    ["snack","小吃","/snæk/","n."],["eager","渴望的","/ˈiːɡər/","adj."],
    ["poet","诗人","/ˈpoʊət/","n."],["county","郡；县","/ˈkaʊnti/","n."],
    ["feast","盛宴","/fiːst/","n."],["roll","卷；滚动","/roʊl/","n.&vi.&vt."],
    ["greet","问候","/ɡriːt/","vt."],["pub","酒吧","/pʌb/","n."],
    ["custom","风俗","/ˈkʌstəm/","n."],["striking","引人注目的","/ˈstraɪkɪŋ/","adj."],
    ["crowd","人群","/kraʊd/","n.&vt."],["transition","过渡","/trænˈzɪʃn/","n."],
]]

B2U5=["Unit 5 Music", [
    ["classical","古典的","/ˈklæsɪkl/","adj."],["hip-hop","嘻哈","/ˈhɪphɒp/","n."],
    ["techno","电子音乐","/ˈteknoʊ/","n."],["energy","能量","/ˈenərdʒi/","n."],
    ["soul","灵魂","/soʊl/","n."],["bagpipes","风笛","/ˈbæɡpaɪps/","n."],
    ["stringed","弦的","/strɪŋd/","adj."],["virtual","虚拟的","/ˈvɜːrtʃuəl/","adj."],
    ["choir","合唱团","/ˈkwaɪər/","n."],["composition","作曲","/ˌkɑːmpəˈzɪʃn/","n."],
    ["opportunity","机会","/ˌɑːpərˈtuːnəti/","n."],["performance","表演","/pərˈfɔːrməns/","n."],
    ["performer","表演者","/pərˈfɔːrmər/","n."],["onto","到……上","/ˈɑːntuː/","prep."],
    ["studio","工作室","/ˈstuːdioʊ/","n."],["ordinary","普通的","/ˈɔːrdneri/","adj."],
    ["enable","使能够","/ɪˈneɪbl/","vt."],["prove","证明","/pruːv/","vt.&vi."],
    ["award","奖；授予","/əˈwɔːrd/","vt.&n."],["composer","作曲家","/kəmˈpoʊzər/","n."],
    ["conductor","指挥","/kənˈdʌktər/","n."],["original","原来的","/əˈrɪdʒənl/","adj.&n."],
    ["phenomenon","现象","/fɪˈnɑːmɪnən/","n."],["stage","舞台","/steɪdʒ/","n."],
    ["altogether","总共","/ˌɔːltəˈɡeðər/","adv."],["thus","因此","/ðʌs/","adv."],
    ["band","乐队","/bænd/","n."],["rap","说唱","/ræp/","n.&vi."],
    ["nowadays","如今","/ˈnaʊədeɪz/","adv."],["gradual","逐渐的","/ˈɡrædʒuəl/","adj."],
    ["capable","有能力的","/ˈkeɪpəbl/","adj."],["relief","减轻；宽慰","/rɪˈliːf/","n."],
    ["cure","治愈","/kjʊr/","vt.&n."],["absorbed","被吸引住的","/əbˈzɔːrbd/","adj."],
    ["previous","先前的","/ˈpriːviəs/","adj."],["unemployed","失业的","/ˌʌnɪmˈplɔɪd/","adj."],
    ["romantic","浪漫的","/roʊˈmæntɪk/","adj."],["album","专辑","/ˈælbəm/","n."],
    ["impact","影响","/ˈɪmpækt/","n.&vt."],["aim","目标","/eɪm/","n.&vi.&vt."],
    ["equipment","设备","/ɪˈkwɪpmənt/","n."],["talent","天赋","/ˈtælənt/","n."],
    ["assume","假定","/əˈsuːm/","vt."],["reaction","反应","/riˈækʃn/","n."],
    ["treatment","治疗","/ˈtriːtmənt/","n."],["moreover","此外","/mɔːrˈoʊvər/","adv."],
    ["somehow","不知怎么地","/ˈsʌmhaʊ/","adv."],["outline","概述","/ˈaʊtlaɪn/","n.&vt."],
]]

# =============== SAVE GRADE 10 (高一) ===============
g10={"grade":"高一","semester":"必修一~三 (共3册)","textbook":"2019人教版高中英语",
     "units":[
         {"unit":0,"title":B1W[0],"words":_r(B1W[1])},
         {"unit":1,"title":B1U1[0],"words":_r(B1U1[1])},
         {"unit":2,"title":B1U2[0],"words":_r(B1U2[1])},
         {"unit":3,"title":B1U3[0],"words":_r(B1U3[1])},
         {"unit":4,"title":B1U4[0],"words":_r(B1U4[1])},
         {"unit":5,"title":B1U5[0],"words":_r(B1U5[1])},
         {"unit":6,"title":B2U1[0],"words":_r(B2U1[1])},
         {"unit":7,"title":B2U2[0],"words":_r(B2U2[1])},
         {"unit":8,"title":B2U3[0],"words":_r(B2U3[1])},
         {"unit":9,"title":B2U4[0],"words":_r(B2U4[1])},
         {"unit":10,"title":B2U5[0],"words":_r(B2U5[1])},
     ]}
S("grade10.json",g10)

# 必修三 (Book 3): U1-U5 from search results (abbreviated 50-70 words each)
B3U1=["Unit 1 Festivals and Celebrations", [
    ["lantern","灯笼","/ˈlæntərn/","n."],["carnival","狂欢节","/ˈkɑːrnɪvl/","n."],
    ["costume","服装","/ˈkɑːstuːm/","n."],["march","行进","/mɑːrtʃ/","vi.&n."],
    ["congratulation","祝贺","/kənˌɡrætʃuˈleɪʃn/","n."],["riddle","谜语","/ˈrɪdl/","n."],
    ["ceremony","典礼","/ˈserəmoʊni/","n."],["range","范围","/reɪndʒ/","n.&vi."],
    ["origin","起源","/ˈɔːrɪdʒɪn/","n."],["religion","宗教","/rɪˈlɪdʒən/","n."],
    ["religious","宗教的","/rɪˈlɪdʒəs/","adj."],["figure","人物；数字","/ˈfɪɡjər/","n.&vt."],
    ["charm","魅力","/tʃɑːrm/","n."],["joy","高兴","/dʒɔɪ/","n."],
    ["gratitude","感激","/ˈɡrætɪtuːd/","n."],["harvest","收获","/ˈhɑːrvɪst/","n.&vt."],
    ["agricultural","农业的","/ˌæɡrɪˈkʌltʃərəl/","adj."],["crop","庄稼","/krɑːp/","n."],
    ["gather","聚集","/ˈɡæðər/","vt.&vi."],["grateful","感激的","/ˈɡreɪtfl/","adj."],
    ["feature","以……为特色","/ˈfiːtʃər/","vt.&n."],["decorate","装饰","/ˈdekəreɪt/","vt."],
    ["significant","重大的","/sɪɡˈnɪfɪkənt/","adj."],["fade","逐渐消失","/feɪd/","vi.&vt."],
    ["typical","典型的","/ˈtɪpɪkl/","adj."],["evil","邪恶的","/ˈiːvl/","adj.&n."],
    ["commercial","商业的","/kəˈmɜːrʃl/","adj."],["medium","媒介","/ˈmiːdiəm/","n.&adj."],
    ["reflect","反映","/rɪˈflekt/","vt."],["belief","信仰","/bɪˈliːf/","n."],
    ["faith","信心","/feɪθ/","n."],["occasion","场合","/əˈkeɪʒn/","n."],
    ["atmosphere","氛围","/ˈætməsfɪr/","n."],["lunar","阴历的","/ˈluːnər/","adj."],
    ["eve","前夕","/iːv/","n."],["envelope","信封","/ˈenvəloʊp/","n."],
    ["merry","愉快的","/ˈmeri/","adj."],["roast","烤的","/roʊst/","adj.&vt."],
    ["turkey","火鸡","/ˈtɜːrki/","n."],["pleased","高兴的","/pliːzd/","adj."],
    ["firework","烟花","/ˈfaɪərwɜːrk/","n."],["frank","坦率的","/fræŋk/","adj."],
    ["region","地区","/ˈriːdʒən/","n."],["represent","代表","/ˌreprɪˈzent/","vt."],
    ["fancy","精致的；想要","/ˈfænsi/","adj.&vt."],["absolutely","完全地","/ˈæbsəluːtli/","adv."],
    ["tent","帐篷","/tent/","n."],["brief","简洁的","/briːf/","adj."],
    ["wedding","婚礼","/ˈwedɪŋ/","n."],["clap","鼓掌","/klæp/","vt.&n."],
    ["respect","尊敬","/rɪˈspekt/","n.&vt."],["horrible","恐怖的","/ˈhɔːrəbl/","adj."],
]]

B3U2=["Unit 2 Morals and Virtues", [
    ["moral","道德的","/ˈmɔːrəl/","adj.&n."],["virtue","美德","/ˈvɜːrtʃuː/","n."],
    ["dilemma","困境","/dɪˈlemə/","n."],["faint","昏倒","/feɪnt/","vi.&adj."],
    ["illustrate","说明","/ˈɪləstreɪt/","vt."],["precious","宝贵的","/ˈpreʃəs/","adj."],
    ["entrust","委托","/ɪnˈtrʌst/","vt."],["marriage","婚姻","/ˈmærɪdʒ/","n."],
    ["majority","大多数","/məˈdʒɔːrəti/","n."],["complain","抱怨","/kəmˈpleɪn/","vi.&vt."],
    ["tuition","学费；教学","/tuˈɪʃn/","n."],["fee","费用","/fiː/","n."],
    ["respond","回应","/rɪˈspɑːnd/","vi."],["union","协会","/ˈjuːniən/","n."],
    ["scholarship","奖学金","/ˈskɑːlərʃɪp/","n."],["hire","雇佣","/ˈhaɪər/","vt."],
    ["physician","医师","/fɪˈzɪʃn/","n."],["colleague","同事","/ˈkɑːliːɡ/","n."],
    ["reject","拒绝","/rɪˈdʒekt/","vt."],["appoint","任命","/əˈpɔɪnt/","vt."],
    ["clinic","诊所","/ˈklɪnɪk/","n."],["elect","选举","/ɪˈlekt/","vt."],
    ["decade","十年","/ˈdekeɪd/","n."],["tend","倾向；照顾","/tend/","vt.&vi."],
    ["publish","发表","/ˈpʌblɪʃ/","vt."],["staff","员工","/stæf/","n."],
    ["retire","退休","/rɪˈtaɪər/","vi.&vt."],["saving","存款","/ˈseɪvɪŋ/","n."],
    ["principle","原则","/ˈprɪnsəpl/","n."],["passive","被动的","/ˈpæsɪv/","adj."],
    ["scared","害怕的","/skerd/","adj."],["scare","惊吓","/sker/","vt."],
    ["sharp","急剧的","/ʃɑːrp/","adj."],["insurance","保险","/ɪnˈʃʊrəns/","n."],
    ["energetic","精力充沛的","/ˌenərˈdʒetɪk/","adj."],["replace","取代","/rɪˈpleɪs/","vt."],
    ["accident","事故","/ˈæksɪdənt/","n."],["operation","手术","/ˌɑːpəˈreɪʃn/","n."],
    ["whisper","耳语","/ˈwɪspər/","vi.&vt."],["midnight","午夜","/ˈmɪdnaɪt/","n."],
    ["import","进口","/ˈɪmpɔːrt/","n.&vt."],["export","出口","/ˈekspɔːrt/","n.&vt."],
    ["pole","极点","/poʊl/","n."],["bite","咬","/baɪt/","vt.&vi."],
    ["lip","嘴唇","/lɪp/","n."],["assist","帮助","/əˈsɪst/","vt."],
    ["memory","记忆","/ˈmeməri/","n."],["chain","链子","/tʃeɪn/","n."],
    ["disguise","伪装","/dɪsˈɡaɪz/","vt.&n."],["tear","眼泪","/tɪr/","n."],
    ["despair","绝望","/dɪˈsper/","n.&vi."],["harm","伤害","/hɑːrm/","n.&vt."],
    ["fable","寓言","/ˈfeɪbl/","n."],["flexible","灵活的","/ˈfleksəbl/","adj."],
    ["income","收入","/ˈɪnkʌm/","n."],["tension","紧张","/ˈtenʃn/","n."],
]]

B3U3=["Unit 3 Diverse Cultures", [
    ["diverse","多样的","/daɪˈvɜːrs/","adj."],["diversity","多样性","/daɪˈvɜːrsəti/","n."],
    ["fortune","运气","/ˈfɔːrtʃən/","n."],["chip","炸薯条；芯片","/tʃɪp/","n."],
    ["spicy","辛辣的","/ˈspaɪsi/","adj."],["ethnic","民族的","/ˈeθnɪk/","adj."],
    ["admit","承认","/ədˈmɪt/","vi.&vt."],["definitely","肯定","/ˈdefɪnətli/","adv."],
    ["occur","发生","/əˈkɜːr/","vi."],["downtown","市中心","/ˈdaʊntaʊn/","adv."],
    ["mission","使命","/ˈmɪʃn/","n."],["district","区域","/ˈdɪstrɪkt/","n."],
    ["comic","连环漫画","/ˈkɑːmɪk/","n.&adj."],["historical","历史的","/hɪˈstɔːrɪkl/","adj."],
    ["seek","寻找","/siːk/","vt.&vi."],["earn","挣得","/ɜːrn/","vt.&vi."],
    ["immigrant","移民","/ˈɪmɪɡrənt/","n."],["select","选择","/sɪˈlekt/","vt."],
    ["china","瓷器","/ˈtʃaɪnə/","n."],["jazz","爵士乐","/dʒæz/","n."],
    ["bar","酒吧","/bɑːr/","n."],["diagram","图表","/ˈdaɪəɡræm/","n."],
    ["journal","日志","/ˈdʒɜːrnl/","n."],["claim","声称","/kleɪm/","vt.&n."],
    ["series","一系列","/ˈsɪriːz/","n."],["minority","少数民族","/maɪˈnɔːrəti/","n."],
    ["escape","逃跑","/ɪˈskeɪp/","vi.&vt."],["Atlantic","大西洋的","/ətˈlæntɪk/","adj."],
    ["financial","金融的","/faɪˈnænʃl/","adj."],["poetry","诗歌","/ˈpoʊətri/","n."],
    ["jeans","牛仔裤","/dʒiːnz/","n."],["boot","靴子","/buːt/","n."],
    ["poisonous","有毒的","/ˈpɔɪzənəs/","adj."],["fold","折叠","/foʊld/","vt."],
    ["collection","收藏品","/kəˈlekʃn/","n."],["souvenir","纪念品","/ˌsuːvəˈnɪr/","n."],
    ["percentage","百分比","/pərˈsentɪdʒ/","n."],["climate","气候","/ˈklaɪmət/","n."],
    ["mild","温和的","/maɪld/","adj."],["settle","定居","/ˈsetl/","vi.&vt."],
    ["construction","建造","/kənˈstrʌkʃn/","n."],["material","材料","/məˈtɪriəl/","n."],
    ["clothing","服装","/ˈkloʊðɪŋ/","n."],["suit","适合","/suːt/","vt.&n."],
    ["item","项目","/ˈaɪtəm/","n."],["contain","包含","/kənˈteɪn/","vt."],
    ["neat","整洁的","/niːt/","adj."],["super","超级","/ˈsuːpər/","adv.&adj."],
]]

B3U4=["Unit 4 Space Exploration", [
    ["astronaut","宇航员","/ˈæstrənɔːt/","n."],["procedure","程序","/prəˈsiːdʒər/","n."],
    ["mental","精神的","/ˈmentl/","adj."],["intelligent","有智慧的","/ɪnˈtelɪdʒənt/","adj."],
    ["rocket","火箭","/ˈrɑːkɪt/","n."],["gravity","重力","/ˈɡrævəti/","n."],
    ["frontier","边境","/frʌnˈtɪr/","n."],["vehicle","交通工具","/ˈviːəkl/","n."],
    ["universe","宇宙","/ˈjuːnɪvɜːrs/","n."],["determined","有决心的","/dɪˈtɜːrmɪnd/","adj."],
    ["satellite","人造卫星","/ˈsætəlaɪt/","n."],["launch","发射","/lɔːntʃ/","vt.&n."],
    ["orbit","轨道","/ˈɔːrbɪt/","n.&vt."],["giant","巨大的","/ˈdʒaɪənt/","adj.&n."],
    ["leap","跳跃","/liːp/","n.&vi."],["mankind","人类","/mænˈkaɪnd/","n."],
    ["agency","机构","/ˈeɪdʒənsi/","n."],["transmit","传输","/trænzˈmɪt/","vt.&vi."],
    ["data","数据","/ˈdeɪtə/","n."],["disappointed","失望的","/ˌdɪsəˈpɔɪntɪd/","adj."],
    ["desire","渴望","/dɪˈzaɪər/","n.&vt."],["ongoing","持续进行的","/ˈɑːnɡoʊɪŋ/","adj."],
    ["independent","独立的","/ˌɪndɪˈpendənt/","adj."],["spacecraft","航天器","/ˈspeɪskræft/","n."],
    ["signal","信号","/ˈsɪɡnəl/","vt.&n."],["recycle","回收","/ˌriːˈsaɪkl/","vt."],
    ["muscle","肌肉","/ˈmʌsl/","n."],["lack","缺乏","/læk/","n.&vt."],
    ["float","漂浮","/floʊt/","vi.&vt."],["otherwise","否则","/ˈʌðərwaɪz/","adv."],
    ["beyond","超出","/bɪˈjɑːnd/","prep."],["solar","太阳的","/ˈsoʊlər/","adj."],
    ["current","当前的","/ˈkɜːrənt/","adj.&n."],["sufficient","足够的","/səˈfɪʃnt/","adj."],
    ["microwave","微波炉","/ˈmaɪkrəweɪv/","n."],["tissue","纸巾；组织","/ˈtɪʃuː/","n."],
    ["facility","设施","/fəˈsɪləti/","n."],["keen","热衷的","/kiːn/","adj."],
    ["globe","地球仪","/ɡloʊb/","n."],["argue","论证","/ˈɑːrɡjuː/","vt.&vi."],
    ["fatal","致命的","/ˈfeɪtl/","adj."],["shallow","肤浅的","/ˈʃæloʊ/","adj."],
    ["pattern","模式","/ˈpætərn/","n."],["analysis","分析","/əˈnæləsɪs/","n."],
    ["monitor","监视器","/ˈmɑːnɪtər/","n.&vt."],["regularly","定期地","/ˈreɡjələrli/","adv."],
    ["resource","资源","/ˈriːsɔːrs/","n."],["limited","有限的","/ˈlɪmɪtɪd/","adj."],
    ["mystery","神秘","/ˈmɪstəri/","n."],["oxygen","氧气","/ˈɑːksɪdʒən/","n."],
]]

B3U5=["Unit 5 The Value of Money", [
    ["basis","基础","/ˈbeɪsɪs/","n."],["loan","贷款","/loʊn/","n."],
    ["plastic","塑料","/ˈplæstɪk/","n.&adj."],["apologise","道歉","/əˈpɑːlədʒaɪz/","vi."],
    ["ignore","忽视","/ɪɡˈnɔːr/","vt."],["judge","评判；法官","/dʒʌdʒ/","vt.&n."],
    ["scene","场景","/siːn/","n."],["narrator","叙述者","/nəˈreɪtər/","n."],
    ["bet","打赌","/bet/","n.&vt."],["servant","仆人","/ˈsɜːrvənt/","n."],
    ["sail","航行","/seɪl/","vi.&vt."],["spot","发现；地点","/spɑːt/","vt.&n."],
    ["dare","敢于","/der/","vi.&modal v."],["sort","种类","/sɔːrt/","n."],
    ["patience","耐心","/ˈpeɪʃns/","n."],["ought","应该","/ɔːt/","modal v."],
    ["indicate","表明","/ˈɪndɪkeɪt/","vt.&vi."],["beneath","在……下面","/bɪˈniːθ/","adv.&prep."],
    ["postpone","延迟","/poʊˈspoʊn/","vt."],["odd","奇怪的","/ɑːd/","adj."],
    ["obligation","义务","/ˌɑːblɪˈɡeɪʃn/","n."],["intention","意图","/ɪnˈtenʃn/","n."],
    ["nowhere","无处","/ˈnoʊwer/","adv."],["extent","程度","/ɪkˈstent/","n."],
    ["opera","歌剧","/ˈɑːpərə/","n."],["musical","音乐剧","/ˈmjuːzɪkl/","n.&adj."],
    ["dinosaur","恐龙","/ˈdaɪnəsɔːr/","n."],["hug","拥抱","/hʌɡ/","vt.&vi."],
    ["pursue","追求","/pərˈsuː/","vt."],["duty","责任","/ˈduːti/","n."],
    ["hesitate","犹豫","/ˈhezɪteɪt/","vi."],["sequence","顺序","/ˈsiːkwəns/","n.&vt."],
    ["eventually","最终","/ɪˈventʃuəli/","adv."],["tailor","裁缝","/ˈteɪlər/","n.&vt."],
    ["clerk","职员","/klɜːrk/","n."],["manner","举止","/ˈmænər/","n."],
    ["downstairs","在楼下","/ˌdaʊnˈsterz/","adv."],["aside","到旁边","/əˈsaɪd/","adv."],
    ["frown","皱眉","/fraʊn/","n.&vi."],["option","选项","/ˈɑːpʃn/","n."],
    ["broad","宽阔的","/brɔːd/","adj."],["indeed","确实","/ɪnˈdiːd/","adv."],
    ["normal","正常的","/ˈnɔːrml/","adj."],["willing","愿意的","/ˈwɪlɪŋ/","adj."],
    ["element","要素","/ˈelɪmənt/","n."],["plot","情节","/plɑːt/","n."],
    ["maintain","维持","/meɪnˈteɪn/","vt."],["permission","许可","/pərˈmɪʃn/","n."],
    ["permit","允许","/pərˈmɪt/","vt.&vi."],["saying","谚语","/ˈseɪɪŋ/","n."],
]]

# Now combine B3 into grade10
g10["units"].extend([
    {"unit":11,"title":B3U1[0],"words":_r(B3U1[1])},
    {"unit":12,"title":B3U2[0],"words":_r(B3U2[1])},
    {"unit":13,"title":B3U3[0],"words":_r(B3U3[1])},
    {"unit":14,"title":B3U4[0],"words":_r(B3U4[1])},
    {"unit":15,"title":B3U5[0],"words":_r(B3U5[1])},
])
S("grade10.json",g10)

# ================================================================
# GRADE 11 (高二): 选择性必修一 + 选择性必修二 (10 units)
# ================================================================
# 选必一 U1-U5
XB1U1=["Unit 1 People of Achievement", [
    ["physiology","生理学","/ˌfɪziˈɑːlədʒi/","n."],["artemisinin","青蒿素","/ˌɑːrtɪˈmiːsɪnɪn/","n."],
    ["crucial","至关重要的","/ˈkruːʃl/","adj."],["committed","尽心尽力的","/kəˈmɪtɪd/","adj."],
    ["academy","学院；学会","/əˈkædəmi/","n."],["objective","目标；客观的","/əbˈdʒektɪv/","n.&adj."],
    ["botanical","植物学的","/bəˈtænɪkl/","adj."],["evaluate","评估","/ɪˈvæljueɪt/","vt."],
    ["property","性质；财产","/ˈprɑːpərti/","n."],["distinct","清晰的","/dɪˈstɪŋkt/","adj."],
    ["extract","提取","/ɪkˈstrækt/","vt.&n."],["wormwood","蒿","/ˈwɜːrmwʊd/","n."],
    ["boil","煮沸","/bɔɪl/","vt.&vi."],["liquid","液体","/ˈlɪkwɪd/","n.&adj."],
    ["obtain","获得","/əbˈteɪn/","vt.&vi."],["substance","物质","/ˈsʌbstəns/","n."],
    ["insist","坚持","/ɪnˈsɪst/","vi.&vt."],["conclusion","结论","/kənˈkluːʒn/","n."],
    ["circumstance","条件","/ˈsɜːrkəmstæns/","n."],["consequence","结果","/ˈkɑːnsɪkwens/","n."],
    ["encounter","偶然碰到","/ɪnˈkaʊntər/","vt.&n."],["remarkable","非凡的","/rɪˈmɑːrkəbl/","adj."],
    ["apparently","显然","/əˈpærəntli/","adv."],["scientific","科学的","/ˌsaɪənˈtɪfɪk/","adj."],
    ["novelist","小说家","/ˈnɑːvəlɪst/","n."],["politician","政治家","/ˌpɑːləˈtɪʃn/","n."],
    ["relativity","相对论","/ˌreləˈtɪvəti/","n."],["passion","热情","/ˈpæʃn/","n."],
    ["genius","天才","/ˈdʒiːniəs/","n."],["professor","教授","/prəˈfesər/","n."],
    ["institution","机构","/ˌɪnstɪˈtuːʃn/","n."],["consequence","后果","/ˈkɑːnsɪkwens/","n."],
    ["sum","金额；总和","/sʌm/","n."],["draft","草稿","/dræft/","n.&vt."],
    ["PhD","博士学位","/ˌpiː eɪtʃ ˈdiː/","abbr."],
]]

XB1U2=["Unit 2 Looking into the Future", [
    ["phrase","短语","/freɪz/","n."],["persuade","说服","/pərˈsweɪd/","vt."],
    ["switch","开关；转变","/swɪtʃ/","vt.&n."],["remote","远程的","/rɪˈmoʊt/","adj."],
    ["automatic","自动的","/ˌɔːtəˈmætɪk/","adj."],["integrated","集成的","/ˈɪntɪɡreɪtɪd/","adj."],
    ["sensor","传感器","/ˈsensər/","n."],["efficient","高效的","/ɪˈfɪʃnt/","adj."],
    ["mode","模式","/moʊd/","n."],["routine","常规","/ruːˈtiːn/","n."],
    ["preference","偏好","/ˈprefrəns/","n."],["instant","即时的","/ˈɪnstənt/","adj."],
    ["command","命令","/kəˈmænd/","n.&vt."],["obey","服从","/əˈbeɪ/","vi.&vt."],
    ["warning","警告","/ˈwɔːrnɪŋ/","n."],["constant","不断的","/ˈkɑːnstənt/","adj."],
    ["abnormal","不正常的","/æbˈnɔːrml/","adj."],["critical","批评的；关键的","/ˈkrɪtɪkl/","adj."],
    ["potential","潜在的","/pəˈtenʃl/","adj.&n."],["leak","泄漏","/liːk/","vi.&vt."],
    ["innovation","创新","/ˌɪnəˈveɪʃn/","n."],["available","可获得的","/əˈveɪləbl/","adj."],
    ["forecast","预测","/ˈfɔːrkæst/","vt.&n."],["artificial","人工的","/ˌɑːrtɪˈfɪʃl/","adj."],
    ["predict","预测","/prɪˈdɪkt/","vt."],["combine","结合","/kəmˈbaɪn/","vt.&vi."],
    ["occupation","职业","/ˌɑːkjuˈpeɪʃn/","n."],["absence","缺席","/ˈæbsəns/","n."],
    ["emphasis","强调","/ˈemfəsɪs/","n."],["luxury","奢侈","/ˈlʌkʃəri/","n."],
    ["career","职业","/kəˈrɪr/","n."],["prospect","前景","/ˈprɑːspekt/","n."],
    ["resist","抵制","/rɪˈzɪst/","vt.&vi."],["paragraph","段落","/ˈpærəɡræf/","n."],
    ["signpost","路标","/ˈsaɪnpoʊst/","n."],["essay","文章","/ˈeseɪ/","n."],
]]

XB1U3=["Unit 3 Fascinating Parks", [
    ["buffet","自助餐","/bəˈfeɪ/","n."],["edge","边缘","/edʒ/","n."],
    ["valley","山谷","/ˈvæli/","n."],["vast","辽阔的","/væst/","adj."],
    ["glacier","冰川","/ˈɡleɪʃər/","n."],["reindeer","驯鹿","/ˈreɪndɪr/","n."],
    ["territory","领土","/ˈterətɔːri/","n."],["ban","禁止","/bæn/","vt.&n."],
    ["boundary","边界","/ˈbaʊndri/","n."],["cottage","小屋","/ˈkɑːtɪdʒ/","n."],
    ["visible","看得见的","/ˈvɪzəbl/","adj."],["accompany","陪同","/əˈkʌmpəni/","vt."],
    ["adopt","采纳；收养","/əˈdɑːpt/","vt."],["sour","酸的","/ˈsaʊər/","adj."],
    ["cream","奶油","/kriːm/","n."],["bush","灌木","/bʊʃ/","n."],
    ["theme","主题","/θiːm/","n."],["incredible","难以置信的","/ɪnˈkredəbl/","adj."],
    ["appeal","吸引；呼吁","/əˈpiːl/","vi.&n."],["adorable","可爱的","/əˈdɔːrəbl/","adj."],
    ["wander","漫步","/ˈwɑːndər/","vi.&vt."],["amusement","娱乐","/əˈmjuːzmənt/","n."],
    ["swing","摇摆","/swɪŋ/","vi.&vt."],["iron","铁","/ˈaɪərn/","n.&adj."],
    ["steel","钢","/stiːl/","n."],["display","展示","/dɪˈspleɪ/","vt.&n."],
    ["rare","稀有的","/rer/","adj."],["superb","极好的","/suːˈpɜːrb/","adj."],
    ["aquarium","水族馆","/əˈkweriəm/","n."],["upwards","向上","/ˈʌpwərdz/","adv."],
    ["column","柱子","/ˈkɑːləm/","n."],["label","标签","/ˈleɪbl/","vt.&n."],
]]

XB1U4=["Unit 4 Body Language", [
    ["interaction","互动","/ˌɪntərˈækʃn/","n."],["vary","变化","/ˈveri/","vi."],
    ["appropriate","适当的","/əˈproʊpriət/","adj."],["gesture","手势","/ˈdʒestʃər/","n."],
    ["witness","目击；证人","/ˈwɪtnəs/","vt.&n."],["employ","使用；雇佣","/ɪmˈplɔɪ/","vt."],
    ["identical","相同的","/aɪˈdentɪkl/","adj."],["interpret","解释","/ɪnˈtɜːrprɪt/","vt."],
    ["differ","不同","/ˈdɪfər/","vi."],["favour","帮助；偏爱","/ˈfeɪvər/","vt.&n."],
    ["bow","鞠躬","/baʊ/","vi.&n."],["barrier","障碍","/ˈbæriər/","n."],
    ["fake","假的","/feɪk/","adj."],["anger","愤怒","/ˈæŋɡər/","n."],
    ["reliable","可靠的","/rɪˈlaɪəbl/","adj."],["incident","事件","/ˈɪnsɪdənt/","n."],
    ["trial","审判","/ˈtraɪəl/","n."],["slight","轻微的","/slaɪt/","adj."],
    ["twin","双胞胎","/twɪn/","adj.&n."],["nonverbal","非语言的","/nɑːnˈvɜːrbl/","adj."],
    ["assess","评估","/əˈses/","vt."],["internal","内部的","/ɪnˈtɜːrnl/","adj."],
    ["pose","姿势；造成","/poʊz/","n.&vt."],["bend","弯曲","/bend/","vt.&vi."],
    ["reveal","揭示","/rɪˈviːl/","vt."],["clarify","澄清","/ˈklærəfaɪ/","vt."],
    ["tick","勾号","/tɪk/","vt.&n."],["tendency","趋势","/ˈtendənsi/","n."],
    ["occupy","占据","/ˈɑːkjupaɪ/","vt."],["stare","凝视","/ster/","vi."],
    ["ceiling","天花板","/ˈsiːlɪŋ/","n."],["distract","分心","/dɪˈstrækt/","vt."],
]]

XB1U5=["Unit 5 Working the Land", [
    ["hybrid","杂交的","/ˈhaɪbrɪd/","adj.&n."],["devote","致力于","/dɪˈvoʊt/","vt."],
    ["shortage","短缺","/ˈʃɔːrtɪdʒ/","n."],["tackle","解决","/ˈtækl/","vt."],
    ["crisis","危机","/ˈkraɪsɪs/","n."],["boost","促进","/buːst/","vt."],
    ["yield","产量","/jiːld/","n.&vt."],["convince","说服","/kənˈvɪns/","vt."],
    ["characteristic","特征","/ˌkærəktəˈrɪstɪk/","n.&adj."],["attain","获得","/əˈteɪn/","vt."],
    ["conventional","传统的","/kənˈvenʃənl/","adj."],["assumption","假设","/əˈsʌmpʃn/","n."],
    ["intense","强烈的","/ɪnˈtens/","adj."],["overcome","克服","/ˌoʊvərˈkʌm/","vt."],
    ["expand","扩大","/ɪkˈspænd/","vt.&vi."],["output","产量","/ˈaʊtpʊt/","n."],
    ["domestic","国内的","/dəˈmestɪk/","adj."],["consumption","消费","/kənˈsʌmpʃn/","n."],
    ["comprise","包括","/kəmˈpraɪz/","vt."],["generate","产生","/ˈdʒenəreɪt/","vt."],
    ["strain","品种；压力","/streɪn/","n."],["leisure","休闲","/ˈliːʒər/","n."],
    ["soil","土壤","/sɔɪl/","n."],["celebrity","名人","/səˈlebrəti/","n."],
    ["grain","谷物","/ɡreɪn/","n."],["organic","有机的","/ɔːrˈɡænɪk/","adj."],
    ["pesticide","杀虫剂","/ˈpestɪsaɪd/","n."],["widespread","广泛的","/ˈwaɪdspred/","adj."],
    ["nutrition","营养","/nuˈtrɪʃn/","n."],["digest","消化","/daɪˈdʒest/","vt.&vi."],
    ["alternative","替代的","/ɔːlˈtɜːrnətɪv/","n.&adj."],["instance","例子","/ˈɪnstəns/","n."],
    ["depth","深度","/depθ/","n."],["root","根","/ruːt/","n."],
    ["entirely","完全地","/ɪnˈtaɪərli/","adv."],["aspect","方面","/ˈæspekt/","n."],
]]

g11={"grade":"高二","semester":"选择性必修一~二 (共2册)","textbook":"2019人教版高中英语",
     "units":[
         {"unit":1,"title":XB1U1[0],"words":_r(XB1U1[1])},
         {"unit":2,"title":XB1U2[0],"words":_r(XB1U2[1])},
         {"unit":3,"title":XB1U3[0],"words":_r(XB1U3[1])},
         {"unit":4,"title":XB1U4[0],"words":_r(XB1U4[1])},
         {"unit":5,"title":XB1U5[0],"words":_r(XB1U5[1])},
     ]}
S("grade11.json",g11)

# ================================================================
# GRADE 12 (高三): 选择性必修三 + 四 (10 units)
# ================================================================
XB3U1=["Unit 1 Art", [
    ["precisely","准确地","/prɪˈsaɪsli/","adv."],["realistic","现实的","/ˌriːəˈlɪstɪk/","adj."],
    ["primitive","原始的","/ˈprɪmətɪv/","adj."],["dimension","维度","/daɪˈmenʃn/","n."],
    ["influential","有影响力的","/ˌɪnfluˈenʃl/","adj."],["reputation","名誉","/ˌrepjuˈteɪʃn/","n."],
    ["rank","等级","/ræŋk/","n.&vt."],["purchase","购买","/ˈpɜːrtʃəs/","vt.&n."],
    ["mythology","神话","/mɪˈθɑːlədʒi/","n."],["client","客户","/ˈklaɪənt/","n."],
    ["photography","摄影","/fəˈtɑːɡrəfi/","n."],["emerge","出现","/iˈmɜːrdʒ/","vi."],
    ["sunrise","日出","/ˈsʌnraɪz/","n."],["convey","传达","/kənˈveɪ/","vt."],
    ["subjective","主观的","/səbˈdʒektɪv/","adj."],["outer","外部的","/ˈaʊtər/","adj."],
    ["canvas","画布","/ˈkænvəs/","n."],["exhibition","展览","/ˌeksɪˈbɪʃn/","n."],
    ["bronze","青铜","/brɑːnz/","n."],["ceramic","陶瓷的","/səˈræmɪk/","adj.&n."],
    ["vase","花瓶","/veɪs/","n."],["artistic","艺术的","/ɑːrˈtɪstɪk/","adj."],
    ["sculpture","雕塑","/ˈskʌlptʃər/","n."],["critic","评论家","/ˈkrɪtɪk/","n."],
    ["representative","代表","/ˌreprɪˈzentətɪv/","adj.&n."],["decline","下降","/dɪˈklaɪn/","n.&vi."],
    ["recognition","认出","/ˌrekəɡˈnɪʃn/","n."],["expansion","扩张","/ɪkˈspænʃn/","n."],
    ["guarantee","保证","/ˌɡærənˈtiː/","vt.&n."],["contemporary","当代的","/kənˈtempəreri/","adj."],
    ["permanent","永久的","/ˈpɜːrmənənt/","adj."],
]]

XB3U2=["Unit 2 Healthy Lifestyle", [
    ["tobacco","烟草","/təˈbækoʊ/","n."],["alcohol","酒精","/ˈælkəhɔːl/","n."],
    ["abuse","滥用","/əˈbjuːz/","n.&vt."],["physical","身体的","/ˈfɪzɪkl/","adj."],
    ["dominate","支配","/ˈdɑːmɪneɪt/","vt.&vi."],["psychology","心理学","/saɪˈkɑːlədʒi/","n."],
    ["reward","奖励","/rɪˈwɔːrd/","n.&vt."],["rely","依赖","/rɪˈlaɪ/","vi."],
    ["facilitate","促进","/fəˈsɪlɪteɪt/","vt."],["examine","检查","/ɪɡˈzæmɪn/","vt."],
    ["negative","消极的","/ˈneɡətɪv/","adj."],["discipline","纪律","/ˈdɪsəplɪn/","n."],
    ["pill","药丸","/pɪl/","n."],["delete","删除","/dɪˈliːt/","vt."],
    ["compose","组成","/kəmˈpoʊz/","vt.&vi."],["surgeon","外科医生","/ˈsɜːrdʒən/","n."],
    ["surgery","外科手术","/ˈsɜːrdʒəri/","n."],["organ","器官","/ˈɔːrɡən/","n."],
    ["toxin","毒素","/ˈtɑːksɪn/","n."],["nutritional","营养的","/nuˈtrɪʃənl/","adj."],
    ["pessimistic","悲观的","/ˌpesɪˈmɪstɪk/","adj."],["monthly","每月的","/ˈmʌnθli/","adj.&adv."],
    ["enhance","增强","/ɪnˈhæns/","vt."],["refresh","刷新","/rɪˈfreʃ/","vt."],
    ["absorb","吸收","/əbˈzɔːrb/","vt."],["dynamic","充满活力的","/daɪˈnæmɪk/","adj."],
]]

# Now SAVE all
g11["units"].extend([
    {"unit":6,"title":XB3U1[0],"words":_r(XB3U1[1])},
    {"unit":7,"title":XB3U2[0],"words":_r(XB3U2[1])},
])
S("grade11.json",g11)

XB3U3=["Unit 3 Environmental Protection", [
    ["graph","图表","/ɡræf/","n."],["emission","排放","/iˈmɪʃn/","n."],
    ["melt","融化","/melt/","vi.&vt."],["starve","挨饿","/stɑːrv/","vi.&vt."],
    ["ecology","生态","/iˈkɑːlədʒi/","n."],["habitat","栖息地","/ˈhæbɪtæt/","n."],
    ["sustain","维持","/səˈsteɪn/","vt."],["comprehensive","全面的","/ˌkɑːmprɪˈhensɪv/","adj."],
    ["trend","趋势","/trend/","n."],["frequently","经常地","/ˈfriːkwəntli/","adv."],
    ["broadcast","广播","/ˈbrɔːdkæst/","vt.&n."],["policy","政策","/ˈpɑːləsi/","n."],
    ["restrict","限制","/rɪˈstrɪkt/","vt."],["seize","抓住","/siːz/","vt."],
    ["submit","提交","/səbˈmɪt/","vt.&vi."],["sensitive","敏感的","/ˈsensətɪv/","adj."],
    ["jungle","丛林","/ˈdʒʌŋɡl/","n."],["smog","雾霾","/smɑːɡ/","n."],
    ["volume","量；音量","/ˈvɑːljuːm/","n."],["garbage","垃圾","/ˈɡɑːrbɪdʒ/","n."],
    ["enterprise","企业","/ˈentərpraɪz/","n."],["restore","恢复","/rɪˈstɔːr/","vt."],
    ["conservation","保护","/ˌkɑːnsərˈveɪʃn/","n."],["agenda","议程","/əˈdʒendə/","n."],
    ["tolerate","容忍","/ˈtɑːləreɪt/","vt."],["carbon","碳","/ˈkɑːrbən/","n."],
    ["nuclear","核能的","/ˈnuːkliər/","adj."],
]]

XB3U4=["Unit 4 Adversity and Courage", [
    ["adversity","逆境","/ədˈvɜːrsəti/","n."],["expedition","探险","/ˌekspəˈdɪʃn/","n."],
    ["endurance","耐力","/ɪnˈdʊrəns/","n."],["resolve","决心","/rɪˈzɑːlv/","vi.&vt.&n."],
    ["crew","船员","/kruː/","n."],["abandon","放弃","/əˈbændən/","vt."],
    ["stove","炉子","/stoʊv/","n."],["blanket","毯子","/ˈblæŋkɪt/","n."],
    ["belongings","财物","/bɪˈlɔːŋɪŋz/","n."],["banjo","班卓琴","/ˈbændʒoʊ/","n."],
    ["nephew","侄子","/ˈnefjuː/","n."],["voyage","航行","/ˈvɔɪɪdʒ/","n."],
    ["candidate","候选人","/ˈkændɪdeɪt/","n."],["commitment","承诺","/kəˈmɪtmənt/","n."],
    ["decent","体面的","/ˈdiːsnt/","adj."],["cosy","舒适的","/ˈkoʊzi/","adj."],
    ["genuine","真正的","/ˈdʒenjuɪn/","adj."],["persevere","坚持","/ˌpɜːrsɪˈvɪr/","vi."],
    ["resolve","决心","/rɪˈzɑːlv/","vi.&vt."],["fortunate","幸运的","/ˈfɔːrtʃənət/","adj."],
    ["bark","吠叫","/bɑːrk/","vi.&n."],["rugby","橄榄球","/ˈrʌɡbi/","n."],
    ["bat","蝙蝠","/bæt/","n."],["damp","潮湿的","/dæmp/","adj."],
    ["recreation","娱乐","/ˌrekriˈeɪʃn/","n."],["motor","发动机","/ˈmoʊtər/","n."],
]]

XB3U5=["Unit 5 Poems", [
    ["drama","戏剧","/ˈdrɑːmə/","n."],["sorrow","悲伤","/ˈsɑːroʊ/","n."],
    ["imagery","意象","/ˈɪmɪdʒəri/","n."],["literary","文学的","/ˈlɪtəreri/","adj."],
    ["rhyme","押韵","/raɪm/","n.&vi.&vt."],["folk","民间的","/foʊk/","adj.&n."],
    ["amateur","业余的","/ˈæmətər/","n.&adj."],["format","格式","/ˈfɔːrmæt/","n."],
    ["respective","各自的","/rɪˈspektɪv/","adj."],["sow","播种","/soʊ/","vt.&vi."],
    ["deadline","截止日期","/ˈdedlaɪn/","n."],["contest","比赛","/ˈkɑːntest/","n.&vt."],
    ["polish","润色","/ˈpɑːlɪʃ/","vt."],["string","细绳","/strɪŋ/","n."],
    ["wherever","无论哪里","/werˈevər/","conj.&adv."],["barren","荒芜的","/ˈbærən/","adj."],
    ["grief","悲伤","/ɡriːf/","n."],["complicated","复杂的","/ˈkɑːmplɪkeɪtɪd/","adj."],
    ["variation","变化","/ˌveriˈeɪʃn/","n."],["prejudice","偏见","/ˈpredʒədɪs/","n."],
    ["racial","种族的","/ˈreɪʃl/","adj."],["era","时代","/ˈɪrə/","n."],
    ["core","核心","/kɔːr/","n.&adj."],["version","版本","/ˈvɜːrʒn/","n."],
    ["innocent","天真的","/ˈɪnəsnt/","adj."],["delicate","精美的","/ˈdelɪkət/","adj."],
]]

g12={"grade":"高三","semester":"选择性必修三~四 (共2册)","textbook":"2019人教版高中英语",
     "units":[
         {"unit":1,"title":XB3U3[0],"words":_r(XB3U3[1])},
         {"unit":2,"title":XB3U4[0],"words":_r(XB3U4[1])},
         {"unit":3,"title":XB3U5[0],"words":_r(XB3U5[1])},
     ]}
S("grade12.json",g12)

print("\n==============================")
print("DONE! All high school vocab built.")
print("==============================")
